msgid ""
msgstr ""
"Project-Id-Version: friendly-traceback\n"
"POT-Creation-Date: 2022-10-24 10:58-0300\n"
"PO-Revision-Date: \n"
"Last-Translator: \n"
"Language-Team: \n"
"Language: es\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 3.1.1\n"

#: __init__.py:284 __main__.py:171
msgid "The file {filename} does not exist."
msgstr "El archivo {filename} no existe."

#: __init__.py:367
msgid "The available languages are:"
msgstr "Los idiomas disponibles son:"

#: __init__.py:395
msgid "{include}: Unrecognized value."
msgstr ""

#: __init__.py:396
msgid "The allowed values are:"
msgstr ""

#: about_warnings.py:88
msgid "Warning issued on line `{line}` of code block {filename}."
msgstr ""
"Excepción elevada en la linea `{line}` del bloque de código {filename}."

#: about_warnings.py:92
msgid "Warning issued on line `{line}` of file '{filename}'."
msgstr "Excepción elevada en la linea `{line}` del archivo '{filename}'."

#: about_warnings.py:137
msgid ""
"The source is unavailable.\n"
"If you used `exec`, consider using `friendly_exec` instead."
msgstr ""

#: base_formatters.py:192 base_formatters.py:198
msgid "I have no suggestion to offer."
msgstr "No tengo una sugerencia para ofrecer."

#: base_formatters.py:196
msgid "I have no suggestion to offer; try `why()`."
msgstr "No tengo una sugerencia para ofrecer; intenta con `why()`."

#: config.py:42
msgid ""
"Are you using a regular Python console instead of a Friendly console?\n"
"If so, to continue, try: `start_console(local_vars=locals())`.\n"
"You will need to import `start_console` if you have not already done so.\n"
msgstr ""
"¿Estás usando una consola normal de Python en lugar de una consola "
"Friendly?\n"
"Si es así, para continuar, prueba: `start_console(local_vars=locals())`.\n"
"Tendrás que importar `start_console` si no lo has hecho ya.\n"

#: config.py:76 config.py:194 console_helpers.py:43
msgid "Nothing to show: no exception recorded."
msgstr "Nada para mostrar: no se registró una excepción."

#: config.py:81 console_helpers.py:306
msgid "Invalid index value."
msgstr ""

#: config.py:320
msgid ""
"An exception occurred before friendly-traceback was imported.\n"
"Some information is available."
msgstr ""
"Se ha producido una excepción antes de importar el friendly-traceback.\n"
"Hay alguna información disponible."

#: console_helpers.py:49
msgid "Friendly-traceback is already disabled."
msgstr ""

#: console_helpers.py:59
msgid "Friendly-traceback is already enabled."
msgstr ""

#: console_helpers.py:109 functions_help.py:15
msgid "Shows a list of recorded traceback messages."
msgstr "Muestra una lista de los mensajes de traceback registrados."

#: console_helpers.py:111 functions_help.py:17
msgid "You can also use `history.clear()` and `history.pop()`."
msgstr ""

#: console_helpers.py:121
#, fuzzy
#| msgid "Nothing to show: no exception recorded."
msgid "Nothing to delete: no exception recorded."
msgstr "Nada para mostrar: no se registró una excepción."

#: console_helpers.py:128
msgid "There is no such history item."
msgstr ""

#: console_helpers.py:172 console_helpers.py:176
msgid "{exception} is not an exception."
msgstr "{exception} no es una excepción."

#: console_helpers.py:270
msgid "The default web browser cannot be used for searching."
msgstr "El navegador web por defecto no se puede utilizar para la búsqueda."

#: console_helpers.py:280
#, fuzzy
#| msgid ""
#| "Invalid argument for `www()`.\n"
#| "Valid arguments include `None` or one of `{sites}`.\n"
msgid ""
"Invalid argument for `www()`.\n"
"Valid arguments are integer values or one of `{sites}`.\n"
msgstr ""
"Argumento no valido para `www()`.\n"
"Los argumentos validos incluyen `None` o alguno de `{sites}`.\n"

#: console_helpers.py:478
msgid ""
"The following methods of the Friendly object should also be available as "
"functions."
msgstr ""
"Los siguientes métodos del objeto Friendly también deberían estar "
"disponibles como funciones."

#: core.py:125
msgid "More lines not shown."
msgstr "Más lineas no mostradas."

#: core.py:127 core.py:166
msgid "Python exception:"
msgstr "Excepción Python:"

#: core.py:180
msgid "The exception includes the following note:\n"
msgstr ""

#: core.py:184
msgid "The exception includes the following notes:\n"
msgstr ""

#: core.py:204
msgid ""
"Warning: improperly formed exception.\n"
"I suspect that a custom exception has been raised\n"
"with a non-string value used as a message.\n"
"This can occur if a `__repr__` or a `__str__` method\n"
"raises an exception or does not return a string.\n"
msgstr ""
"Advertencia: excepción mal formada.\n"
"Sospecho que se ha lanzado una excepción personalizada\n"
"con un valor que no es una cadena utilizado como mensaje.\n"
"Esto puede ocurrir si un método `__repr__` o un método `__str__`\n"
"lanza una excepción o no devuelve una cadena.\n"

#: core.py:255
msgid "The encoding of the file was not valid.\n"
msgstr "La codificación del archivo no era valida.\n"

#: core.py:335 core.py:356
msgid ""
"{filename} is not a regular Python file whose contents can be analyzed.\n"
msgstr ""
"{filename} no es un archivo regular de Python cuyo contenido pueda ser "
"analizado.\n"

#: core.py:339
msgid "If you used `exec`, consider using `friendly_exec` instead.\n"
msgstr ""

#: core.py:344
msgid "Exception raised on line `{linenumber}` of code block {filename}.\n"
msgstr ""
"Excepción elevada en la linea `{linenumber}` del bloque de código "
"'{filename}'.\n"

#: core.py:348
msgid "Exception raised on line `{linenumber}` of file '{filename}'.\n"
msgstr ""
"Excepción elevada en la linea `{linenumber}` del archivo '{filename}'.\n"

#: core.py:384
msgid "Execution stopped on line `{linenumber}` of code block {filename}.\n"
msgstr ""
"La ejecución se detuvo en la linea `{linenumber}` del bloque de "
"código{filename}.\n"

#: core.py:388
msgid "Execution stopped on line `{linenumber}` of file '{filename}'.\n"
msgstr ""
"La ejecución se detuvo en la linea `{linenumber}` del archivo '{filename}'.\n"

#: core.py:412
#, fuzzy
#| msgid "File {filename}, line {line}"
msgid "Code block {filename}, line `{line}`"
msgstr "Archivo {filename}, línea {line}"

#: core.py:416
msgid "File '{filename}', line `{line}`"
msgstr "Archivo {filename}, línea `{line}`"

#: core.py:430
msgid "The entire content of `{filename}` is not available.\n"
msgstr "El contenido completo de `{filename}` no está disponible.\n"

#: core.py:444
msgid "Python could not understand the code in the code block {filename}\n"
msgstr "Python no pudo entender el código en el bloque de código {filename}\n"

#: core.py:448
msgid ""
"Python could not understand the code in the file\n"
"'{filename}'\n"
msgstr ""
"Python no pudo entender el código en el archivo\n"
"'{filename}'\n"

#: core.py:453
msgid "at the location indicated.\n"
msgstr "en la ubicación indicada.\n"

#: core.py:689
msgid ""
"Unfortunately, no additional information is available:\n"
"the content of file '<stdin>' is not accessible.\n"
msgstr ""
"Lamentablemente, no hay información adicional disponible:\n"
"el contenido del archivo '<stdin>' no es accesible.\n"

#: debug_helper.py:41
msgid "Fatal error - aborting"
msgstr "Error fatal - abortando"

#: debug_helper.py:42
msgid "Please report this issue."
msgstr "Por favor, informe de este problema."

#: frame_info.py:85
msgid "Problem: source of `{filename}` is not available\n"
msgstr "Problema: la fuente de `{filename}` no está disponible\n"

#: ft_console.py:30
msgid "Use exit() or Ctrl-Z plus Return to exit."
msgstr ""

#: ft_console.py:32
msgid "Use exit() or Ctrl-D to exit."
msgstr ""

#: ft_console.py:33
msgid "Type 'Friendly' for help on special functions/methods."
msgstr ""
"Escriba 'Friendly' para obtener ayuda sobre funciones/métodos especiales."

#: ft_gettext.py:82
msgid ""
"Please report this example to\n"
"https://github.com/friendly-traceback/friendly-traceback/issues/new\n"
"If you are using a REPL, use `www('bug')` to do so.\n"
"\n"
msgstr ""
"Por favor, informe de este ejemplo a\n"
"https://github.com/friendly-traceback/friendly-traceback/issues/new\n"
"Si está utilizando un REPL, utilice `www('bug')` para hacerlo.\n"
"\n"

#: ft_gettext.py:90
msgid "Friendly-traceback does not know the cause of this error.\n"
msgstr "Friendly-traceback no conoce la causa de este error.\n"

#: ft_gettext.py:96
msgid "No information is known about this exception.\n"
msgstr "No se conoce ninguna información sobre esta excepción.\n"

#: ft_gettext.py:98
msgid ""
"If you are using the Friendly console, use `www()` to\n"
"do an Internet search for this particular case.\n"
msgstr ""
"Si está utilizando la consola Friendly, utilice `www()` para\n"
"hacer una búsqueda en Internet para este caso en particular.\n"

#: ft_gettext.py:107
msgid "Internal error for Friendly.\n"
msgstr "Error interno para Friendly.\n"

#: functions_help.py:10
msgid "Disable friendly-traceback and restore previous exception hook."
msgstr ""

#: functions_help.py:13
msgid "Enable friendly-traceback as an exception hook"
msgstr ""

#: functions_help.py:14
msgid "Shows all the information about the last traceback."
msgstr "Muestra toda la información sobre el último traceback."

#: functions_help.py:18
msgid "Sets the language to be used."
msgstr "Establece el idioma a utilizar."

#: functions_help.py:19
msgid "Shows the paths corresponding to synonyms used."
msgstr "Muestra las rutas correspondientes a los sinónimos utilizados."

#: functions_help.py:20
msgid "Shows the generic meaning of a given exception."
msgstr "Muestra el significado genérico de una determinada excepción."

#: functions_help.py:21
msgid "Shows where an exception was raised."
msgstr "Muestra dónde se ha producido una excepción."

#: functions_help.py:22
msgid "Shows the likely cause of the exception."
msgstr "Muestra la causa probable de la excepción."

#: functions_help.py:23
msgid "Opens a web browser at a useful location."
msgstr "Abre un navegador web en una ubicación útil."

#: functions_help.py:24
msgid "Suggestion sometimes added to a friendly traceback."
msgstr "Sugerencia que a veces se añade a un traceback amistoso."

#: functions_help.py:25
msgid "Shows a normal Python traceback."
msgstr "Muestra un traceback normal de Python."

#: functions_help.py:26
msgid "Shows a simplified Python traceback."
msgstr "Muestra un traceback simplificado de Python."

#: functions_help.py:27
msgid "Returns the current value used for items to include by default."
msgstr ""
"Devuelve el valor actual utilizado para los elementos a incluir por defecto."

#: functions_help.py:30
msgid "Sets the items to show by default when an exception is raised."
msgstr ""
"Establece los elementos a mostrar por defecto cuando se produce una "
"excepción."

#: functions_help.py:33
msgid "Returns the language currently used."
msgstr "Devuelve el idioma utilizado actualmente."

#: functions_help.py:34
msgid "Sets the formatter to use for display."
msgstr "Establece el formateador que será utilizado para mostrar."

#: functions_help.py:35
msgid "Use True (default) or False to enable debugging methods."
msgstr ""
"Utilice True (por defecto) o False para activar los métodos de depuración."

#: info_generic.py:43
msgid "A warning of type `{name}` is a subclass of `{parent}`.\n"
msgstr ""
"A warning of type `{name}` is a subclass of `{parent}`.\n"
"\n"

#: info_generic.py:47
msgid "An exception of type `{name}` is a subclass of `{parent}`.\n"
msgstr "Una excepción del tipo `{name}` es subclase de `{parent}`.\n"

#: info_generic.py:50
#, fuzzy
#| msgid ""
#| "The following are some of its known attributes:\n"
#| "`{names}`."
msgid "Nothing more specific is known about `{name}`."
msgstr ""
"A continuación se detallan algunos de sus atributos conocidos:\n"
"`{names}`."

#: info_generic.py:54
msgid ""
"The inheritance is as follows:\n"
"\n"
"    {tree}\n"
msgstr ""

#: info_generic.py:97
msgid ""
"All built-in exceptions defined by Python are derived from `Exception`.\n"
"All user-defined exceptions should also be derived from this class.\n"
msgstr ""

#: info_generic.py:105
msgid ""
"`BaseException` is the base class for all built-in exceptions.\n"
"It is not meant to be directly inherited by user-defined classes.\n"
msgstr ""

#: info_generic.py:113
#, fuzzy
#| msgid ""
#| "`ArithmeticError` is the base class for those built-in exceptions\n"
#| "that are raised for various arithmetic errors.\n"
#| "It is unusual that you are seeing this exception;\n"
#| "normally, a more specific exception should have been raised.\n"
msgid ""
"`ArithmeticError` is the base class for those built-in exceptions\n"
"that are raised for various arithmetic errors.\n"
msgstr ""
"`ArithmeticError` es la clase base para aquellas excepciones integradas al "
"lenguaje\n"
"que se producen por diversos errores aritméticos.\n"
"Es inusual que veas esta excepción;\n"
"normalmente, una excepción más específica debería haber sido lanzada.\n"

#: info_generic.py:121
msgid ""
"In Python, the keyword `assert` is used in statements of the form\n"
"`assert condition`, to confirm that `condition` is not `False`,\n"
"nor equivalent to `False` such as an empty list, etc.\n"
"\n"
"If `condition` is `False` or equivalent, an `AssertionError` is raised.\n"
msgstr ""
"En Python, la palabra clave `assert` se utiliza en sentencias de la forma\n"
"`assert condition`, para confirmar que `condition` no es `False`,\n"
"ni equivalente a `False`, como una lista vacía, etc.\n"
"\n"
"Si `condición` es `False` o equivalente, se produce un `AssertionError`.\n"

#: info_generic.py:131
msgid ""
"An `AttributeError` occurs when the code contains something like\n"
"    `object.x`\n"
"and `x` is not a method or attribute (variable) belonging to `object`.\n"
msgstr ""
"Un `AttributeError` ocurre cuando el código contiene algo como\n"
"    objeto.x\n"
"y `x` no es un método o atributo (variable) perteneciente al `objeto`.\n"

#: info_generic.py:140
msgid ""
"An `EOFError` is raised when the `input()` function hits\n"
"an end-of-file condition (EOF) without reading any data.\n"
msgstr ""
"Se produce un `EOFError` cuando la función `input()` alcanza\n"
"una condición de fin de archivo (EOF) sin leer ningún dato.\n"

#: info_generic.py:148
msgid ""
"A `FileNotFoundError` exception indicates that you\n"
"are trying to open a file that cannot be found by Python.\n"
"This could be because you misspelled the name of the file.\n"
msgstr ""
"Una excepción `FileNotFoundError` indica que estas\n"
"tratando de abrir un archivo que no puede ser encontrado por Python.\n"
"Esto puede deberse a que has escrito mal el nombre del archivo.\n"

#: info_generic.py:157
msgid ""
"An `ImportError` exception indicates that a certain object could not\n"
"be imported from a module or package. Most often, this is\n"
"because the name of the object is not spelled correctly.\n"
msgstr ""
"Una excepción `ImportError` indica que un determinado objeto no pudo\n"
"importarse de un módulo o paquete. La mayoría de las veces, esto se debe a "
"que\n"
"porque el nombre del objeto no está escrito correctamente.\n"

#: info_generic.py:166
msgid ""
"An `IndentationError` occurs when a given line of code is\n"
"not indented (aligned vertically with other lines) as expected.\n"
msgstr ""
"Un `IndentationError` ocurre cuando una línea de código dada no está\n"
"con la indentación (alineada verticalmente con otras líneas) que se espera.\n"

#: info_generic.py:174
msgid ""
"An `IndexError` occurs when you try to get an item from a list,\n"
"a tuple, or a similar object (sequence), and use an index which\n"
"does not exist; typically, this happens because the index you give\n"
"is greater than the length of the sequence.\n"
msgstr ""
"Un `IndexError` se produce cuando se intenta obtener un elemento de una "
"lista\n"
"una tupla, o un objeto similar (secuencia), y utiliza un índice que\n"
"no existe; normalmente, esto ocurre porque el índice que se da\n"
"es mayor que la longitud de la secuencia.\n"

#: info_generic.py:184
msgid ""
"A `KeyError` is raised when a value is not found as a\n"
"key in a Python dict or in a similar object.\n"
msgstr ""
"Se produce un `KeyError` cuando no se encuentra un valor como llave\n"
"en un dict de Python o en un objeto similar.\n"

#: info_generic.py:192
msgid ""
"`LookupError` is the base class for the exceptions that are raised\n"
"when a key or index used on a mapping or sequence is invalid.\n"
"It can also be raised directly by codecs.lookup().\n"
msgstr ""
"`LookupError` es la clase base para las excepciones que se producen\n"
"cuando una clave o índice utilizado en un mapeo o secuencia no es válido.\n"
"También puede ser elevada directamente por codecs.lookup().\n"

#: info_generic.py:201
msgid ""
"Like the name indicates, a `MemoryError` occurs when Python\n"
"runs out of memory. This can happen if you create an object\n"
"that is too big, like a list with too many items.\n"
msgstr ""
"Como su nombre indica, un `MemoryError` ocurre cuando Python\n"
"se queda sin memoria. Esto puede ocurrir si se crea un objeto\n"
"que es demasiado grande, como una lista con demasiados elementos.\n"

#: info_generic.py:210
msgid ""
"A `ModuleNotFoundError` exception indicates that you\n"
"are trying to import a module that cannot be found by Python.\n"
"This could be because you misspelled the name of the module\n"
"or because it is not installed on your computer.\n"
msgstr ""
"Una excepción `ModuleNotFoundError` indica que estás\n"
"está tratando de importar un módulo que no puede ser encontrado por Python.\n"
"Esto puede deberse a que has escrito mal el nombre del módulo\n"
"o porque no está instalado en tu computadora.\n"

#: info_generic.py:220
msgid ""
"A `NameError` exception indicates that a variable or\n"
"function name is not known to Python.\n"
"Most often, this is because there is a spelling mistake.\n"
"However, sometimes it is because the name is used\n"
"before being defined or given a value.\n"
msgstr ""
"Una excepción `NameError` indica que una variable o\n"
"nombre de función no es conocido por Python.\n"
"La mayoría de las veces, esto se debe a un error ortográfico.\n"
"Sin embargo, a veces es porque el nombre se utiliza\n"
"antes de ser definido o de recibir un valor.\n"

#: info_generic.py:231
msgid ""
"An `OSError` exception is usually raised by the Operating System\n"
"to indicate that an operation is not allowed or that\n"
"a resource is not available.\n"
msgstr ""
"El sistema operativo suele lanzar una excepción `OSError` para indicar que "
"una operación\n"
"para indicar que una operación no está permitida o que\n"
"un recurso no está disponible.\n"

#: info_generic.py:240
msgid ""
"An `OverflowError` is raised when the result of an arithmetic operation\n"
"is too large to be handled by the computer's processor.\n"
msgstr ""
"Se produce un `OverflowError` cuando el resultado de una operación "
"aritmética\n"
"es demasiado grande para ser manejado por el procesador del ordenador.\n"

#: info_generic.py:248
msgid ""
"A `RecursionError` is raised when a function calls itself,\n"
"directly or indirectly, too many times.\n"
"It almost always indicates that you made an error in your code\n"
"and that your program would never stop.\n"
msgstr ""
"Un `RecursionError` se levanta cuando una función se llama a sí misma\n"
"directa o indirectamente, demasiadas veces.\n"
"Casi siempre indica que has cometido un error en tu código\n"
"y que su programa nunca se detendrá.\n"

#: info_generic.py:258
msgid ""
"A `RuntimeError` is raised when an error is detected that doesn't fall in "
"any\n"
"of the more specific exception types defined by Python.\n"
msgstr ""

#: info_generic.py:266
msgid ""
"`StopIteration` is raised to indicate that an iterator has no more\n"
"item to provide when its `__next__` method is called by\n"
"the `next()` builtin function.\n"
msgstr ""
"`StopIteration` se eleva para indicar que un iterador no tiene más\n"
"elementos para proporcionar cuando su método `__next__` es llamado por\n"
"la función incorporada `next()`.\n"

#: info_generic.py:275
msgid "A `SyntaxError` occurs when Python cannot understand your code.\n"
msgstr "Un `SyntaxError` ocurre cuando Python no puede entender tu código.\n"

#: info_generic.py:280
msgid ""
"A `TabError` indicates that you have used both spaces\n"
"and tab characters to indent your code.\n"
"This is not allowed in Python.\n"
"Indenting your code means to have block of codes aligned vertically\n"
"by inserting either spaces or tab characters at the beginning of lines.\n"
"Python's recommendation is to always use spaces to indent your code.\n"
msgstr ""
"Un `TabError` indica que ha utilizado tanto espacios\n"
"y caracteres de tabulación para indentar tu código.\n"
"Esto no está permitido en Python.\n"
"Indentar tu código significa tener un bloque de código alineado "
"verticalmente\n"
"insertando espacios o caracteres de tabulación al principio de las líneas.\n"
"La recomendación de Python es utilizar siempre espacios para sangrar el "
"código.\n"

#: info_generic.py:292
msgid ""
"A `TypeError` is usually caused by trying\n"
"to combine two incompatible types of objects,\n"
"by calling a function with the wrong type of object,\n"
"or by trying to do an operation not allowed on a given type of object.\n"
msgstr ""
"Un `TypeError` suele producirse al intentar\n"
"combinar dos tipos de objetos incompatibles,\n"
"por llamar a una función con el tipo de objeto equivocado,\n"
"o por intentar realizar una operación no permitida en un tipo de objeto "
"determinado.\n"

#: info_generic.py:302
msgid ""
"A `ValueError` indicates that a function or an operation\n"
"received an argument of the right type, but an inappropriate value.\n"
msgstr ""
"Un `ValueError` indica que una función o una operación\n"
"recibió un argumento del tipo correcto, pero un valor inapropiado.\n"

#: info_generic.py:310
msgid ""
"In Python, variables that are used inside a function are known as \n"
"local variables. Before they are used, they must be assigned a value.\n"
"A variable that is used before it is assigned a value is assumed to\n"
"be defined outside that function; it is known as a `global`\n"
"(or sometimes `nonlocal`) variable. You cannot assign a value to such\n"
"a global variable inside a function without first indicating to\n"
"Python that this is a global variable, otherwise you will see\n"
"an `UnboundLocalError`.\n"
msgstr ""
"En Python, las variables que se utilizan dentro de una función sé conocen\n"
"como variables locales. Previo a ser empleadas, se les debe asignar un "
"valor.\n"
"Una variable que se emplea antes de que se le asigne\n"
"un valor se supone que está definida fuera de esa función; se \n"
"conoce como `global` (o a veces `no local`). No se puede asignar un\n"
"valor a dicha variable global dentro de una función sin indicar primero a\n"
"Python que se trata de una variable global, de lo contrario verá\n"
"un `UnboundLocalError`.\n"

#: info_generic.py:324
msgid ""
"A `ZeroDivisionError` occurs when you are attempting to divide a value\n"
"by zero either directly or by using some other mathematical operation.\n"
msgstr ""
"Un `ZeroDivisionError` ocurre cuando se intenta dividir un valor\n"
"por cero, ya sea directamente o utilizando alguna otra operación "
"matemática.\n"

#: info_generic.py:332
msgid "`UserWarning` is the default class for `warnings.warn()`.\n"
msgstr ""

#: info_generic.py:337
msgid ""
"`SyntaxWarning` often indicates that your code will likely not give the "
"result you expect.\n"
msgstr ""

#: info_generic.py:344
msgid ""
"`DeprecationWarning` indicates that some feature will not be available in a "
"future version.\n"
msgstr ""

#: info_generic.py:351
msgid ""
"`RuntimeWarning` often indicates some not recommended runtime features.\n"
msgstr ""

#: info_generic.py:358
msgid ""
"`FutureWarning` is the base category for features that will likely be "
"deprecated\n"
"in future Python versions.\n"
msgstr ""

#: info_generic.py:366
msgid ""
"`UnicodeWarning` is the base category for warnings related to unicode.\n"
msgstr ""

#: info_generic.py:371
msgid ""
"`BytesWarning` is the base category for warnings related to bytes and "
"bytearray.\n"
msgstr ""

#: info_generic.py:378
msgid "`Warning` is the base class of all warning category classes.\n"
msgstr ""

#: info_variables.py:69
msgid "a complex number"
msgstr "un número complejo"

#: info_variables.py:70
msgid "a dictionary (`dict`)"
msgstr "un diccionario (`dict`)"

#: info_variables.py:71
msgid "a number (`float`)"
msgstr "un número (`float`)"

#: info_variables.py:72
msgid "a `frozenset`"
msgstr "un `frozenset`"

#: info_variables.py:73
msgid "an integer (`int`)"
msgstr "un número entero (`int`)"

#: info_variables.py:74
msgid "a `list`"
msgstr "una `list`"

#: info_variables.py:75
msgid "a variable equal to `None` (`NoneType`)"
msgstr "una variable igual a `None` (`NoneType`)"

#: info_variables.py:76
msgid "a `set`"
msgstr "un `set`"

#: info_variables.py:77 info_variables.py:78
msgid "a string (`str`)"
msgstr "un string (`str`)"

#: info_variables.py:79
msgid "a `tuple`"
msgstr "una `tuple`"

#: info_variables.py:357
msgid "Friendly warning: you have redefined the python builtin `{name}`.\n"
msgstr ""

#: info_variables.py:531
msgid "Object too large to be processed by Python."
msgstr "Objeto demasiado grande para ser procesado por Python."

#: info_variables.py:535
msgid "Unable to compute."
msgstr ""

#: info_variables.py:592
msgid ""
"A type hint found for `{name}` in the {scope} scope.\n"
"Perhaps you had used a colon instead of an equal sign and wrote\n"
"\n"
"    {name} : {hint}\n"
"\n"
"instead of\n"
"\n"
"    {name} = {hint}\n"
msgstr ""
"Se ha encontrado un type hint para `{name}` en el ámbito {scope}.\n"
"Tal vez haya utilizado dos puntos en lugar de un signo de igualdad y haya "
"escrito\n"
"\n"
"    {name} : {hint}\n"
"\n"
"en lugar de\n"
"\n"
"    {name} = {hint}\n"

#: path_info.py:213
msgid "The default directory is {dirname}."
msgstr "El directorio por defecto es {dirname}."

#: runtime_errors\attribute_error.py:32 runtime_errors\attribute_error.py:79
#: runtime_errors\attribute_error.py:117
msgid "Did you give your program the same name as a Python module?\n"
msgstr "¿Has dado a tu programa el mismo nombre que un módulo de Python?\n"

#: runtime_errors\attribute_error.py:33 runtime_errors\attribute_error.py:80
msgid ""
"I suspect that you used the name `{module}.py` for your program\n"
"and that you also wanted to import a module with the same name\n"
"from Python's standard library.\n"
"If so, you should use a different name for your program.\n"
msgstr ""
"Sospecho que has utilizado el nombre `{module}.py` para tu programa\n"
"y que también querías importar un módulo con el mismo nombre\n"
"de la biblioteca estándar de Python.\n"
"Si es así, deberías usar un nombre diferente para tu programa.\n"

#: runtime_errors\attribute_error.py:42 runtime_errors\import_error.py:63
msgid "You have a circular import.\n"
msgstr "Tienes un import circular.\n"

#: runtime_errors\attribute_error.py:46 runtime_errors\attribute_error.py:88
msgid "You likely have a circular import.\n"
msgstr "Es probable que tengas un import circular.\n"

#: runtime_errors\attribute_error.py:47
msgid "Python indicated that the module `{module}` was not fully imported.\n"
msgstr ""
"Python indicó que el módulo `{module}` no fue importado completamente.\n"

#: runtime_errors\attribute_error.py:48 runtime_errors\attribute_error.py:89
msgid ""
"This can occur if, during the execution of the code in module `{module}`\n"
"an attempt is made to import the same module again.\n"
msgstr ""
"Esto puede ocurrir si, durante la ejecución del código del módulo `{module}"
"`\n"
"se intenta importar de nuevo el mismo módulo.\n"

#: runtime_errors\attribute_error.py:72
msgid ""
"This should not happen:\n"
"Python tells us that module `{module}` does not have an attribute named "
"`{attribute}`.\n"
"However, it does not appear that module `{module}` was imported.\n"
msgstr ""
"Esto no debería ocurrir:\n"
"Python nos dice que el módulo `{module}` no tiene un atributo llamado "
"`{attribute}`.\n"
"Sin embargo, no parece que el módulo `{module}` haya sido importado.\n"

#: runtime_errors\attribute_error.py:98 runtime_errors\attribute_error.py:106
#: runtime_errors\attribute_error.py:139 runtime_errors\attribute_error.py:405
#: runtime_errors\import_error.py:106 runtime_errors\key_error.py:184
#: runtime_errors\key_error.py:191 runtime_errors\module_not_found_error.py:121
#: runtime_errors\name_error.py:111 runtime_errors\unbound_local_error.py:54
#: syntax_errors\message_analyzer.py:459 syntax_errors\message_analyzer.py:1151
#: syntax_errors\statement_analyzer.py:1389
msgid "Did you mean `{name}`?\n"
msgstr "¿Quieres decir `{name}`?\n"

#: runtime_errors\attribute_error.py:99
msgid ""
"Perhaps you meant to write `{module}.{correct}` instead of `{module}.{typo}"
"`\n"
msgstr ""
"Quizás quisiste escribir `{module}.{correct}` en lugar de `{module}.{typo}`\n"

#: runtime_errors\attribute_error.py:107
msgid ""
"Instead of writing `{module}.{typo}`, perhaps you meant to write one of \n"
"the following names which are attributes of module `{module}`:\n"
"`{names}`\n"
msgstr ""
"En lugar de escribir `{module}.{typo}`, quizás quisiste escribir uno de los\n"
"siguientes nombres que son atributos del módulo `{module}`:\n"
"`{names}`\n"

#: runtime_errors\attribute_error.py:118
msgid ""
"You imported a module named `{module}` from `{mod_path}`.\n"
"There is also a module named `{module}` in Python's standard library.\n"
"Perhaps you need to rename your module.\n"
msgstr ""
"Importaste un modulo llamado`{module}` desde `{mod_path}`.\n"
"Pero también existe un modulo llamado `{module}` en la librería estándar de "
"Python.\n"
"Quizás debas cambiar el nombre de tu módulo.\n"

#: runtime_errors\attribute_error.py:140
msgid ""
"Perhaps you meant to use the attribute `{attribute}` of \n"
"module `{mod_name}` instead of module `{module}`.\n"
msgstr ""
"Quizás quisiste utilizar el atributo `{attribute}` del \n"
"modulo `{mod_name}` en lugar del módulo `{module}`.\n"

#: runtime_errors\attribute_error.py:146
msgid "Did you mean one of the following modules: `{names}`?"
msgstr "¿Querías utilizar uno de los módulos: `{names}`?"

#: runtime_errors\attribute_error.py:149
msgid ""
"Instead of the module `{module}`, perhaps you wanted to use\n"
"the attribute `{attribute}` of one of the following modules:\n"
"`{names}`.\n"
msgstr ""
"En lugar del modulo `{module}`, quizás querías usar el\n"
"atributo `{attribute}` de uno de los siguientes módulos:\n"
"`{names}.\n"

#: runtime_errors\attribute_error.py:158
msgid ""
"Python tells us that no object with name `{attribute}` is\n"
"found in module `{module}`.\n"
msgstr ""
"Python nos indica que no se encuentra ningún objeto con nombre `{attribute}` "
"en\n"
"el módulo  `{module}`.\n"

#: runtime_errors\attribute_error.py:179
msgid "`add_note()` is only allowed for Python version 3.11 and newer.\n"
msgstr ""

#: runtime_errors\attribute_error.py:180
#, fuzzy
#| msgid "You cannot delete a Python expression.\n"
msgid "You are using Python version {version}.\n"
msgstr "No se puede borrar una expresión de Python.\n"

#: runtime_errors\attribute_error.py:197
msgid ""
"You are attempting to access the attribute `{attr}`\n"
"for a variable whose value is `None`."
msgstr ""
"Está intentando acceder al atributo `{attr}`\n"
"de una variable cuyo valor es `None`."

#: runtime_errors\attribute_error.py:222
msgid ""
"The value of attribute `{attribute}` of objects of type `{obj_type}`\n"
"cannot be changed.\n"
"I have no further information.\n"
msgstr ""
"El valor del atributo `{attribute}` en el objeto de tipo `{obj_type}`\n"
"no puede ser cambiado.\n"
"No tengo más información.\n"

#: runtime_errors\attribute_error.py:241
msgid ""
"Object `{name}` uses an empty `__slots__` to prevent the modification\n"
"of any of its attributes.\n"
msgstr ""
"El objeto `{name}` utiliza un `__slots__` vacío para prevenir la "
"modificación\n"
"de cualquiera de sus atributos.\n"

#: runtime_errors\attribute_error.py:247
msgid ""
"Object `{name}` uses `__slots__` to specify which attributes can\n"
"be changed. The value of attribute `{name}.{attribute}` cannot be changed.\n"
msgstr ""
"El objeto `{name}` utiliza `__slots__` para indicar que atributos pueden\n"
"cambiar. Puntualmente, el valor del atributo `{name}.{attribute}` no puede "
"ser cambiado.\n"

#: runtime_errors\attribute_error.py:272
msgid ""
"`{obj_name}` is a function. Perhaps you meant to write\n"
"`{obj_name}({attribute})`\n"
msgstr ""
"`{obj_name}` es una función. Quizás quisiste escribir\n"
"`{obj_name}({attribute})`\n"

#: runtime_errors\attribute_error.py:276
msgid "Did you mean `{obj_name}({attribute})`?\n"
msgstr "¿Querías decir `{obj_name}({attribute})`?\n"

#: runtime_errors\attribute_error.py:281
msgid ""
"`{obj_name}` is a Python built-in function or method\n"
"which does not have an attribute named `{attribute}.`\n"
msgstr ""
"`{obj_name}` es una función o método integrado de Python\n"
"el cual no posee un atributo llamado `{attribute}.`\n"

#: runtime_errors\attribute_error.py:300
msgid ""
"An object of type `{obj_type}` has no attribute named `{attr}`.\n"
"Unfortunately I cannot find such an object on the line where\n"
"the problem occurs.\n"
msgstr ""
"Un objeto de tipo `{obj_type}` no tiene ningún atributo llamado `{attr}`.\n"
"Lamentablemente, no puedo encontrar un objeto de este tipo en la línea\n"
"en la que el problema fue encontrado.\n"

#: runtime_errors\attribute_error.py:328
msgid ""
"An object of type `{obj_type}` has no attribute named `{attr}`.\n"
"\n"
"I cannot give additional information:\n"
"I found one object of this type in the current scope\n"
"but it does not appear to be the object causing the problem.\n"
msgstr ""
"Un objeto de tipo `{obj_type}` no tiene ningún atributo llamado `{attr}`.\n"
"\n"
"No puedo dar información adicional:\n"
"He encontrado un objeto de este tipo en el ámbito actual\n"
"pero no parece ser el objeto que causa el problema.\n"

#: runtime_errors\attribute_error.py:337
msgid ""
"An object of type `{obj_type}` has no attribute named `{attr}`.\n"
"\n"
"The following objects might be the cause of the problem: \n"
"{names}.\n"
msgstr ""
"Un objeto de tipo `{obj_type}` no tiene ningún atributo llamado `{attr}`.\n"
"\n"
"Los siguientes objetos pueden ser la causa del problema: \n"
"{names}.\n"

#: runtime_errors\attribute_error.py:377
msgid "The object `{obj}` has no attribute named `{attr}`.\n"
msgstr "Un objeto de tipo `{obj}` no tiene ningún atributo llamado `{attr}`.\n"

#: runtime_errors\attribute_error.py:381
msgid ""
"Note that object `{obj}` uses `__slots__` which prevents\n"
"the creation of new attributes.\n"
msgstr ""
"Tenga en cuenta que el objeto `{obj}` utiliza `__slots__`\n"
"que impide la creación de nuevos atributos.\n"

#: runtime_errors\attribute_error.py:389
msgid ""
"The following are some of its known attributes:\n"
"`{names}`."
msgstr ""
"A continuación se detallan algunos de sus atributos conocidos:\n"
"`{names}`."

#: runtime_errors\attribute_error.py:401
msgid "The object `{obj_name}` has no attribute named `{attribute}`.\n"
msgstr ""
"El objeto `{obj_name}` no tiene ningún atributo llamado `{attribute}`.\n"

#: runtime_errors\attribute_error.py:406
msgid ""
"Perhaps you meant to write `{obj}.{correct}` instead of `{obj}.{typo}`\n"
msgstr "Tal vez quiso escribir `{obj}.{correct}` en lugar de `{obj}.{typo}`\n"

#: runtime_errors\attribute_error.py:412 runtime_errors\import_error.py:113
msgid "Did you mean one of the following: `{names}`?\n"
msgstr "¿Te refieres a uno de los siguientes: `{names}`?\n"

#: runtime_errors\attribute_error.py:413
msgid ""
"Instead of writing `{obj}.{typo}`, perhaps you meant to write one of \n"
"the following names which are attributes of object `{obj}`:\n"
"`{names}`\n"
msgstr ""
"En lugar de escribir `{obj}.{typo}`, tal vez quiso escribir uno de \n"
"los siguientes nombres que son atributos del objeto `{obj}`:\n"
"`{names}`\n"

#: runtime_errors\attribute_error.py:438 syntax_errors\message_analyzer.py:1817
#: syntax_errors\message_analyzer.py:1830
msgid "Did you write a comma by mistake?\n"
msgstr "¿Escribiste una coma por error?\n"

#: runtime_errors\attribute_error.py:439
msgid ""
"`{obj_name}` is a tuple that contains a single item\n"
"which does have `'{attribute}'` as an attribute.\n"
"Perhaps you added a trailing comma by mistake at the end of the line\n"
"where you defined `{obj_name}`.\n"
msgstr ""
"`{obj_name}` es una tupla que contiene un único elemento\n"
"que tiene `{attribute}` como atributo.\n"
"Tal vez haya añadido por error una coma al final de la línea\n"
"donde definiste `{obj_name}`.\n"

#: runtime_errors\attribute_error.py:452
msgid "Did you mean `{str_content}.join({obj_name})`?\n"
msgstr "¿Te refieres a `{str_content}.join({obj_name})`?\n"

#: runtime_errors\attribute_error.py:453
msgid ""
"The object `{obj_name}` has no attribute named `join`.\n"
"Perhaps you wanted something like `{str_content}.join({obj_name})`.\n"
msgstr ""
"El objeto `{obj_name}` no tiene un atributo llamado `join`.\n"
"Tal vez querías algo como `{str_content}.join({obj_name})`.\n"

#: runtime_errors\attribute_error.py:476
msgid "Did you mean `{known_builtin}({obj_name})`?\n"
msgstr "¿Te refieres a `{known_builtin}({obj_name})`?\n"

#: runtime_errors\attribute_error.py:479
msgid ""
"The object `{obj_name}` has no attribute named `{attribute}`.\n"
"Perhaps you can use the Python builtin function `{known_builtin}` instead:\n"
"`{known_builtin}({obj_name})`."
msgstr ""
"El objeto `{obj_name}` no tiene ningún atributo llamado `{attribute}`.\n"
"Tal vez pueda utilizar la función incorporada de Python `{known_builtin}` en "
"su lugar:\n"
"`{known_builtin}({obj_name})`."

#: runtime_errors\attribute_error.py:508
msgid "Did you mean `{attr}`?\n"
msgstr "¿Quieres decir `{attr}`?\n"

#: runtime_errors\attribute_error.py:509
msgid "The object `{name}` has no attribute named `{attribute}`.\n"
msgstr "El objeto `{name}` no tiene ningún atributo llamado `{attribute}`.\n"

#: runtime_errors\attribute_error.py:513
msgid "However, `{attr}` is an attribute of `{name}` with a similar meaning.\n"
msgstr ""
"Sin embargo, `{attr}` es un atributo de `{name}` con un significado "
"similar.\n"

#: runtime_errors\attribute_error.py:517
msgid ""
"However, `{name}` has the following attributes with similar meanings:\n"
"`{attributes}`.\n"
msgstr ""
"Sin embargo, `{name}` tiene los siguientes atributos con significados "
"similares:\n"
"`{attributes}`.\n"

#: runtime_errors\attribute_error.py:526
msgid "Did you mean to separate object names by a comma?\n"
msgstr "¿Te refieres a separar los nombres de los objetos con una coma?\n"

#: runtime_errors\attribute_error.py:528
msgid ""
"`{second}` is not an attribute of `{first}`.\n"
"However, both `{first}` and `{second}` are known objects.\n"
"Perhaps you wrote a period to separate these two objects, \n"
"instead of using a comma.\n"
msgstr ""
"`{second}` no es un atributo de `{first}`.\n"
"Sin embargo, tanto `{first}` como `{second}` son objetos conocidos.\n"
"Tal vez utilizaste un punto para separar estos dos objetos \n"
"en lugar de usar una coma.\n"

#: runtime_errors\file_not_found_error.py:25
#: runtime_errors\file_not_found_error.py:36
msgid ""
"In your program, the name of the\n"
"file that cannot be found is `{filename}`.\n"
msgstr ""
"En su programa, el nombre del archivo\n"
"que no se puede encontrar es `{filename}`.\n"

#: runtime_errors\file_not_found_error.py:32
msgid ""
"{directory}\n"
"is not a valid directory.\n"
msgstr ""
"{directory}\n"
"no es un directorio valido.\n"

#: runtime_errors\file_not_found_error.py:41
msgid ""
"It was expected to be found in the\n"
"`{directory}` directory.\n"
msgstr ""
"Se esperaba encontrarlo en el directorio\n"
"directorio `{directory}`.\n"

#: runtime_errors\file_not_found_error.py:45
msgid "Did you mean `{similar}`?\n"
msgstr "¿Quieres decir `{similar}`?\n"

#: runtime_errors\file_not_found_error.py:47
msgid "The file `{similar}` has a similar name.\n"
msgstr "El archivo `{similar}` tiene un nombre similar.\n"

#: runtime_errors\file_not_found_error.py:52
msgid "Perhaps you meant one of the following files with similar names:\n"
msgstr ""
"Tal vez se refiera a uno de los siguientes archivos con nombres similares:\n"

#: runtime_errors\file_not_found_error.py:59 runtime_errors\name_error.py:131
msgid "I have no additional information for you.\n"
msgstr "No tengo información adicional para usted.\n"

#: runtime_errors\import_error.py:66
msgid ""
"The object that could not be imported is `{name}`.\n"
"The module or package where it was \n"
"expected to be found is `{module}`.\n"
msgstr ""
"El objeto que no se ha podido importar es `{name}`.\n"
"El módulo o paquete donde se esperaba encontrar \n"
"se esperaba encontrar es `{module}`.\n"

#: runtime_errors\import_error.py:83
msgid ""
"Python indicated that you have a circular import.\n"
"This can occur if executing the code in module 'A'\n"
"results in executing the code in module 'B' where\n"
"an attempt to import a name from module 'A' is made\n"
"before the execution of the code in module 'A' had been completed.\n"
msgstr ""
"Python ha indicado que tienes una importación circular.\n"
"Esto puede ocurrir si al ejecutar el código en el módulo 'A'\n"
"resulta en la ejecución del código en el módulo 'B' donde\n"
"un intento de importar un nombre del módulo 'A' se hace\n"
"antes de que la ejecución del código en el módulo 'A' haya finalizado.\n"

#: runtime_errors\import_error.py:95
msgid ""
"Inconsistent state: `'{module}'` was apparently not imported.\n"
"As a result, no further analysis can be done.\n"
msgstr ""
"Estado inconsistente: `'{module}'` aparentemente no fue importado.\n"
"Como resultado, no se puede realizar ningún otro análisis.\n"

#: runtime_errors\import_error.py:107
msgid ""
"Perhaps you meant to import `{correct}` (from `{module}`) instead of `{typo}"
"`\n"
msgstr ""
"Tal vez quiso importar `{correct}` (de `{module}`) en lugar de `{typo}`\n"

#: runtime_errors\import_error.py:116
msgid ""
"Instead of trying to import `{typo}` from `{module}`, \n"
"perhaps you meant to import one of \n"
"the following names which are found in module `{module}`:\n"
"`{candidates}`\n"
msgstr ""
"En lugar de intentar importar `{typo}` de `{module}`, \n"
"tal vez lo que querías era importar uno de \n"
"los siguientes nombres que se encuentran en el módulo `{module}`:\n"
"`{candidates}`\n"

#: runtime_errors\import_error.py:134
msgid "The object that could not be imported is `{name}`.\n"
msgstr "El objeto que no se ha podido importar es `{name}`.\n"

#: runtime_errors\import_error.py:186
msgid ""
"The problem was likely caused by what is known as a 'circular import'.\n"
"First, Python imported and started executing the code in file\n"
"   '{file}'.\n"
"which imports module `{last_module}`.\n"
"During this process, the code in another file,\n"
"   '{last_file}'\n"
"was executed. However in this last file, an attempt was made\n"
"to import the original module `{last_module}`\n"
"a second time, before Python had completed the first import.\n"
msgstr ""
"El problema fue probablemente causado por lo que se conoce como una "
"'importación circular'.\n"
"Primero, Python importó y comenzó a ejecutar el código en el archivo\n"
"   '{file}'.\n"
"que importa al módulo `{last_module}`.\n"
"Durante este proceso, el código en el otro archivo\n"
"   '{last_file}'\n"
"fue ejecutado. Sin embargo, en este último archivo, se intentó\n"
"de importar el módulo original `{last_module}`\n"
"por segunda vez, antes de que Python hubiera completado la primera "
"importación.\n"

#: runtime_errors\index_error.py:36
msgid ""
"You have tried to assign a value to an item of an object\n"
"of type `{obj_type}` which I cannot identify.\n"
"The index you gave was not an allowed value.\n"
msgstr ""
"Ha intentado asignar un valor a un elemento de un objeto\n"
"de tipo `{obj_type}` que no puedo identificar.\n"
"El índice que has dado no es un valor permitido.\n"

#: runtime_errors\index_error.py:46
msgid ""
"You have tried to assign a value to index `{index}` of `{name}`,\n"
"{obj_type} of length `{length}`.\n"
msgstr ""
"Ha intentado asignar un valor al índice `{index}` de `{name}`,\n"
"{obj_type} de longitud `{length}`.\n"

#: runtime_errors\index_error.py:57 runtime_errors\index_error.py:145
msgid ""
"The valid index values of `{name}` are integers ranging from\n"
"`{min}` to `{max}`.\n"
msgstr ""
"Los valores de índice válidos de `{name}` son números enteros que van desde\n"
"`{min}` a `{max}`.\n"

#: runtime_errors\index_error.py:62 runtime_errors\index_error.py:150
msgid ""
"Remember: the first item of {obj_type} is not at index 1 but at index 0.\n"
msgstr ""
"Recuerda: el primer elemento de {obj_type} no está en la posición 1 sino en "
"la número 0.\n"

#: runtime_errors\index_error.py:67 runtime_errors\index_error.py:155
msgid "`{name}` contains no item.\n"
msgstr "{name}`no contiene items.\n"

#: runtime_errors\index_error.py:68
msgid ""
"You have tried to assign a value to index `{index}` of `{name}`,\n"
"{obj_type} which contains no item.\n"
msgstr ""
"Ha intentado asignar un valor al índice `{index}` de `{name}`,\n"
"{obj_type} que no contiene ningún elemento.\n"

#: runtime_errors\index_error.py:80
msgid ""
"You have tried to get an item of an object\n"
"of type `{obj_type}` which I cannot identify.\n"
"The index you gave was not an allowed value.\n"
msgstr ""
"Ha intentado obtener un elemento de un objeto\n"
"de tipo `{obj_type}` que no puedo identificar.\n"
"El índice que has dado no es un valor permitido.\n"

#: runtime_errors\index_error.py:125
msgid ""
"You have tried to get an item from `{name}`,\n"
"{obj_type} of length `{length}`, by using a value for the index\n"
"that I cannot determine but which is not allowed.\n"
msgstr ""
"Ha intentado obtener un elemento de `{name}`,\n"
"{obj_type} de longitud `{length}`, utilizando un valor para el índice\n"
"que no puedo determinar pero que no está permitido.\n"

#: runtime_errors\index_error.py:134
msgid ""
"You have tried to get the item with index `{index}` of `{name}`,\n"
"{obj_type} of length `{length}`.\n"
msgstr ""
"Ha intentado obtener el elemento con índice `{index}` de `{name}`,\n"
"{obj_type} de longitud `{length}`.\n"

#: runtime_errors\index_error.py:156
msgid ""
"You have tried to get the item with index `{index}` of `{name}`,\n"
"{obj_type} which contains no item.\n"
msgstr ""
"Ha intentado obtener el elemento con índice `{index}` de `{name}`,\n"
"{obj_type} que no contiene ningún elemento.\n"

#: runtime_errors\key_error.py:23
msgid ""
"You tried to retrieve an item from an empty `dict`\n"
"or a similar object which I cannot identify.\n"
msgstr ""
"Has intentado recuperar un elemento de un `dict` vacío\n"
"o un objeto similar que no he podido identificar.\n"

#: runtime_errors\key_error.py:29
msgid "`{name}` is an empty `dict`.\n"
msgstr "`{name}` es un `dict` vacío.\n"

#: runtime_errors\key_error.py:30
msgid "You tried to retrieve an item from `{name}` which is an empty `dict`.\n"
msgstr ""
"Has intentado recuperar un elemento de {name}` que es un `dict` vacío.\n"

#: runtime_errors\key_error.py:49
msgid ""
"You tried to retrieve an item from an empty ChainMap\n"
"or similar object which I cannot identify.\n"
msgstr ""
"Ha intentado recuperar un elemento de un ChainMap vacío\n"
"o un objeto similar que no puedo identificar.\n"

#: runtime_errors\key_error.py:55
msgid "`{name}` is an empty `ChainMap`.\n"
msgstr "`{name}` es un `ChainMap` vacío.\n"

#: runtime_errors\key_error.py:56
msgid ""
"You tried to retrieve an item from `{name}` which is an empty `ChainMap`.\n"
msgstr ""
"Has intentado recuperar un elemento de `{name}` que es un `ChainMap` vacío.\n"

#: runtime_errors\key_error.py:97
msgid "Missing key `{key}` in a `ChainMap` or in a similar object.\n"
msgstr "Falta la clave `{key}` en un `ChainMap` o en un objeto similar.\n"

#: runtime_errors\key_error.py:137
msgid ""
"A `dict` or a similar object which I cannot identify\n"
"does not have `{key}` as a key.\n"
msgstr ""
"Un `dict` o un objeto similar que no puedo identificar\n"
"no tiene `{key}` como clave.\n"

#: runtime_errors\key_error.py:144
msgid "The key `{key}` cannot be found in the dict `{name}`.\n"
msgstr "La clave `{key}` no se encuentra en el dict `{name}`.\n"

#: runtime_errors\key_error.py:149
msgid ""
"The key `{key}` cannot be found in `{name}`, an object of type `{obj_type}"
"`.\n"
msgstr ""
"La clave `{key}` no se encuentra en `{name}`, un objeto de tipo `{obj_type}"
"`.\n"

#: runtime_errors\key_error.py:159
msgid ""
"`{name}` contains a string key which is identical to `str({key})`.\n"
"Perhaps you forgot to convert the key into a string.\n"
msgstr ""
"`{name}` contiene una clave de cadena que es idéntica a `str({key})`.\n"
"Tal vez te olvidaste de convertir la clave en una cadena.\n"

#: runtime_errors\key_error.py:163
msgid "Did you forget to convert `{key}` into a string?\n"
msgstr "¿Olvidaste convertir `{key}` en una cadena?\n"

#: runtime_errors\key_error.py:172
msgid ""
"`{key}` is a string.\n"
"There is a key of `{name}` whose string representation\n"
"is identical to `{key}`.\n"
msgstr ""
"`{key}` es una cadena.\n"
"Existe una clave de `{name}` cuya representación en cadena\n"
"es idéntica a `{key}`.\n"

#: runtime_errors\key_error.py:177
msgid "Did you convert `{key}` into a string by mistake?\n"
msgstr "¿Has convertido `{key}` en una cadena por error?\n"

#: runtime_errors\key_error.py:185
msgid "`{name}` is a key of `{dict_}` which is similar to `{key}`.\n"
msgstr "`{name}` es una clave de `{dict_}` que es similar a `{key}`.\n"

#: runtime_errors\key_error.py:193
msgid ""
"`{name}` has some keys similar to `{key}` including:\n"
"`{names}`.\n"
msgstr ""
"`{name}` tiene algunas claves similares a `{key}` incluyendo:\n"
"`{names}`.\n"

#: runtime_errors\module_not_found_error.py:35
msgid ""
"No additional information available since `{name}` cannot be imported.\n"
msgstr ""
"No hay información adicional disponible ya que `{name}` no se puede "
"importar.\n"

#: runtime_errors\module_not_found_error.py:46
msgid "Did you mean `from {name} import {rest}`?\n"
msgstr "¿Quieres decir `from {name} import {rest}`?\n"

#: runtime_errors\module_not_found_error.py:49
msgid ""
"`{rest}` is not a separate module but an object that is part of `{name}`.\n"
msgstr ""
"`{rest}` no es un módulo independiente, sino un objeto que forma parte de "
"`{name}`.\n"

#: runtime_errors\module_not_found_error.py:59
msgid "Did you mean `import {name}.{attr}`?\n"
msgstr "¿Quieres decir `import {name}.{attr}`?\n"

#: runtime_errors\module_not_found_error.py:62
msgid ""
"Perhaps you meant `import {name}.{attr}`.\n"
"`{attr}` is a name similar to `{rest}` and is a module that\n"
"can be imported from `{name}`.\n"
msgstr ""
"Tal vez se refiera a `importar {name}.{attr}`.\n"
"`{attr}` es un nombre similar a `{rest}` y es un módulo que\n"
"puede ser importado desde `{name}`.\n"

#: runtime_errors\module_not_found_error.py:70
msgid "Did you mean `from {name} import {attr}`?\n"
msgstr "¿Quieres decir `from {name} import {attr}`?\n"

#: runtime_errors\module_not_found_error.py:73
msgid ""
"Perhaps you meant `from {name} import {attr}`.\n"
"`{attr}` is a name similar to `{rest}` and is an object that\n"
"can be imported from `{name}`.\n"
msgstr ""
"Tal vez quieras decir `from {name} import {attr}`.\n"
"`{attr}` es un nombre similar a `{rest}` y es un objeto que\n"
"puede ser importado desde `{name}`.\n"

#: runtime_errors\module_not_found_error.py:80
msgid ""
"Other objects with similar names that are part of\n"
" `{name}` include `{others}`.\n"
msgstr ""
"Otros objetos con nombres similares que forman parte de\n"
"`{name}` incluyen a `{others}`.\n"

#: runtime_errors\module_not_found_error.py:86
msgid "`{rest}` cannot be imported from `{name}`.\n"
msgstr "`{rest}` no puede ser importado desde `{name}`.\n"

#: runtime_errors\module_not_found_error.py:95
msgid "The curses module is rarely installed with Python on Windows.\n"
msgstr "El módulo curses rara vez se instala con Python en Windows.\n"

#: runtime_errors\module_not_found_error.py:97
msgid "The curses module is often not installed with Python.\n"
msgstr "El módulo curses no suele instalarse con Python.\n"

#: runtime_errors\module_not_found_error.py:98
msgid "You have tried to import the curses module.\n"
msgstr "Ha intentado importar el módulo curses.\n"

#: runtime_errors\module_not_found_error.py:114
msgid ""
"No module named `{name}` can be imported.\n"
"Perhaps you need to install it.\n"
msgstr ""
"No se puede importar el módulo llamado `{name}`.\n"
"Tal vez sea necesario instalarlo.\n"

#: runtime_errors\module_not_found_error.py:123
msgid ""
"The following existing modules have names that are similar \n"
"to the module you tried to import: `{names}`\n"
msgstr ""
"Los siguientes módulos existentes tienen nombres similares \n"
"al módulo que ha intentado importar: `{names}`\n"

#: runtime_errors\module_not_found_error.py:128
msgid "`{name}` is an existing module that has a similar name.\n"
msgstr "`{name}` es un módulo existente que tiene un nombre similar.\n"

#: runtime_errors\name_error.py:19
msgid "You are already using Python!"
msgstr "¡Ya estás usando Python!"

#: runtime_errors\name_error.py:34
msgid ""
"`{name}` is a name found in module `{mod}`.\n"
"Perhaps you forgot to write\n"
"\n"
"    from {mod} import {name}\n"
msgstr ""
"`{name}` es un nombre que se encuentra en el módulo `{mod}`.\n"
"Tal vez haya olvidado escribir\n"
"\n"
"    from {mod} import {name}\n"

#: runtime_errors\name_error.py:38
#, fuzzy
#| msgid ""
#| "`{name}` is a name found in the following modules from the standard "
#| "library:\n"
#| "{modules}.\n"
#| "Perhaps you forgot to import `{name}` from one of these modules.\n"
msgid ""
"`{name}` is a name found in the following modules:\n"
"{modules}.\n"
"Perhaps you forgot to import `{name}` from one of these modules.\n"
msgstr ""
"`{name}` es un nombre que se encuentra en los siguientes módulos de la "
"biblioteca estándar:\n"
"{modules}.\n"
"Tal vez hayas olvidado importar `{name}` de uno de estos módulos.\n"

#: runtime_errors\name_error.py:61
msgid ""
"In your program, `{var_name}` is an unknown name\n"
"that exists in an enclosing scope,\n"
"but has not yet been assigned a value.\n"
msgstr ""
"En tu programa, `{var_name}` es un nombre desconocido\n"
"que existe en un ámbito de aplicación\n"
"pero aún no se le ha asignado un valor.\n"

#: runtime_errors\name_error.py:88 runtime_errors\name_error.py:147
msgid "In your program, no object with the name `{var_name}` exists.\n"
msgstr "En su programa, no existe ningún objeto con el nombre `{var_name}`.\n"

#: runtime_errors\name_error.py:107
#, fuzzy
#| msgid "Did you mean `{name}`?\n"
msgid " Or did you mean `{name}`?\n"
msgstr "¿Quieres decir `{name}`?\n"

#: runtime_errors\name_error.py:113
msgid "Did you use a colon instead of an equal sign?\n"
msgstr "¿Ha utilizado dos puntos en lugar del signo de igualdad?\n"

#: runtime_errors\name_error.py:146
msgid "Did you mean `1j`?\n"
msgstr "¿Quieres decir `1j`?\n"

#: runtime_errors\name_error.py:150
msgid ""
"However, sometimes `{name}` is intended to represent\n"
"the square root of `-1` which is written as `1j` in Python.\n"
msgstr ""
"Sin embargo, a veces `{name}` pretende representar\n"
"la raíz cuadrada de `-1` que se escribe como `1j` en Python.\n"

#: runtime_errors\name_error.py:180
msgid "Did you mean `{word}`?\n"
msgstr "¿Quieres decir `{word}`?\n"

#: runtime_errors\name_error.py:181
msgid "I suspect you meant to write the keyword `{word}` and made a typo.\n"
msgstr ""
"Sin embargo, sospecho que has escrito la palabra clave `{word}` por error.\n"

#: runtime_errors\name_error.py:189
msgid "`__debug__` is a constant.\n"
msgstr "`__debug__` es una constante.\n"

#: runtime_errors\name_error.py:190
msgid ""
"`__debug__` is a constant that cannot be deleted.\n"
"In future Python versions, attempting to delete it will be a SyntaxError.\n"
msgstr ""
"`__debug__` es una constante que no puede ser borrada.\n"
"En futuras versiones de Python, los intentos de borrarla elevaran un "
"`SyntaxError`.\n"

#: runtime_errors\name_error.py:198
msgid "You must be a fan of PyConAu!\n"
msgstr "¡Debes ser un fan de la PyConAu!\n"

#: runtime_errors\name_error.py:199
msgid ""
"I am guessing that you tried to use (one of) the flipfloperators\n"
"shown during the second Lightning Talk session of PyConAu 2018,\n"
"but that you forgot to install the module from PyPI.\n"
"\n"
"#### Note that it is still a bad idea.\n"
msgstr ""
"Supongo que has intentado utilizar (uno de) los flipfloperators\n"
"mostrado durante la segunda sesión de Lightning Talk de PyConAu 2018,\n"
"pero que olvidaste instalar el módulo desde PyPI.\n"
"\n"
"#### Ten en cuenta que sigue siendo una mala idea.\n"

#: runtime_errors\name_error.py:214 runtime_errors\name_error.py:238
msgid "Did you forget to import `{name}`?\n"
msgstr "¿Olvidaste importar `{name}`?\n"

#: runtime_errors\name_error.py:217
msgid ""
"The name `{name}` is not defined in your program.\n"
"Perhaps you forgot to import `{lowercase}` which is found\n"
"in Python's standard library.\n"
msgstr ""
"El nombre `{name}` no está definido en su programa.\n"
"Tal vez se olvidó de importar `{lowercase}` que se encuentra\n"
"en la biblioteca estándar de Python.\n"

#: runtime_errors\name_error.py:226
msgid "Note that the name of the module is `{lowercase}` and not `{name}`.\n"
msgstr ""
"Tenga en cuenta que el nombre del módulo es `{lowercase}` y no `{name}`.\n"

#: runtime_errors\name_error.py:241
#, fuzzy
#| msgid ""
#| "The name `{name}` is not defined in your program.\n"
#| "Perhaps you forgot to import `{lowercase}` which is found\n"
#| "in Python's standard library.\n"
msgid ""
"The name `{name}` is not defined in your program.\n"
"Perhaps you forgot to import `{name}` which is a known library.\n"
msgstr ""
"El nombre `{name}` no está definido en su programa.\n"
"Tal vez se olvidó de importar `{lowercase}` que se encuentra\n"
"en la biblioteca estándar de Python.\n"

#: runtime_errors\name_error.py:251
#, fuzzy
#| msgid "Did you forget to import `{name}`?\n"
msgid "Did you forget to import `{true_name}`?\n"
msgstr "¿Olvidaste importar `{name}`?\n"

#: runtime_errors\name_error.py:256
#, fuzzy
#| msgid ""
#| "The name `{name}` is not defined in your program.\n"
#| "Perhaps you forgot to import `{lowercase}` which is found\n"
#| "in Python's standard library.\n"
msgid ""
"The name `{name}` is not defined in your program.\n"
"Perhaps you forgot to write\n"
"\n"
"   import {true_name} as {name}\n"
msgstr ""
"El nombre `{name}` no está definido en su programa.\n"
"Tal vez se olvidó de importar `{lowercase}` que se encuentra\n"
"en la biblioteca estándar de Python.\n"

#: runtime_errors\name_error.py:275
msgid "The similar name `{name}` was found in the local scope.\n"
msgstr "Se ha encontrado el nombre similar `{name}` en el ámbito local.\n"

#: runtime_errors\name_error.py:276
msgid "The similar name `{name}` was found in the global scope.\n"
msgstr "Se ha encontrado el nombre similar `{name}` en el ámbito global.\n"

#: runtime_errors\name_error.py:277
msgid "The Python builtin `{name}` has a similar name.\n"
msgstr "El builtin de Python `{name}` tiene un nombre similar.\n"

#: runtime_errors\name_error.py:286 runtime_errors\unbound_local_error.py:124
msgid "Instead of writing `{name}`, perhaps you meant one of the following:\n"
msgstr ""
"En lugar de escribir `{name}`, tal vez quiso decir uno de los siguientes:\n"

#: runtime_errors\name_error.py:291 runtime_errors\unbound_local_error.py:128
msgid "*   Local scope: "
msgstr "*   alcance local: "

#: runtime_errors\name_error.py:292
msgid "*   Global scope: "
msgstr "*   alcance global: "

#: runtime_errors\name_error.py:293
msgid "*   Python builtins: "
msgstr "*   integrados de Python: "

#: runtime_errors\name_error.py:357
msgid "Did you write `self` at the wrong place?\n"
msgstr "¿Escribiste `self` en el lugar equivocado?\n"

#: runtime_errors\name_error.py:358
msgid ""
"The {scope} object `{obj}`\n"
"has an attribute named `{unknown_name}`.\n"
"Perhaps you should have written `self.{unknown_name}(...`\n"
"instead of `{unknown_name}(self, ...`.\n"
msgstr ""
"El objeto {scope} `{obj}`\n"
"tiene un atributo llamado `{unknown_name}`.\n"
"Quizás deberías haber escrito `self.{unknown_name}(...`\n"
"en lugar de `{unknown_name}(self, ...`.\n"

#: runtime_errors\name_error.py:365
msgid "Did you forget to add `self.`?\n"
msgstr "¿Has olvidado añadir `self.`?\n"

#: runtime_errors\name_error.py:366
msgid ""
"A {scope} object, `{obj}`,\n"
"has an attribute named `{unknown_name}`.\n"
"Perhaps you should have written `self.{unknown_name}`\n"
"instead of `{unknown_name}`.\n"
msgstr ""
"Un objeto de {scope}, `{obj}`,\n"
"tiene un atributo llamado `{unknown_name}`.\n"
"Tal vez deberías haber escrito `self.{unknown_name}`\n"
"en lugar de `{unknown_name}`.\n"

#: runtime_errors\name_error.py:373
msgid "Did you forget to add `{name}.`?\n"
msgstr "¿Has olvidado añadir `{name}.`?\n"

#: runtime_errors\name_error.py:374
msgid ""
"The {scope} object `{name}`\n"
"has an attribute named `{unknown_name}`.\n"
"Perhaps you should have written `{name}.{unknown_name}`\n"
"instead of `{unknown_name}`.\n"
msgstr ""
"El objeto {scope} `{name}`\n"
"tiene un atributo llamado `{unknown_name}`.\n"
"Quizás deberías haber escrito `{name}.{unknown_name}`\n"
"en lugar de `{unknown_name}`.\n"

#: runtime_errors\os_error.py:19
msgid ""
"I suspect that you are trying to connect to a server and\n"
"that a connection cannot be made.\n"
"\n"
"If that is the case, check for typos in the URL\n"
"and check your internet connectivity.\n"
msgstr ""
"Sospecho que está intentando conectarse a un servidor y\n"
"que no se puede realizar la conexión.\n"
"\n"
"Si ese es el caso, verifique que la URL sea correcta\n"
"y compruebe su conectividad a Internet.\n"

#: runtime_errors\os_error.py:37 syntax_errors\message_analyzer.py:1902
msgid "Perhaps you need to double the backslash characters.\n"
msgstr "Tal vez sea necesario duplicar las barras invertidas.\n"

#: runtime_errors\os_error.py:38
msgid ""
"I suspect that you wrote a filename or path that contains\n"
"at least one backslash character, `\\`.\n"
"Python likely interpreted this as indicating the beginning of\n"
"what is known as an escape sequence.\n"
"To solve the problem, either write a so-called 'raw string'\n"
"by adding the letter `r` as a prefix in\n"
"front of the filename or path, or replace all single backslash\n"
"characters, `\\`, by double ones: `\\\\`.\n"
msgstr ""
"Sospecho que ha escrito un nombre de archivo o ruta que contiene\n"
"por lo menos un carácter de barra invertida, `\\`.\n"
"Python probablemente interpretó esto como el comienzo de\n"
"lo que se conoce como una secuencia de escape.\n"
"Para resolver el problema, escriba la llamada 'cadena cruda'\n"
"añadiendo la letra `r` como prefijo delante\n"
"delante del nombre del archivo o de la ruta, o reemplazar todas las barras "
"invertidas\n"
"simples, \"barra invertida\", por otras dobles: `\\\\`.\n"

#: runtime_errors\runtime_error.py:48
msgid ""
"While you were iterating over the items of `{name}` ({container_type})\n"
"in a `{for_while}` loop, you either tried to add or remove items from it.\n"
"Suggestion: start by making a copy of `{name}` and iterate over the items\n"
"of that copy if you want to change `{name}` inside a loop.\n"
"You might want to do this as follows:\n"
"\n"
"    my_{name} = {name}.copy()\n"
"    for item in my_{name}:\n"
"        # Change {name}\n"
msgstr ""

#: runtime_errors\runtime_error.py:59
msgid ""
"While you were iterating over the items of a container ({container_type})\n"
"in a `{for_while}` loop, you either tried to add or remove items from it.\n"
"Suggestion: start by making a copy of the container and iterate over the "
"items\n"
"of that copy if you want to change that container inside a loop.\n"
msgstr ""

#: runtime_errors\type_error.py:54
msgid "Did you forget to convert the string `{name}` into {number_type}?\n"
msgstr "¿Has olvidado convertir el string `{name}` al tipo {number_type}?\n"

#: runtime_errors\type_error.py:59
msgid "Perhaps you forgot to convert the string `{name}` into {number_type}.\n"
msgstr "Tal vez haya olvidado convertir la cadena `{name}` en {number_type}.\n"

#: runtime_errors\type_error.py:71
msgid "You cannot use complex numbers with the modulo operator `%`.\n"
msgstr ""

#: runtime_errors\type_error.py:88 runtime_errors\type_error.py:102
msgid ""
"The arguments of `divmod` must be integers (`int`) or real (`float`) "
"numbers.\n"
msgstr ""

#: runtime_errors\type_error.py:93 runtime_errors\type_error.py:106
msgid "At least one of the arguments was a complex number.\n"
msgstr ""

#: runtime_errors\type_error.py:123
msgid "The second argument of the function `getattr()` must be a string.\n"
msgstr "El segundo argumento de la función `getattr()` debe ser una cadena.\n"

#: runtime_errors\type_error.py:128
msgid "The second argument of the function `hasattr()` must be a string.\n"
msgstr "El segundo argumento de la función `hasattr()` debe ser una cadena.\n"

#: runtime_errors\type_error.py:131
msgid "Some attribute of a function you called is expected to be a string.\n"
msgstr ""

#: runtime_errors\type_error.py:152 runtime_errors\type_error.py:175
msgid ""
"You tried to concatenate (add) two different types of objects:\n"
"{first} and {second}.\n"
msgstr ""
"Has intentado concatenar (sumar) dos tipos de objetos diferentes:\n"
"`{first}` y `{second}`.\n"

#: runtime_errors\type_error.py:205
msgid ""
"You tried to add two incompatible types of objects:\n"
"{first} and {second}.\n"
msgstr ""
"Has intentado añadir dos tipos de objetos incompatibles:\n"
"`{first}` y `{second}`.\n"

#: runtime_errors\type_error.py:213
msgid ""
"You tried to subtract two incompatible types of objects:\n"
"{first} and {second}.\n"
msgstr ""
"Has intentado restar dos tipos de objetos incompatibles:\n"
"`{first}` y `{second}`.\n"

#: runtime_errors\type_error.py:221
msgid ""
"You tried to multiply two incompatible types of objects:\n"
"{first} and {second}.\n"
msgstr ""
"Has intentado multiplicar dos tipos de objetos incompatibles:\n"
"`{first}` y `{second}`.\n"

#: runtime_errors\type_error.py:229
msgid ""
"You tried to divide two incompatible types of objects:\n"
"{first} and {second}.\n"
msgstr ""
"Has intentado dividir dos tipos de objetos incompatibles:\n"
"`{first}` y `{second}`.\n"

#: runtime_errors\type_error.py:237
msgid ""
"You tried to perform the bitwise operation {operator}\n"
"on two incompatible types of objects:\n"
"{first} and {second}.\n"
msgstr ""
"Has intentado realizar la operación de bits {operator}\n"
"sobre dos tipos de objetos incompatibles:\n"
"`{first}` y `{second}`.\n"

#: runtime_errors\type_error.py:252 runtime_errors\type_error.py:854
#: runtime_errors\type_error.py:962 syntax_errors\statement_analyzer.py:1259
#: syntax_errors\statement_analyzer.py:1535
msgid "Did you mean `{line}`?\n"
msgstr "¿Quieres decir `{line}`?\n"

#: runtime_errors\type_error.py:253
msgid "Outside of Python, `^` is often used to indicate exponentiation.\n"
msgstr ""
"Fuera de Python, `^` se utiliza a menudo para indicar la exponenciación.\n"

#: runtime_errors\type_error.py:256 runtime_errors\type_error.py:857
msgid "Perhaps you meant `{line}`.\n"
msgstr "Tal vez quiso decir `{line}`.\n"

#: runtime_errors\type_error.py:259
msgid ""
"You tried to perform the bit shifting operation {operator}\n"
"on two incompatible types of objects:\n"
"{first} and {second}.\n"
msgstr ""
"Has intentado realizar la operación de desplazamiento de bits {operator}\n"
"sobre dos tipos de objetos incompatibles:\n"
"`{first}` y `{second}`.\n"

#: runtime_errors\type_error.py:269
msgid ""
"You tried to exponentiate (raise to a power)\n"
"using two incompatible types of objects:\n"
"{first} and {second}.\n"
msgstr ""
"Has intentado exponer (elevar a una potencia)\n"
"usando dos tipos de objetos incompatibles:\n"
"`{first}` y `{second}`.\n"

#: runtime_errors\type_error.py:278
msgid ""
"You tried to use the operator {operator}\n"
"using two incompatible types of objects:\n"
"{first} and {second}.\n"
"This operator is normally used only\n"
"for multiplication of matrices.\n"
msgstr ""
"Has intentado utilizar el operador {operator}\n"
"utilizando dos tipos de objetos incompatibles:\n"
"`{first}` y `{second}`.\n"
"Este operador se emplea normalmente sólo\n"
"para la multiplicación de matrices.\n"

#: runtime_errors\type_error.py:313
msgid "Complex numbers cannot be ordered.\n"
msgstr "Los números complejos no se pueden ordenar.\n"

#: runtime_errors\type_error.py:314
msgid ""
"You tried to do an order comparison ({operator})\n"
"between two complex numbers.\n"
msgstr ""
"Has intentado hacer una comparación de orden ({operator})\n"
"entre dos números complejos.\n"

#: runtime_errors\type_error.py:320
msgid ""
"You tried to do an order comparison ({operator})\n"
"between two incompatible types of objects:\n"
"{first} and {second}.\n"
msgstr ""
"Has intentado hacer una comparación de orden ({operator})\n"
"entre dos tipos de objetos incompatibles:\n"
"`{first}` y `{second}`.\n"

#: runtime_errors\type_error.py:348
msgid ""
"`{iter}` is an iterator. You likely needed to write something like\n"
"\n"
"    next({iter}())\n"
"\n"
"or use it in a `for` loop to get a number from it\n"
"before comparing it to {number}.\n"
msgstr ""

#: runtime_errors\type_error.py:380
msgid "Perhaps you meant to write `{operator}=` instead of `={operator}`"
msgstr "Tal vez quiso escribir `{operator}=` en lugar de `={operator}`"

#: runtime_errors\type_error.py:384
msgid ""
"You tried to use the unary operator '{operator}'\n"
"with the following type of object: {obj}.\n"
"This operation is not defined for this type of object.\n"
msgstr ""
"Has intentado utilizar el operador unario '{operator}'\n"
"con el siguiente tipo de objeto {obj}.\n"
"La operación no está definida para este tipo de objeto.\n"

#: runtime_errors\type_error.py:410
msgid ""
"In Python, some objects are known as immutable:\n"
"once defined, their value cannot be changed.\n"
"You tried change part of such an immutable object: {obj},\n"
"most likely by using an indexing operation.\n"
msgstr ""
"En Python, algunos objetos se conocen como inmutables:\n"
"una vez definidos, su valor no puede ser cambiado.\n"
"Has intentado cambiar parte de un objeto inmutable de este tipo: {obj},\n"
"probablemente utilizando una operación de indexación.\n"

#: runtime_errors\type_error.py:417
msgid "Did you mean to use a list?\n"
msgstr "¿Querías usar una lista?\n"

#: runtime_errors\type_error.py:418
msgid "Perhaps you meant to use a list instead.\n"
msgstr "Tal vez quisiste usar una lista en su lugar.\n"

#: runtime_errors\type_error.py:431
msgid ""
"Exceptions must be derived from `BaseException`.\n"
"It is recommended that user-defined exceptions derive from\n"
"`Exception`, a subclass of `BaseException`.\n"
msgstr ""

#: runtime_errors\type_error.py:457
#, fuzzy
#| msgid "In Python 3, exceptions must be derived from BaseException.\n"
msgid ""
"In an `except` statement, you must only have classes that derive from "
"`BaseException`.\n"
msgstr "En Python 3, las excepciones deben derivarse de `BaseException`.\n"

#: runtime_errors\type_error.py:461
#, fuzzy
#| msgid "The following characters are not allowed: `{invalid}`.\n"
msgid "The following is not a valid classes: `{not_exception}`.\n"
msgstr "Los siguientes caracteres no están permitidos: `{invalid}`.\n"

#: runtime_errors\type_error.py:465
#, fuzzy
#| msgid "The following characters are not allowed: `{invalid}`.\n"
msgid "The following are not valid classes: `{not_exception}`.\n"
msgstr "Los siguientes caracteres no están permitidos: `{invalid}`.\n"

#: runtime_errors\type_error.py:502
msgid ""
"You apparently have called the function `{fn_name}` with\n"
"{nb_given} positional argument(s) while it requires {nb_required}\n"
"such positional argument(s).\n"
msgstr ""
"Al parecer, ha llamado a la función `{fn_name}` con\n"
"{nb_given} argumento(s) posicional(es) mientras que requiere {nb_required}\n"
"dicho(s) argumento(s) posicional(es).\n"

#: runtime_errors\type_error.py:508
msgid "Perhaps you forgot `self` when defining `{fn_name}`.\n"
msgstr "Tal vez olvidó `self` al definir `{fn_name}`.\n"

#: runtime_errors\type_error.py:528
msgid ""
"You apparently have called the function '{fn_name}' with\n"
"fewer positional arguments than it requires ({nb_required} missing).\n"
msgstr ""
"Al parecer, ha llamado a la función '{fn_name}' con\n"
"menos argumentos posicionales de los que requiere (falta {nb_required}).\n"

#: runtime_errors\type_error.py:545 runtime_errors\type_error.py:928
#: warning_parsers\syntax_warning.py:21 warning_parsers\syntax_warning.py:69
msgid ""
"\n"
"Note: `NoneType` means that the object has a value of `None`.\n"
msgstr ""
"\n"
"Nota: `NoneType` significa que el objeto tiene un valor de `None`.\n"

#: runtime_errors\type_error.py:552 warning_parsers\syntax_warning.py:27
msgid ""
"Python indicates that you have an object of type `{obj_type}`,\n"
"followed by something surrounded by parentheses, `(...)`,\n"
"which Python took as an indication of a function call.\n"
"Either the object of type `{obj_type}` was meant to be a function,\n"
"or you forgot a comma before `(...)`.\n"
msgstr ""
"Python indica que tienes un objeto de tipo `{obj_type}`,\n"
"seguido de algo rodeado de paréntesis, `(...)`,\n"
"que Python toma como indicación de una llamada a una función.\n"
"O bien el objeto de tipo `{obj_type}` estaba destinado a ser una función,\n"
"o se ha olvidado una coma antes de `(...)`.\n"

#: runtime_errors\type_error.py:574
msgid ""
"The parenthesis `()` following `{obj_name}` are interpreted\n"
"by Python as a function call for `{obj_name}`.\n"
"However, `{obj_name}` is not a function but an object of type `{obj_type}`.\n"
msgstr ""
"Los paréntesis `()` que siguen a `{obj_name}` son interpretados\n"
"por Python como una llamada a una función para `{obj_name}`.\n"
"Sin embargo, `{obj_name}` no es una función sino un objeto de tipo "
"`{obj_type}`.\n"

#: runtime_errors\type_error.py:581
msgid ""
"Because of the surrounding parenthesis, `{fn_call}` \n"
"is interpreted by Python as indicating a function call for \n"
"`{obj_name}`, which is an object of type `{obj_type}`\n"
"which cannot be called.\n"
"\n"
msgstr ""
"Debido a los paréntesis que lo rodean, `{fn_call}` \n"
"es interpretado por Python como una llamada a una función para \n"
"`{obj_name}`, que es un objeto de tipo `{obj_type}`\n"
"que no puede ser llamado.\n"
"\n"

#: runtime_errors\type_error.py:594
msgid ""
"However, `{fn_call}` is a `tuple`.\n"
"Either the object `{obj_name}` was meant to be a function\n"
"or you have a missing comma between the object `{obj_name}`\n"
"and the tuple `{fn_call}` and meant to write\n"
"`{obj_name}, {fn_call}`.\n"
msgstr ""
"Sin embargo, `{fn_call}` es una `tupla`.\n"
"O bien el objeto `{obj_name}` debía ser una función\n"
"o falta una coma entre el objeto `{obj_name}` y la tupla\n"
"y la tupla `{fn_call}` y querías escribir\n"
"`{obj_name}, {fn_call}`.\n"

#: runtime_errors\type_error.py:601
msgid "Did you forget a comma between `{obj_name}` and `{fn_call}`?\n"
msgstr "¿Olvidaste una coma entre `{obj_name}` y `{fn_call}`?\n"

#: runtime_errors\type_error.py:607
msgid ""
"However, `{obj_name}` is a sequence.\n"
"Perhaps you meant to use `[]` instead of `()` and write\n"
"`{obj_name}[{slice}]`\n"
msgstr ""
"Sin embargo, `{obj_name}` es una secuencia.\n"
"Tal vez usted quería usar `[]` en lugar de `()` y escribir\n"
"`{obj_name}[{slice}]`\n"

#: runtime_errors\type_error.py:612
msgid "Did you mean `{obj_name}[{slice}]`?\n"
msgstr "¿Quiere decir `{obj_name}[{slice}]`?\n"

#: runtime_errors\type_error.py:623
msgid ""
"However, both `{obj_name}` and `{fn_call}` are numbers.\n"
"Perhaps you forgot a multiplication operator, `*`,\n"
"and meant to write `{obj_name} * {fn_call}`.\n"
msgstr ""
"Sin embargo, tanto `{obj_name}` como `{fn_call}` son números.\n"
"Tal vez olvidó un operador de multiplicación, `*`,\n"
"y quiso escribir `{obj_name}` * {fn_call}`.\n"

#: runtime_errors\type_error.py:628
msgid "Did you mean `{obj_name} * {fn_call}`?\n"
msgstr "¿Se refiere a `{obj_name}` * {fn_call}`?\n"

#: runtime_errors\type_error.py:640
msgid "Did you forget to convert `{name}` into an integer?\n"
msgstr "¿Olvidaste convertir `{name}` en un número entero?\n"

#: runtime_errors\type_error.py:641
msgid "Perhaps you forgot to convert `{name}` into an integer.\n"
msgstr "Tal vez hayas olvidado convertir `{name}` en un número entero.\n"

#: runtime_errors\type_error.py:653
msgid ""
"You can only multiply sequences, such as list, tuples,\n"
" strings, etc., by integers.\n"
msgstr ""
"Sólo se pueden multiplicar secuencias, como listas, tuplas\n"
"cadenas, etc., por enteros.\n"

#: runtime_errors\type_error.py:675
msgid "Did you forget to convert `{name1}` and `{name2}` into integers?\n"
msgstr "¿Has olvidado convertir `{name1}` y `{name2}` en enteros?\n"

#: runtime_errors\type_error.py:678
msgid "Perhaps you forgot to convert `{name1}` and `{name2}` into integers.\n"
msgstr "Tal vez olvidó convertir `{name1}` y `{name2}` en enteros.\n"

#: runtime_errors\type_error.py:714
msgid ""
"You wrote an object whose value is `None` where an integer was expected.\n"
msgstr ""
"Has escrito un objeto cuyo valor es `None` donde se esperaba un entero.\n"

#: runtime_errors\type_error.py:724
msgid "You wrote an object of type `{obj}` where an integer was expected.\n"
msgstr "Has escrito un objeto de tipo `{obj}` donde se esperaba un entero.\n"

#: runtime_errors\type_error.py:734
msgid "Did you forget to convert `{names}` into integers?\n"
msgstr "¿Olvidaste convertir `{names}` en enteros?\n"

#: runtime_errors\type_error.py:737
msgid "Perhaps you forgot to convert `{names}` into integers."
msgstr "Tal vez olvidó convertir `{names}` en enteros."

#: runtime_errors\type_error.py:760
msgid ""
"In the expression `{line}`\n"
"what is included between the square brackets, `[...]`,\n"
"must be either an integer or a slice\n"
"(`start:stop` or `start:stop:step`) \n"
"and you have used {obj_type} instead.\n"
msgstr ""
"En la expresión `{line}`\n"
"lo que se incluye entre los corchetes, `[...]`,\n"
"debe ser un número entero o un slice\n"
"(`inicio:parada` o `inicio:parada:paso`)\n"
"y se ha utilizado {obj_type} en su lugar.\n"

#: runtime_errors\type_error.py:771
msgid ""
"Note: sometimes this exception is raised because what Python\n"
"interprets as indices was meant to be a separate list, and a comma\n"
"should have been written before the opening `[` of that list.\n"
msgstr ""
"Nota: a veces se produce esta excepción porque lo que Python\n"
"interpreta como índices se supone que es una lista separada, y una coma\n"
"debería haberse escrito antes de la apertura `[` de esa lista.\n"

#: runtime_errors\type_error.py:776 syntax_errors\statement_analyzer.py:1159
#: syntax_errors\statement_analyzer.py:1531
msgid "Did you forget a comma?\n"
msgstr "¿Te has olvidado de una coma?\n"

#: runtime_errors\type_error.py:811
msgid ""
"Perhaps you have forgotten a comma between two identical lists\n"
"`{container}`. The second list had been interpreted as\n"
"the indexation of the first one by the index `{new_index}`\n"
msgstr ""
"Tal vez haya olvidado una coma entre dos listas idénticas\n"
"`{container}`. La segunda lista había sido interpretada como\n"
"la indexación de la primera por el índice `{new_index}`\n"

#: runtime_errors\type_error.py:817
msgid ""
"Perhaps you have forgotten a comma between the object `{container}`\n"
"and the list `{index}`.  The list `{index}` had been interpreted as\n"
"the indexation of object `{container}` by the index `{new_index}`\n"
msgstr ""
"Tal vez haya olvidado una coma entre el objeto `{container}`\n"
"y la lista `{index}`.  La lista `{index}` había sido interpretada como\n"
"la indexación del objeto `{container}` por el índice `{new_index}`\n"

#: runtime_errors\type_error.py:822
msgid "Did you forget a comma before `{index}`?\n"
msgstr "¿Olvidaste una coma antes de `{index}`?\n"

#: runtime_errors\type_error.py:881
msgid ""
"When using a slice to extract a range of elements\n"
"from a sequence, that is something like\n"
"`[start:stop]` or `[start:stop:step]`\n"
"each of `start`, `stop`, `step` must be either an integer, `None`,\n"
"or possibly some other object having an `__index__` method.\n"
msgstr ""
"Cuando se utiliza un slice para extraer un rango de elementos\n"
"de una secuencia, es decir, algo como\n"
"`[inicio:parada]` o `[inicio:parada:paso]`.\n"
"cada uno de los elementos `inicio`, `parada`, `paso` debe ser un entero, "
"`None`,\n"
"o posiblemente algún otro objeto que tenga un método `__index__`.\n"

#: runtime_errors\type_error.py:898
msgid ""
"Only hashable objects can be used\n"
"as elements of `set` or keys of `dict`.\n"
"Hashable objects are objects that do not change value\n"
"once they have been created."
msgstr ""
"Sólo se pueden utilizar objetos hasheables\n"
"como elementos de `set` o claves de `dict`.\n"
"Los objetos hasheables son aquellos que no cambian de valor\n"
"una vez que han sido creados."

#: runtime_errors\type_error.py:908
msgid "Instead of using {original}, consider using {replacement}.\n"
msgstr "En lugar de usar {original}, considere usar {replacement}.\n"

#: runtime_errors\type_error.py:934 warning_parsers\syntax_warning.py:75
msgid ""
"Subscriptable objects are typically containers from which\n"
"you can retrieve item using the notation `[...]`.\n"
msgstr ""
"Los objetos subscribibles son típicamente contenedores de los cuales\n"
"se puede recuperar un elemento utilizando la notación `[...]`.\n"

#: runtime_errors\type_error.py:946 warning_parsers\syntax_warning.py:79
msgid ""
"Using this notation, you attempted to retrieve an item\n"
"from an object of type `{obj_type}` which is not allowed.\n"
msgstr ""
"Utilizando esta notación, ha intentado recuperar un elemento\n"
"de un objeto de tipo `{tipo_obj}` que no está permitido.\n"

#: runtime_errors\type_error.py:963
msgid "Perhaps you meant to write `{line}`.\n"
msgstr "Tal vez quiso escribir `{line}`.\n"

#: runtime_errors\type_error.py:966
msgid ""
"Using this notation, you attempted to retrieve an item\n"
"from `{name}`, an object of type `{obj_type}`. This is not allowed.\n"
msgstr ""
"Utilizando esta notación, has intentado recuperar un elemento\n"
"de `{name}`, un objeto de tipo `{obj_type}`. Esto no está permitido.\n"

#: runtime_errors\type_error.py:1000
msgid ""
"An iterable is an object capable of returning its members one at a time.\n"
"Python containers (`list, tuple, dict`, etc.) are iterables.\n"
"'{obj_name}' is not a container. A container is required here.\n"
msgstr ""
"Un iterable es un objeto capaz de devolver sus miembros de uno en uno.\n"
"Los contenedores de Python (`lista, tupla, dict`, etc.) son iterables.\n"
"'{obj_name}' no es un contenedor. Aquí se requiere un contenedor.\n"

#: runtime_errors\type_error.py:1015
msgid ""
"An iterable is an object capable of returning its members one at a time.\n"
"Python containers (`list, tuple, dict`, etc.) are iterables.\n"
"An iterable is required here.\n"
msgstr ""
"Un iterable es un objeto capaz de devolver sus miembros de uno en uno.\n"
"Los contenedores de Python (`lista, tupla, dict`, etc.) son iterables.\n"
"Aquí se requiere un iterable.\n"

#: runtime_errors\type_error.py:1030 runtime_errors\value_error.py:25
msgid ""
"Unpacking is a convenient way to assign a name,\n"
"to each item of an iterable.\n"
msgstr ""
"El desempaquetado es una forma conveniente de asignar un nombre\n"
"a cada elemento de un iterable.\n"

#: runtime_errors\type_error.py:1034
msgid ""
"An iterable is an object capable of returning its members one at a time.\n"
"Python containers (`list, tuple, dict`, etc.) are iterables,\n"
"but not objects of type `{obj_type}`.\n"
msgstr ""
"Un iterable es un objeto capaz de devolver sus miembros de uno en uno.\n"
"Los contenedores de Python (`list, tuple, dict`, etc.) son iterables,\n"
"pero no objetos de tipo `{obj_type}`.\n"

#: runtime_errors\type_error.py:1049
msgid ""
"{function} does not accept a sequence as an argument.\n"
"Instead of writing `{line}`\n"
"perhaps you should use the `dict.fromkeys()` method: `{new_line}`.\n"
msgstr ""
"{function} no acepta una secuencia como argumento.\n"
"En lugar de escribir `{line}`\n"
"tal vez debería utilizar el método `dict.fromkeys()`: `{new_line}`.\n"

#: runtime_errors\type_error.py:1054
msgid "Perhaps you need to use the `dict.fromkeys()` method.\n"
msgstr "Tal vez necesite utilizar el método `dict.fromkeys()`.\n"

#: runtime_errors\type_error.py:1092 runtime_errors\type_error.py:1116
msgid "Did you forget to call `{name}`?\n"
msgstr "¿Olvidaste llamar a `{name}`?\n"

#: runtime_errors\type_error.py:1093 runtime_errors\type_error.py:1117
msgid ""
"I suspect that you forgot to add parentheses to call `{name}`.\n"
"You might have meant to write:\n"
"`{line}`\n"
msgstr ""
"Sospecho que has olvidado añadir paréntesis para llamar a `{name}`.\n"
"Puede que hayas querido escribir:\n"
"`{line}`\n"

#: runtime_errors\type_error.py:1131
msgid ""
"The function `vars` is used to list the content of the\n"
"`__dict__` attribute of an object.\n"
msgstr ""
"La función `vars` se utiliza para listar el contenido del atributo\n"
"`__dict__` de un objeto.\n"

#: runtime_errors\type_error.py:1140
msgid "Object `{name}` uses `__slots__` instead of `__dict__`.\n"
msgstr "El objeto `{name}` utiliza `__slots__` en lugar de `__dict__`.\n"

#: runtime_errors\type_error.py:1144
msgid ""
"`{name}`, the argument of `vars`, is an object without such an attribute.\n"
msgstr "`{name}`, el argumento de `vars`, es un objeto sin dicho atributo.\n"

#: runtime_errors\type_error.py:1165
msgid ""
"You have specified the value of argument `{argument}` more than once\n"
"when calling the function named `{function}`.\n"
msgstr ""
"Ha especificado el valor del argumento `{argument}` más de una vez\n"
"al llamar a la función llamada `{function}`.\n"

#: runtime_errors\type_error.py:1186
msgid "This function has only one argument: `{arguments}`\n"
msgstr "Esta función sólo tiene un argumento: `{arguments}`\n"

#: runtime_errors\type_error.py:1190
msgid ""
"This function has the following arguments:\n"
"`{arguments}`\n"
msgstr ""
"Esta función tiene los siguientes argumentos:\n"
"`{arguments}`\n"

#: runtime_errors\type_error.py:1200
msgid ""
"I am guessing that you were trying to count the number of elements\n"
"produced by a generator expression. You first need to capture them\n"
"in a list:\n"
"\n"
msgstr ""

#: runtime_errors\type_error.py:1221
msgid "    {new_line}\n"
msgstr ""
"    {new_line}\n"
"\n"

#: runtime_errors\type_error.py:1222
msgid "You likely need to build a list first.\n"
msgstr "Es probable que primero tengas que crear una lista.\n"

#: runtime_errors\unbound_local_error.py:31
msgid ""
"You're trying to use the name `{name}` identified by Python as being\n"
"in the local scope of a function before having assigned it a value.\n"
msgstr ""
"Estás tratando de usar el nombre `{name}` identificado por Python como "
"estando\n"
"en el ámbito local de una función antes de haberle asignado un valor.\n"

#: runtime_errors\unbound_local_error.py:62
msgid ""
"The name `{var_name}` exists in both the global and nonlocal scope.\n"
"This can be rather confusing and is not recommended.\n"
"Depending on which variable you wanted to refer to, you needed to add "
"either\n"
"\n"
"    global {var_name}\n"
"\n"
"or\n"
"\n"
"    nonlocal {var_name}\n"
"\n"
"as the first line inside your function.\n"
msgstr ""
"El nombre `{var_name}` existe tanto en el ámbito global como en el no "
"local.\n"
"Esto puede ser bastante confuso y no es recomendable.\n"
"Dependiendo de la variable a la que quiera referirse, deberá añadir\n"
"\n"
"    global {var_name}\n"
"\n"
"o\n"
"\n"
"    nonlocal {var_name}\n"
"\n"
"como la primera línea dentro de su función.\n"

#: runtime_errors\unbound_local_error.py:72
msgid ""
"Did you forget to add either `global {var_name}` or \n"
"`nonlocal {var_name}`?\n"
msgstr ""
"¿Olvidó añadir `global {var_name}` o \n"
"`nonlocal {var_name}`?\n"

#: runtime_errors\unbound_local_error.py:84
msgid ""
"`{name}` is a Python builtin function.\n"
"You have tried to assign a value to `{name}` inside a function\n"
"while also using its original meaning in the function.\n"
"\n"
"Note that it is generally not a good idea to give a local variable\n"
"the same name as a Python builtin function (like `{name}`).\n"
msgstr ""
"`{name}` es una función incorporada de Python.\n"
"Has intentado asignar un valor a `{name}` dentro de una función\n"
"al mismo tiempo que utilizas su significado original en la función.\n"
"\n"
"Tenga en cuenta que generalmente no es una buena idea dar a una variable "
"local\n"
"el mismo nombre que a una función incorporada de Python (como `{name}`).\n"

#: runtime_errors\unbound_local_error.py:101
msgid ""
"The name `{var_name}` exists in the {scope} scope.\n"
"Perhaps the statement\n"
"\n"
"    {scope} {var_name}\n"
"\n"
"should have been included as the first line inside your function.\n"
msgstr ""
"El nombre `{var_name}` existe en el ámbito {scope}.\n"
"Quizás la sentencia\n"
"\n"
"    {scope} {var_name}\n"
"\n"
"debería haber sido incluida como la primera línea dentro de su función.\n"

#: runtime_errors\unbound_local_error.py:108
msgid "Did you forget to add `{scope} {var_name}`?\n"
msgstr "¿Olvidaste añadir `{scope} {var_name}`?\n"

#: runtime_errors\unbound_local_error.py:119
msgid "The similar name `{name}` was found in the local scope. "
msgstr "Se ha encontrado el nombre similar `{name}` en el ámbito local. "

#: runtime_errors\value_error.py:72 runtime_errors\value_error.py:81
msgid ""
"In this instance, there are more names ({nb_names})\n"
"than {length}, the length of the iterable.\n"
msgstr ""
"En este caso, hay más nombres ({nb_names})\n"
"que {length}, la longitud del iterable.\n"

#: runtime_errors\value_error.py:87
msgid ""
"In this instance, there are more names ({nb_names})\n"
"than the length of the iterable, {iter_type} of length {length}.\n"
msgstr ""
"En este caso, hay más nombres ({nb_names})\n"
"que la longitud del iterable, {iter_type} de longitud {length}.\n"

#: runtime_errors\value_error.py:105 runtime_errors\value_error.py:115
msgid ""
"In this instance, there are fewer names ({nb_names})\n"
"than the length of the iterable.\n"
msgstr ""
"En este caso, hay menos nombres ({nb_names})\n"
"que la longitud del iterable.\n"

#: runtime_errors\value_error.py:121
msgid ""
"In this instance, there are fewer names ({nb_names})\n"
"than the length of the iterable, {iter_type} of length {length}.\n"
msgstr ""
"En este caso, hay menos nombres ({nb_names})\n"
"que la longitud del iterable, {iter_type} de longitud {length}.\n"

#: runtime_errors\value_error.py:137
msgid ""
"`int()` expects an argument that looks like a number in base `{base}`\n"
"but you gave it an empty string.\n"
msgstr ""
"`int()` espera un argumento que parezca un número en base `{base}`\n"
"pero le has dado una cadena vacía.\n"

#: runtime_errors\value_error.py:143
msgid "`{value}` is an invalid argument for `int()` in base `{base}`.\n"
msgstr "`{value}` es un argumento no válido para `int()` en base `{base}`.\n"

#: runtime_errors\value_error.py:159
msgid "The following characters are not allowed: `{invalid}`.\n"
msgstr "Los siguientes caracteres no están permitidos: `{invalid}`.\n"

#: runtime_errors\value_error.py:171
msgid ""
"When base `0` is specified, `int()` expects the argument\n"
"to be an integer literal, written in\n"
"base 2 (`0b...`), 8 (`0o...`), 10, or 16 (`0x...`).\n"
msgstr ""
"Cuando se especifica la base `0`, `int()` espera que el argumento\n"
"sea un literal entero, escrito en\n"
"base 2 (`0b...`), 8 (`0o...`), 10, o 16 (`0x...`).\n"

#: runtime_errors\value_error.py:177
msgid ""
"In base `{base}`, `int()` is most often use to convert a string\n"
"containing the digits `0` to `{max_n}` into an integer.\n"
msgstr ""
"En base `{base}`, `int()` se utiliza más a menudo para convertir una cadena\n"
"que contiene los dígitos `0` a `{max_n}` en un número entero.\n"

#: runtime_errors\value_error.py:182
msgid ""
"In base `11`, `int()` is most often use to convert a string\n"
"containing the digits `0` to `9` and the letter `'a'` into an integer.\n"
msgstr ""
"En base `11`, `int()` se utiliza más a menudo para convertir una cadena\n"
"que contiene los dígitos \"0\" a \"9\" y la letra \"a\" en un número "
"entero.\n"

#: runtime_errors\value_error.py:187
msgid ""
"In base `base`, `int()` is most often use to convert a string\n"
"containing the digits `0` to `9` and the letters\n"
"from `'a'` to `'{max_n}'` into an integer.\n"
msgstr ""
"En base `base`, `int()` se utiliza más a menudo para convertir una cadena\n"
"que contiene los dígitos \"0\" a \"9\" y las letras\n"
"desde `'a'` hasta `'{max_n}'` en un número entero.\n"

#: runtime_errors\value_error.py:203
msgid "You need to convert `'{value}'` to a float first.\n"
msgstr "Primero hay que convertir `'{value}` en un float.\n"

#: runtime_errors\value_error.py:204
msgid ""
"The string `'{value}'` needs to be first converted using `float()`\n"
"before the result can be converted into an integer using `int()`.\n"
msgstr ""
"La cadena `'{value}` necesita ser convertida primero usando `float()`\n"
"antes de poder convertir el resultado en un entero con `int()`.\n"

#: runtime_errors\value_error.py:216
msgid ""
"The argument `base` of `int()` must be either zero\n"
"or any integer from 2 to 36.\n"
msgstr ""
"El argumento `base` de `int()` debe ser cero\n"
"o un número entero entre 2 y 36.\n"

#: runtime_errors\value_error.py:224
msgid "You wrote {base} which is not allowed.\n"
msgstr "Has escrito {base} que no está permitido.\n"

#: runtime_errors\value_error.py:235
msgid "Did you specify an invalid month?\n"
msgstr "¿Especificó un mes no válido?\n"

#: runtime_errors\value_error.py:236
msgid ""
"I am guessing that you specify an invalid value for a month\n"
"in a `date` object. Valid values are integers, from 1 to 12.\n"
msgstr ""
"Supongo que especifica un valor no válido para un mes\n"
"en un objeto `date`. Los valores válidos son enteros, del 1 al 12.\n"

#: runtime_errors\value_error.py:253
#, fuzzy
#| msgid "The string `{string}` cannot be converted to a `float`.\n"
msgid ""
"The string `{string}` cannot be converted to a `float`\n"
"as it does not represent a number.\n"
msgstr "La cadena `{string}` no se puede convertir en un `float`.\n"

#: runtime_errors\value_error.py:269
msgid ""
"The name `{var}` is used both as the name of a class variable\n"
"and as a string item in the class `__slots__`;\n"
"this is not allowed.\n"
msgstr ""
"El nombre `{var}` se utiliza tanto como nombre de una variable de clase\n"
"y como elemento de cadena en la clase `__slots__`;\n"
"esto no está permitido.\n"

#: runtime_errors\value_error.py:281
msgid "The third argument of the function `pow()` cannot be zero.\n"
msgstr "El tercer argumento de la función `pow()` no puede ser cero.\n"

#: runtime_errors\value_error.py:310
msgid ""
"I do not recognize this error message.\n"
"I am guessing that the problem is with the function `{name}`.\n"
msgstr ""
"No reconozco este mensaje de error.\n"
"Supongo que el problema está en la función `{name}`.\n"

#: runtime_errors\value_error.py:316
msgid ""
"Its docstring is:\n"
"\n"
"{docstring}\n"
msgstr ""
"Su docstring es:\n"
"\n"
"{docstring}\n"

#: runtime_errors\value_error.py:320
msgid "I have no more information.\n"
msgstr "No tengo mas información.\n"

#: runtime_errors\value_error.py:330
msgid ""
"The value you gave for the time is not in the format you specified.\n"
"Make sure to use the same separator between items\n"
"(for example, between day and month) and keep the order the same\n"
"in both the data provided and the format you specified.\n"
"The following table might be useful:\n"
"https://docs.python.org/3/library/time.html#time.strftime\n"
"The following site might also be useful: https://www.strfti.me/\n"
msgstr ""
"El valor que has dado para la hora no está en el formato que has "
"especificado.\n"
"Asegúrese de utilizar el mismo separador entre los elementos\n"
"(por ejemplo, entre el día y el mes) y mantener el mismo orden\n"
"tanto en los datos proporcionados como en el formato que ha especificado.\n"
"La siguiente tabla puede ser útil:\n"
"https://docs.python.org/3/library/time.html#time.strftime\n"
"El siguiente sitio también puede ser útil: https://www.strfti.me/\n"

#: runtime_errors\value_error.py:365
msgid ""
"You have attempted to remove `{item}` from the list `{the_list}`.\n"
"However, `{the_list}` does not contain `{item}`.\n"
msgstr ""

#: runtime_errors\value_error.py:370
msgid ""
"You have attempted to remove an item from the list `{the_list}`.\n"
"However, `{the_list}` does not contain that item.\n"
msgstr ""

#: runtime_errors\value_error.py:375
msgid ""
"You have attempted to remove an item a list that does not contain such an "
"item.\n"
msgstr ""

#: runtime_errors\value_error.py:391
msgid ""
"An explanation of `{exception}` already exists.\n"
"If you think that a better explanation can be given, please file an issue.\n"
msgstr ""

#: runtime_errors\zero_division_error.py:20
#, fuzzy
#| msgid "Using the modulo operator, you are dividing by zero.\n"
msgid "Using the modulo operator, `%`, you are dividing by zero.\n"
msgstr "Usando el operador módulo, estás dividiendo por cero.\n"

#: runtime_errors\zero_division_error.py:21
msgid "You are dividing by zero.\n"
msgstr "Estás dividiendo por cero.\n"

#: runtime_errors\zero_division_error.py:41
#: runtime_errors\zero_division_error.py:73
msgid ""
"You are dividing by the following term\n"
"\n"
"    {expression}\n"
"\n"
"which is equal to zero.\n"
msgstr ""
"Usted está dividiendo por el siguiente término\n"
"\n"
"    {expression}\n"
"\n"
"que es igual a cero.\n"

#: runtime_errors\zero_division_error.py:53
#: runtime_errors\zero_division_error.py:127
msgid "<'expression not found'>"
msgstr ""

#: runtime_errors\zero_division_error.py:54
msgid ""
"The following mathematical expression includes a division by zero:\n"
"\n"
"    {expression}\n"
msgstr ""
"La siguiente expresión matemática incluye una división por cero:\n"
"\n"
"    {expression}\n"

#: runtime_errors\zero_division_error.py:85
#: runtime_errors\zero_division_error.py:120
#, fuzzy
#| msgid ""
#| "Using the modulo operator, you are dividing by the following term\n"
#| "\n"
#| "    {expression}\n"
#| "\n"
#| "which is equal to zero.\n"
msgid ""
"Using the modulo operator, `%`, you are dividing by the following term\n"
"\n"
"    {expression}\n"
"\n"
"which is equal to zero.\n"
msgstr ""
"Usando el operador de módulo, estás dividiendo por el siguiente término\n"
"\n"
"    {expression}\n"
"\n"
"que es igual a cero.\n"

#: runtime_errors\zero_division_error.py:93
msgid "The second argument of the `divmod()` function is zero.\n"
msgstr "El segundo argumento de la función `divmod()` es cero.\n"

#: runtime_errors\zero_division_error.py:104
msgid ""
"You are attempting to raise the number 0 to a negative power\n"
"which is equivalent to dividing by zero.\n"
msgstr ""
"Estás intentando elevar el número 0 a una potencia negativa\n"
"que equivalente a dividir por cero.\n"

#: runtime_errors\zero_division_error.py:128
msgid ""
"The following mathematical expression includes a division by zero\n"
"done using the modulo operator:\n"
"\n"
"    {expression}\n"
msgstr ""
"La siguiente expresión matemática incluye una división por cero\n"
"realizada con el operador módulo:\n"
"\n"
"    {expression}\n"

#: runtime_errors\zero_division_error.py:143
msgid "The second argument of the `divmod()` function is equal to zero.\n"
msgstr "El segundo argumento de la función `divmod()` es igual a cero.\n"

#: syntax_errors\analyze_syntax.py:29
msgid ""
"Currently, I cannot guess the likely cause of this error.\n"
"Try to examine closely the line indicated as well as the line\n"
"immediately above to see if you can identify some misspelled\n"
"word, or missing symbols, like (, ), [, ], :, etc.\n"
"\n"
"Unless your code uses type annotations, which are beyond our scope,\n"
"if you think that this is something which should be handled\n"
"by friendly, please report this case to\n"
"https://github.com/friendly-traceback/friendly-traceback/issues\n"
"\n"
msgstr ""
"Actualmente, no puedo detectar la causa probable de este error.\n"
"Intente examinar detenidamente la línea indicada, así como la línea\n"
"inmediatamente superior para ver si puede identificar alguna palabra mal "
"escrita\n"
"o símbolos que falten, como (, ), [, ], :, etc.\n"
"\n"
"A menos que su código utilice anotaciones de tipo, que están fuera de "
"nuestro alcance,\n"
"si cree que esto es algo que debería ser manejado\n"
"por friendly, por favor reporte este caso a\n"
"https://github.com/friendly-traceback/friendly-traceback/issues\n"
"\n"

#: syntax_errors\analyze_syntax.py:72
msgid ""
"Python told us that it expected a colon at the position indicated.\n"
"However, adding a colon or replacing something else by a colon\n"
"would not fix the problem.\n"
msgstr ""
"Python nos dijo que esperaba dos puntos en la posición indicada.\n"
"Sin embargo, añadir dos puntos o sustituir algo por dos puntos\n"
"no solucionaría el problema.\n"

#: syntax_errors\analyze_syntax.py:86
msgid ""
"Python gave us the following informative message\n"
"about the possible cause of the error:\n"
"\n"
"    {message}\n"
"\n"
"However, I do not recognize this information and I have\n"
"to guess what caused the problem, but I might be wrong.\n"
"\n"
msgstr ""
"Python nos dio el siguiente mensaje informativo\n"
"sobre la posible causa del error:\n"
"\n"
"    {message}\n"
"\n"
"Sin embargo, no reconozco esta información y tengo\n"
"adivinar la causa del problema, pero puedo estar equivocado.\n"
"\n"

#: syntax_errors\error_in_def.py:19 syntax_errors\statement_analyzer.py:20
msgid ""
"However, making such a change would still not correct\n"
"all the syntax errors in the code you wrote.\n"
msgstr ""
"Sin embargo, hacer tal cambio no corregiría\n"
"todos los errores de sintaxis en el código que escribiste.\n"

#: syntax_errors\error_in_def.py:28
msgid ""
"The correct syntax is:\n"
"\n"
"    {async_}def name ( ... ):"
msgstr ""
"La sintaxis correcta es:\n"
"\n"
"    {async_}def name ( ... ):"

#: syntax_errors\error_in_def.py:80
msgid "A function needs a name.\n"
msgstr "Una función necesita un nombre.\n"

#: syntax_errors\error_in_def.py:81
msgid "You tried to define a function and did not use the correct syntax.\n"
msgstr ""
"Has intentado definir una función y no has utilizado la sintaxis correcta.\n"

#: syntax_errors\error_in_def.py:85
msgid "Functions and methods need a name.\n"
msgstr "Las funciones y los métodos necesitan un nombre.\n"

#: syntax_errors\error_in_def.py:86
msgid ""
"You tried to define a function or method and did not use the correct "
"syntax.\n"
msgstr ""
"Has intentado definir una función o un método y no has utilizado la sintaxis "
"correcta.\n"

#: syntax_errors\error_in_def.py:116 syntax_errors\error_in_def.py:147
#: syntax_errors\message_analyzer.py:1111
#: syntax_errors\message_analyzer.py:1649
#: syntax_errors\statement_analyzer.py:1312
#: syntax_errors\statement_analyzer.py:1331
msgid "Did you forget parentheses?\n"
msgstr "¿Has olvidado los paréntesis?\n"

#: syntax_errors\error_in_def.py:117 syntax_errors\error_in_def.py:148
msgid ""
"Perhaps you forgot to include parentheses.\n"
"You might have meant to write\n"
"\n"
"    {line}\n"
msgstr ""
"Tal vez haya olvidado incluir los paréntesis.\n"
"Puede que hayas querido escribir\n"
"\n"
"    {line}\n"

#: syntax_errors\error_in_def.py:175
msgid "A function definition statement must end with a colon.\n"
msgstr ""
"Una declaración de definición de función debe terminar con dos puntos.\n"

#: syntax_errors\error_in_def.py:181 syntax_errors\error_in_def.py:205
msgid "Did you forget to write a colon?\n"
msgstr "¿Olvidaste escribir dos puntos?\n"

#: syntax_errors\error_in_def.py:182 syntax_errors\message_analyzer.py:765
msgid "You wrote `{bad}` instead of a colon.\n"
msgstr "Has escrito `{bad}` en lugar de dos puntos.\n"

#: syntax_errors\error_in_def.py:191
msgid "Did you write something by mistake after the colon?\n"
msgstr "¿Escribiste algo por error después de los dos puntos?\n"

#: syntax_errors\error_in_def.py:192
msgid "A block of code must come after the colon.\n"
msgstr "Un bloque de código debe ir después de los dos puntos.\n"

#: syntax_errors\error_in_def.py:193
msgid "Removing `{bad}`, might fix the problem.\n"
msgstr "Eliminar `{bad}`, podría solucionar el problema.\n"

#: syntax_errors\error_in_def.py:225
msgid "You cannot use a Python keyword as a function name.\n"
msgstr ""
"No se puede utilizar una palabra clave de Python como nombre de función.\n"

#: syntax_errors\error_in_def.py:226
msgid "You tried to use the Python keyword `{kwd}` as a function name.\n"
msgstr ""
"Has intentado utilizar la palabra clave de Python `{kwd}` como nombre de "
"función.\n"

#: syntax_errors\error_in_def.py:234
msgid "There are more syntax errors later in your code.\n"
msgstr "Hay errores de sintaxis adicionales más adelante en su código.\n"

#: syntax_errors\error_in_def.py:257
msgid "You wrote an invalid function name.\n"
msgstr "Has escrito un nombre de función no válido.\n"

#: syntax_errors\error_in_def.py:258
msgid ""
"The name of a function must be a valid Python identifier,\n"
"that is a name that begins with a letter or an underscore character, `_`,\n"
"and which contains only letters, digits or the underscore character.\n"
msgstr ""
"El nombre de una función debe ser un identificador válido de Python,\n"
"es decir, un nombre que comience con una letra o un carácter de subrayado, "
"`_`,\n"
"y que contenga sólo letras, dígitos o el carácter de subrayado.\n"

#: syntax_errors\error_in_def.py:264
msgid "You attempted to use a string as a function name.\n"
msgstr "Has intentado utilizar una cadena como nombre de función.\n"

#: syntax_errors\error_in_def.py:285
msgid "You forgot to name your function.\n"
msgstr "Has olvidado nombrar tu función.\n"

#: syntax_errors\error_in_def.py:293
msgid "However, there are some other syntax errors in your code.\n"
msgstr ""
"Sin embargo, hay algunos errores de sintaxis adicionales en su código.\n"

#: syntax_errors\error_in_def.py:314
msgid ""
"I am guessing that you tried to use the Python keyword\n"
"`{kwd}` as an argument in the definition of a function\n"
"where an identifier (variable name) was expected.\n"
msgstr ""
"Supongo que has intentado utilizar la palabra clave de Python\n"
"`{kwd}` como argumento en la definición de una función\n"
"donde se esperaba un identificador (nombre de variable).\n"

#: syntax_errors\error_in_def.py:329
msgid "You cannot use dotted names as function arguments.\n"
msgstr ""
"No se pueden utilizar nombres con puntos como argumentos de funciones.\n"

#: syntax_errors\error_in_def.py:331
msgid "Perhaps you meant to write a comma.\n"
msgstr "Tal vez querías escribir una coma.\n"

#: syntax_errors\error_in_def.py:332 syntax_errors\error_in_def.py:524
#: syntax_errors\statement_analyzer.py:827 syntax_errors\syntax_utils.py:119
msgid "Did you mean to write a comma?\n"
msgstr "¿Querías escribir una coma?\n"

#: syntax_errors\error_in_def.py:336
msgid "You cannot use dots in function names.\n"
msgstr "No se pueden utilizar puntos en los nombres de las funciones.\n"

#: syntax_errors\error_in_def.py:345
msgid ""
"`/` indicates that the previous arguments in a function definition\n"
"are positional arguments.\n"
msgstr ""
"`/` indica que los argumentos anteriores en una definición de función\n"
"son argumentos posicionales.\n"

#: syntax_errors\error_in_def.py:351
msgid ""
"Function definitions cannot include the symbol `/` in this Python version.\n"
msgstr ""
"Las definiciones de funciones no pueden incluir el símbolo `/` en esta "
"versión de Python.\n"

#: syntax_errors\error_in_def.py:354
msgid ""
"This symbol can only be used with Python versions 3.8.0 or newer.\n"
"You are using Python version {version}.\n"
msgstr ""
"Este símbolo sólo puede utilizarse con las versiones de Python 3.8.0 o "
"posteriores.\n"
"Está utilizando la versión de Python {version}.\n"

#: syntax_errors\error_in_def.py:363
msgid ""
"You have unspecified keyword arguments that appear before\n"
"the symbol `/`.\n"
msgstr ""
"Tiene argumentos de palabras clave no especificadas que aparecen antes de\n"
"el símbolo `/`.\n"

#: syntax_errors\error_in_def.py:367
msgid "Keyword arguments must appear after the `/` symbol.\n"
msgstr ""
"Los argumentos de las palabras clave deben aparecer después del símbolo `/"
"`.\n"

#: syntax_errors\error_in_def.py:372
msgid ""
"However, `*` indicates that the arguments\n"
"that follow must be keyword arguments.\n"
"When they are used together, `/` must appear before `*`.\n"
msgstr ""
"Sin embargo, `*` indica que los argumentos\n"
"que siguen deben ser argumentos de palabra clave.\n"
"Cuando se utilizan juntos, `/` debe aparecer antes de `*`.\n"

#: syntax_errors\error_in_def.py:377
msgid "`*` must appear after `/` in a function definition.\n"
msgstr ""
"El símbolo `*` debe aparecer después de `/` en la definición de una "
"función.\n"

#: syntax_errors\error_in_def.py:379
msgid "`*{name}` must appear after `/` in a function definition.\n"
msgstr ""
"La palabra `*{name}` debe aparecer después de `/` en la definición de una "
"función.\n"

#: syntax_errors\error_in_def.py:386
msgid "You can only use `/` once in a function definition.\n"
msgstr "Sólo se puede utilizar `/` una vez en la definición de una función.\n"

#: syntax_errors\error_in_def.py:400
msgid "You can only use `*` once in a function definition.\n"
msgstr "Sólo se puede utilizar `*` una vez en la definición de una función.\n"

#: syntax_errors\error_in_def.py:406
msgid "You have used it twice, with `*{first}` and `*{second}`.\n"
msgstr "Lo has utilizado dos veces, con `*{first}` y `*{second}`.\n"

#: syntax_errors\error_in_def.py:414
msgid ""
"It must either be used by itself, `*`,\n"
"or in the form `*{args}`, but not both.\n"
msgstr ""
"Debe usarse solo, `*`,\n"
"o en la forma `*{args}`, pero no ambas.\n"

#: syntax_errors\error_in_def.py:423
msgid "`*{args}` must appear before `**{kwargs}`.\n"
msgstr "`*{args}` debe aparecer antes de `**{kwargs}`.\n"

#: syntax_errors\error_in_def.py:427
msgid "`**{kwargs}` must appear after the `*` operator.\n"
msgstr "`**{kwargs}` debe aparecer después del operador `*`.\n"

#: syntax_errors\error_in_def.py:441
msgid "You cannot use numbers as function arguments.\n"
msgstr "No se pueden utilizar números como argumentos de funciones.\n"

#: syntax_errors\error_in_def.py:442
msgid ""
"You used a number as an argument when defining a function.\n"
"You can only use identifiers (variable names) as function arguments.\n"
msgstr ""
"Ha utilizado un número como argumento al definir una función.\n"
"Sólo puede utilizar identificadores (nombres de variables) como argumentos "
"de funciones.\n"

#: syntax_errors\error_in_def.py:454
msgid "You cannot use strings as function arguments.\n"
msgstr "No se pueden utilizar cadenas como argumentos de funciones.\n"

#: syntax_errors\error_in_def.py:455
msgid ""
"You used a string as an argument when defining a function.\n"
"You can only use identifiers (variable names) as function arguments.\n"
msgstr ""
"Ha utilizado una cadena como argumento al definir una función.\n"
"Sólo se pueden utilizar identificadores (nombres de variables) como "
"argumentos de funciones.\n"

#: syntax_errors\error_in_def.py:467
msgid "You cannot have explicit tuples as function arguments.\n"
msgstr "No se pueden tener tuplas explícitas como argumentos de la función.\n"

#: syntax_errors\error_in_def.py:469
msgid ""
"You can only use identifiers (variable names) as function arguments.\n"
"Assign any tuple to a parameter and unpack it\n"
"within the body of the function.\n"
msgstr ""
"Sólo se pueden utilizar identificadores (nombres de variables) como "
"argumentos de funciones.\n"
"Asignar cualquier tupla a un parámetro y desempaquetarla\n"
"dentro del cuerpo de la función.\n"

#: syntax_errors\error_in_def.py:482
msgid "You cannot have explicit lists as function arguments.\n"
msgstr "No se pueden tener listas explícitas como argumentos de funciones.\n"

#: syntax_errors\error_in_def.py:483 syntax_errors\error_in_def.py:495
msgid "You can only use identifiers (variable names) as function arguments.\n"
msgstr ""
"Sólo se pueden utilizar identificadores (nombres de variables) como "
"argumentos de funciones.\n"

#: syntax_errors\error_in_def.py:494
msgid "You cannot have any explicit dict or set as function arguments.\n"
msgstr ""
"No puede tener ningún dict o set explícito como argumentos de la función.\n"

#: syntax_errors\error_in_def.py:517
msgid "You cannot have operators as function arguments.\n"
msgstr "No se pueden tener operadores como argumentos de la función.\n"

#: syntax_errors\error_in_def.py:525
msgid ""
"I suspect you made a typo and wrote `{op}` instead of a comma.\n"
"The following statement contains no syntax error:\n"
"\n"
"    {new_statement}"
msgstr ""
"Sospecho que has cometido un error tipográfico y has escrito `{op}` en lugar "
"de una coma.\n"
"La siguiente declaración no contiene ningún error de sintaxis:\n"
"\n"
"    {new_statement}"

#: syntax_errors\error_in_def.py:537
msgid "Did you mean to write an equal sign?\n"
msgstr "¿Querías escribir un signo de igualdad?\n"

#: syntax_errors\error_in_def.py:538
msgid ""
"I suspect you made a typo and wrote `{op}` instead of an equal sign.\n"
"The following statement contains no syntax error:\n"
"\n"
"    {new_statement}"
msgstr ""
"Sospecho que has cometido un error tipográfico y has escrito `{op}` en lugar "
"de un signo de igualdad.\n"
"La siguiente declaración no contiene ningún error de sintaxis:\n"
"\n"
"    {new_statement}"

#: syntax_errors\error_in_def.py:550
msgid "Did you mean to write `{op}`?\n"
msgstr "¿Querías escribir `{op}`?\n"

#: syntax_errors\error_in_def.py:551
msgid ""
"I suspect you made a typo and added `{op}` by mistake.\n"
"The following statement contains no syntax error:\n"
"\n"
"    {new_statement}"
msgstr ""
"Sospecho que has cometido un error tipográfico y has añadido `{op}` por "
"error.\n"
"La siguiente declaración no contiene ningún error de sintaxis:\n"
"\n"
"    {new_statement}"

#: syntax_errors\error_in_def.py:567
msgid "You cannot use `{op}` as an argument.\n"
msgstr "No se puede utilizar `{op}` como argumento.\n"

#: syntax_errors\error_in_def.py:571
msgid ""
"I suspect you made a typo and wrote `{op}` by mistake.\n"
"If you replace it by a unique variable name, the result\n"
"will contain no syntax error.\n"
msgstr ""
"Sospecho que has cometido una errata y has escrito `{op}` por error.\n"
"Si lo sustituye por un nombre de variable único, el resultado\n"
"no contendrá ningún error de sintaxis.\n"

#: syntax_errors\error_in_def.py:579
msgid ""
"I suspect you made a typo and wrote `{op}` by mistake,\n"
"perhaps instead of writing an identifier (variable name).\n"
msgstr ""
"Sospecho que has cometido una errata y has escrito `{op}` por error,\n"
"tal vez en lugar de escribir un identificador (nombre de la variable).\n"

#: syntax_errors\error_in_def.py:588
msgid ""
"The `**` operator needs to be followed by an identifier (variable name).\n"
msgstr ""
"El operador `**` debe ir seguido de un identificador (nombre de la "
"variable).\n"

#: syntax_errors\error_in_def.py:611
msgid "Positional arguments must come before keyword arguments.\n"
msgstr ""
"Los argumentos posicionales deben ir antes de los argumentos de palabra "
"clave.\n"

#: syntax_errors\error_in_def.py:612
msgid ""
"`{arg}` is a positional argument that appears after one or more\n"
"keyword arguments in your function definition.\n"
msgstr ""
"`{arg}` es un argumento posicional que aparece después de uno o más\n"
"argumentos de la palabra clave en la definición de la función.\n"

#: syntax_errors\indentation_error.py:11
msgid "Line `{number}` identified above is more indented than expected.\n"
msgstr ""
"La línea `{number}` identificada arriba tiene más indentación de la "
"esperada.\n"

#: syntax_errors\indentation_error.py:15
msgid ""
"Line `{number}` identified above was expected to begin a new indented "
"block.\n"
msgstr ""
"Se esperaba que la línea `{number}` identificada anteriormente comenzara un "
"nuevo bloque indentado.\n"

#: syntax_errors\indentation_error.py:20
msgid "Line `{number}` identified above is less indented than expected.\n"
msgstr ""
"La línea `{number}` identificada arriba tiene menos indentación de la "
"esperada.\n"

#: syntax_errors\indentation_error.py:32
msgid ""
"However, line {number}, which is identified as having a problem,\n"
"consists of a single string which is also the case\n"
"for the preceding line.\n"
"Perhaps you meant to include a continuation character, `\\`,\n"
"at the end of line {preceding}.\n"
msgstr ""
"Sin embargo, la línea {number}, que se identifica como\n"
"consiste en una sola cadena, lo que también ocurre\n"
"de la línea anterior.\n"
"Tal vez haya querido incluir un carácter de continuación, ``,\n"
"al final de la línea {preceding}.\n"

#: syntax_errors\message_analyzer.py:22
msgid "You can only assign objects to identifiers (variable names).\n"
msgstr ""
"Sólo se pueden asignar objetos a identificadores (nombres de variables).\n"

#: syntax_errors\message_analyzer.py:26
#: syntax_errors\statement_analyzer.py:1657
msgid ""
"You can only delete names of objects, or items in mutable containers\n"
"such as `list`, `set`, or `dict`.\n"
msgstr ""
"Sólo se pueden borrar nombres de objetos, o elementos en contenedores "
"mutables\n"
"como `list`, `set` o `dict`.\n"

#: syntax_errors\message_analyzer.py:54
msgid "of type `int`"
msgstr "de tipo `int`"

#: syntax_errors\message_analyzer.py:55
msgid "of type `complex`"
msgstr "de tipo `complex`"

#: syntax_errors\message_analyzer.py:56
msgid "of type `float`"
msgstr "de tipo `float`"

#: syntax_errors\message_analyzer.py:57
msgid "of type `str`"
msgstr "de tipo `str`"

#: syntax_errors\message_analyzer.py:58
msgid "of type `dict`"
msgstr "de tipo `dict`"

#: syntax_errors\message_analyzer.py:59
msgid "of type `list`"
msgstr "de tipo `list`"

#: syntax_errors\message_analyzer.py:60
msgid "of type `set`"
msgstr "de tipo `set`"

#: syntax_errors\message_analyzer.py:61
msgid "of type `tuple`"
msgstr "de tipo `tuple`"

#: syntax_errors\message_analyzer.py:81 syntax_errors\message_analyzer.py:91
msgid "Did you mean `{num}`?\n"
msgstr "¿Querías decir `{num}`?\n"

#: syntax_errors\message_analyzer.py:82
msgid ""
"Perhaps you meant to write the octal number `{num}`\n"
"and forgot the letter 'o', or perhaps you meant to write\n"
"a decimal integer and did not know that it could not start with zeros.\n"
msgstr ""
"Tal vez querías escribir el número octal `{num}`\n"
"y se olvidó de la letra 'o', o tal vez quería escribir\n"
"un número entero decimal y no sabía que no podía empezar con ceros.\n"

#: syntax_errors\message_analyzer.py:92
msgid ""
"Perhaps you meant to write the integer `{num}`\n"
"and did not know that it could not start with zeros.\n"
msgstr ""
"Tal vez usted quiso escribir el número entero `{num}`\n"
"y no sabía que no podía empezar con ceros.\n"

#: syntax_errors\message_analyzer.py:131
msgid ""
"On the left-hand side of an equal sign, you have a\n"
"conditional expression instead of the name of a variable.\n"
"A conditional expression has the following form:\n"
"\n"
"    variable = object if condition else other_object\n"
msgstr ""
"En el lado izquierdo de un signo igual, tiene una\n"
"expresión condicional en lugar del nombre de una variable.\n"
"Una expresión condicional tiene la siguiente forma:\n"
"\n"
"    variable = objeto if condición else otro_objeto\n"

#: syntax_errors\message_analyzer.py:149
msgid ""
"On the left-hand side of an equal sign, you have a\n"
"conditional expression instead of the name of a variable.\n"
"    {expression} = ...\n"
"    {mark}\n"
msgstr ""
"En el lado izquierdo de un signo igual, tiene una expresión generadora\n"
"en lugar del nombre de una variable.\n"
"    {expression} = ...\n"
"    {mark}\n"

#: syntax_errors\message_analyzer.py:170
msgid ""
"On the left-hand side of an equal sign, you have\n"
"an expression instead of the name of a variable.\n"
msgstr ""
"En el lado izquierdo de un signo igual, tiene\n"
"una expresión en lugar del nombre de una variable.\n"

#: syntax_errors\message_analyzer.py:195
msgid ""
"You wrote the expression\n"
"\n"
"    {fn_call} = ...\n"
"where `{fn_call}`, on the left-hand side of the equal sign, either is\n"
"or includes a function call and is not simply the name of a variable.\n"
msgstr ""
"Has escrito una expresión como\n"
"\n"
"    {fn_call} = ...\n"
"\n"
"donde `{fn_call}`, a la izquierda del signo igual, es\n"
"o incluye una llamada a una función y no es simplemente el nombre de una "
"variable.\n"

#: syntax_errors\message_analyzer.py:207
msgid ""
"You wrote the expression\n"
"\n"
"    {fn_call} = ...\n"
"    {mark}\n"
"where `{fn_call}`, on the left-hand side of the equal sign, either is\n"
"or includes a function call and is not simply the name of a variable.\n"
msgstr ""
"Has escrito una expresión como\n"
"\n"
"    {fn_call} = ...\n"
"    {mark}\n"
"\n"
"donde `{fn_call}`, a la izquierda del signo igual, es\n"
"o incluye una llamada a una función y no es simplemente el nombre de una "
"variable.\n"

#: syntax_errors\message_analyzer.py:228
msgid ""
"On the left-hand side of an equal sign, you have a\n"
"generator expression instead of the name of a variable.\n"
msgstr ""
"En el lado izquierdo de un signo igual, tiene una expresión generadora\n"
"en lugar del nombre de una variable.\n"

#: syntax_errors\message_analyzer.py:246 syntax_errors\message_analyzer.py:372
msgid ""
"You wrote an expression that has the f-string `{fstring}`\n"
"on the left-hand side of the equal sign.\n"
"An f-string should only appear on the right-hand side of an equal sign.\n"
msgstr ""
"Has escrito una expresión que tiene la f-string `{fstring}`` en el lado "
"izquierdo del signo igual\n"
"en el lado izquierdo del signo igual.\n"
"Una f-string sólo debe aparecer en el lado derecho de un signo igual.\n"

#: syntax_errors\message_analyzer.py:290 syntax_errors\message_analyzer.py:1018
msgid "You cannot assign a value to `{keyword}`.\n"
msgstr "No se puede asignar un valor a `{keyword}`.\n"

#: syntax_errors\message_analyzer.py:293
msgid "You cannot assign a value to the ellipsis symbol [`...`].\n"
msgstr "No se puede asignar un valor al símbolo de elipsis [`...`].\n"

#: syntax_errors\message_analyzer.py:294
msgid ""
"The ellipsis symbol `...` is a constant in Python;you cannot assign it a "
"different value.\n"
msgstr ""
"El símbolo de la elipsis `...` es una constante en Python; no se le puede "
"asignar un valor diferente.\n"

#: syntax_errors\message_analyzer.py:299
msgid ""
"`{keyword}` is a constant in Python; you cannot assign it a different "
"value.\n"
msgstr ""
"{keyword}` es una constante en Python; no puedes asignarle un valor "
"diferente.\n"

#: syntax_errors\message_analyzer.py:304
#: syntax_errors\statement_analyzer.py:1021
msgid ""
"You were trying to assign a value to the Python keyword `{keyword}`.\n"
"This is not allowed.\n"
"\n"
msgstr ""
"Has intentado asignar un valor a la palabra clave de Python `{keyword}`.\n"
"Esto no está permitido.\n"
"\n"

#: syntax_errors\message_analyzer.py:324
msgid ""
"A for loop must have the form:\n"
"\n"
"    for ... in sequence:\n"
"\n"
"where `...` must contain only identifiers (variable names)\n"
"and not literals like `{bad_token}`.\n"
msgstr ""
"Un bucle for debe tener la forma\n"
"\n"
"    for ... in secuencia:\n"
"\n"
"donde `...` debe contener sólo identificadores (nombres de variables)\n"
"y no literales como `{bad_token}`.\n"

#: syntax_errors\message_analyzer.py:381
msgid "variable_name"
msgstr "nombre_de_variable"

#: syntax_errors\message_analyzer.py:385
msgid ""
"Perhaps you meant to write:\n"
"\n"
"    {name} = {literal}\n"
"\n"
msgstr ""
"Tal vez querías escribir:\n"
"\n"
"    {name} = {literal}\n"
"\n"

#: syntax_errors\message_analyzer.py:391
msgid "Perhaps you meant to write `{name} = {literal}`"
msgstr "Tal vez querías escribir `{name} = {literal}`"

#: syntax_errors\message_analyzer.py:410
msgid ""
"You wrote an expression like\n"
"\n"
"    {literal} = {name}\n"
"where `{literal}`, on the left-hand side of the equal sign,\n"
"is or includes an actual object {of_type}\n"
"and is not simply the name of a variable.\n"
msgstr ""
"Has escrito una expresión como\n"
"\n"
"    {literal} = {name}\n"
"donde `{literal}`, a la izquierda del signo de igualdad\n"
"es o incluye un objeto real {of_type}\n"
"y no es simplemente el nombre de una variable.\n"

#: syntax_errors\message_analyzer.py:420
msgid ""
"It is possible that you used an equal sign `=` instead of a colon `:`\n"
"to assign values to keys in a dict.\n"
msgstr ""
"Es posible que haya utilizado un signo igual `=` en lugar de dos puntos `:`\n"
"para asignar valores a las claves de un dict.\n"

#: syntax_errors\message_analyzer.py:438
msgid ""
"You wrote an expression that includes some mathematical operations\n"
"on the left-hand side of the equal sign which should be\n"
"only used to assign a value to a variable.\n"
msgstr ""
"Has escrito una expresión que incluye algunas operaciones matemáticas\n"
"en el lado izquierdo del signo igual que debería ser\n"
"sólo utilizarse para asignar un valor a una variable.\n"

#: syntax_errors\message_analyzer.py:460
msgid "Perhaps you meant to write `{name}` instead of `{original}`\n"
msgstr "Tal vez quiso escribir `{name}` en lugar de `{original}`.\n"

#: syntax_errors\message_analyzer.py:465 syntax_errors\message_analyzer.py:603
#: syntax_errors\statement_analyzer.py:607
msgid "Perhaps you needed `==` instead of `=`.\n"
msgstr "Tal vez necesitabas `==` en lugar de `=`.\n"

#: syntax_errors\message_analyzer.py:477
msgid ""
"You wrote an expression that includes the `yield` keyword\n"
"on the left-hand side of the equal sign.\n"
"You cannot assign a value to such an expression.\n"
"Note that, like the keyword `return`,\n"
"`yield` can only be used inside a function.\n"
msgstr ""
"Ha escrito una expresión que incluye la palabra clave `yield\n"
"a la izquierda del signo igual.\n"
"No se puede asignar un valor a una expresión de este tipo.\n"
"Tenga en cuenta que, al igual que la palabra clave `return`,\n"
"`yield` sólo puede usarse dentro de una función.\n"

#: syntax_errors\message_analyzer.py:496 syntax_errors\message_analyzer.py:518
msgid ""
"You are using the augmented assignment operator `:=` inside\n"
"a comprehension to assign a value to the iteration variable `{var}`.\n"
"This variable is meant to be used only inside the comprehension.\n"
"The augmented assignment operator is normally used to assign a value\n"
"to a variable so that the variable can be reused later.\n"
"This is not possible for variable `{var}`.\n"
msgstr ""
"Está utilizando el operador de asignación aumentada `:=` dentro de\n"
"una comprensión para asignar un valor a la variable de iteración `{var}`.\n"
"Esta variable está pensada para ser empleada sólo dentro de la comprensión.\n"
"El operador de asignación aumentada se usa normalmente para asignar un "
"valor\n"
"a una variable para poder reutilizarla posteriormente.\n"
"Esto no es posible para la variable `{var}`.\n"

#: syntax_errors\message_analyzer.py:535
msgid ""
"The object named `{name}` is defined with type annotation\n"
"as a local variable. It cannot be declared to be a global variable.\n"
msgstr ""
"El objeto llamado `{name}` se define con la anotación de tipo\n"
"como una variable local. No se puede declarar como una variable global.\n"

#: syntax_errors\message_analyzer.py:550
msgid ""
"You cannot use the augmented assignment operator `:=`,\n"
"sometimes called the walrus operator, with literals like `{bad_token}`.\n"
"You can only assign objects to identifiers (variable names).\n"
msgstr ""
"No se puede utilizar el operador de asignación aumentada `:=`,\n"
"a veces llamado operador morsa, con literales como `{bad_token}`.\n"
"Sólo se pueden asignar objetos a identificadores (nombres de variables).\n"

#: syntax_errors\message_analyzer.py:561
msgid ""
"You declared `{name}` as being both a global and nonlocal variable.\n"
"A variable can be global, or nonlocal, but not both at the same time.\n"
msgstr ""
"Has declarado que {name}` es una variable global y no local.\n"
"Una variable puede ser global o no local, pero no ambas cosas a la vez.\n"

#: syntax_errors\message_analyzer.py:576
msgid "Python tells us that the {bracket} was never closed.\n"
msgstr "Python nos dice que el {bracket} nunca fue cerrado.\n"

#: syntax_errors\message_analyzer.py:579
msgid "The {bracket} was never closed.\n"
msgstr "El {bracket} nunca fue cerrado.\n"

#: syntax_errors\message_analyzer.py:591
msgid ""
"The Python keyword `break` can only be used inside a `for` loop or inside a "
"`while` loop.\n"
msgstr ""
"La palabra clave de Python `break` sólo puede utilizarse dentro de un bucle "
"`for` o dentro de un bucle `while`.\n"

#: syntax_errors\message_analyzer.py:604
#: syntax_errors\statement_analyzer.py:608
msgid ""
"You likely used an assignment operator `=` instead of an equality operator "
"`==`.\n"
msgstr ""
"Es probable que hayas utilizado un operador de asignación `=` en lugar de un "
"operador de igualdad `==`.\n"

#: syntax_errors\message_analyzer.py:612
msgid ""
"The following statement would not contain a syntax error:\n"
"\n"
"    {new_statement}\n"
msgstr ""
"La siguiente sentencia no contendría un error de sintaxis:\n"
"\n"
"    {new_statement}\n"

#: syntax_errors\message_analyzer.py:632
msgid "You cannot delete the constant `{constant}`.\n"
msgstr "No se puede eliminar la constante `{constant}`.\n"

#: syntax_errors\message_analyzer.py:652 syntax_errors\message_analyzer.py:706
msgid "You cannot delete a Python expression.\n"
msgstr "No se puede borrar una expresión de Python.\n"

#: syntax_errors\message_analyzer.py:655
msgid "You cannot delete the expression `{expression}`.\n"
msgstr "No se puede eliminar la expresión `{expression}`.\n"

#: syntax_errors\message_analyzer.py:672
msgid ""
"You attempted to delete a function call\n"
"\n"
"    {line}\n"
"instead of deleting the function's name\n"
"\n"
"    {correct}\n"
msgstr ""
"Has intentado borrar una llamada a una función\n"
"\n"
"    {line}\n"
"en lugar de borrar el nombre de la función\n"
"\n"
"    {correct}\n"

#: syntax_errors\message_analyzer.py:690
msgid "You cannot delete the literal `{literal}`.\n"
msgstr "No se puede eliminar el literal `{literal}`.\n"

#: syntax_errors\message_analyzer.py:709
msgid "You cannot delete the named expression `{expression}`.\n"
msgstr "No se puede eliminar la expresión con nombre `{expression}`.\n"

#: syntax_errors\message_analyzer.py:725
msgid ""
"The star operator `*` is interpreted to mean that\n"
"iterable unpacking is to be used to assign a name\n"
"to each item of an iterable, which does not make sense here.\n"
msgstr ""
"El operador estrella `*` se interpreta como que\n"
"el desempaquetado de un iterable debe ser usado para asignar un nombre\n"
"a cada elemento de un iterable, lo que no tiene sentido aquí.\n"

#: syntax_errors\message_analyzer.py:739
msgid ""
"It looks like you surrounded a starred name by parentheses.\n"
"This was not considered a SyntaxError before Python version 3.9.\n"
msgstr ""
"Parece que has rodeado un nombre con asteriscos con paréntesis.\n"
"Esto no se consideraba un SyntaxError antes de la versión 3.9 de Python.\n"

#: syntax_errors\message_analyzer.py:758
msgid "Did you forget a colon?\n"
msgstr "¿Olvidaste los dos puntos?\n"

#: syntax_errors\message_analyzer.py:759
msgid "Python expected a colon at the position indicated.\n"
msgstr "Python esperaba dos puntos en la posición indicada.\n"

#: syntax_errors\message_analyzer.py:787
msgid ""
"It looks like the error occurred as you were writing a Python dict.\n"
"Perhaps you wrote a dict key without writing the corresponding value.\n"
msgstr ""
"Parece que el error se produjo mientras escribías un dict de Python.\n"
"Quizás escribiste una clave de dict sin escribir el valor correspondiente.\n"

#: syntax_errors\message_analyzer.py:791 syntax_errors\message_analyzer.py:1049
#: syntax_errors\statement_analyzer.py:1725
msgid "Did you forget to write a dict value?\n"
msgstr "¿Olvidaste escribir el valor del dict?\n"

#: syntax_errors\message_analyzer.py:798
msgid ""
"The Python keyword `continue` can only be used inside a `for` loop or inside "
"a `while` loop.\n"
msgstr ""
"La palabra clave de Python `continue` sólo puede usarse dentro de un bucle "
"`for` o dentro de un bucle `while`.\n"

#: syntax_errors\message_analyzer.py:810
msgid ""
"You have defined a function repeating the argument\n"
"\n"
"    {name}\n"
"Each argument should appear only once in a function definition.\n"
msgstr ""
"Ha definido una función que repite el argumento\n"
"\n"
"    {name}\n"
"Cada argumento debe aparecer sólo una vez en la definición de una función.\n"

#: syntax_errors\message_analyzer.py:850
msgid "Did you forget to add `else`?\n"
msgstr "¿Olvidaste añadir `else`?\n"

#: syntax_errors\message_analyzer.py:851
msgid "An `else some_value` clause was expected after the `if` expression.\n"
msgstr ""
"Se esperaba una cláusula `else algún_valor` después de la expresión `if`.\n"

#: syntax_errors\message_analyzer.py:863
msgid ""
"You started writing a triple-quoted string but never wrote\n"
"the triple quotes needed to end the string.\n"
msgstr ""
"Empezó a escribir una cadena con comillas triples pero nunca escribió\n"
"las comillas triples necesarias para terminar la cadena.\n"

#: syntax_errors\message_analyzer.py:880
msgid "Did you forget a closing quote?\n"
msgstr "¿Olvidaste la comilla de cierre?\n"

#: syntax_errors\message_analyzer.py:881
msgid ""
"You started writing a string with a single or double quote\n"
"but never ended the string with another quote on that line.\n"
msgstr ""
"Ha empezado a escribir una cadena con una comilla simple o doble\n"
"pero nunca terminó la cadena con otra comilla en esa línea.\n"

#: syntax_errors\message_analyzer.py:894
msgid ""
"Perhaps you meant to write the backslash character, `\\`\n"
"as the last character in the string and forgot that you\n"
"needed to escape it by writing two `\\` in a row.\n"
msgstr ""
"Tal vez quiso escribir el carácter de la barra diagonal inversa, `\\`\n"
"como el último carácter de la cadena y se olvidó de que\n"
"que necesitaba escapar escribiendo dos `\\` seguidas.\n"

#: syntax_errors\message_analyzer.py:899
msgid "Did you forget to escape a backslash character?\n"
msgstr "¿Olvidaste escapar un carácter de barra invertida?\n"

#: syntax_errors\message_analyzer.py:934
#: syntax_errors\statement_analyzer.py:375
msgid "Perhaps you forgot to escape a quote character.\n"
msgstr ""

#: syntax_errors\message_analyzer.py:935
#: syntax_errors\statement_analyzer.py:376
msgid ""
"I suspect that you were trying to use a quote character inside a string\n"
"that was enclosed in quotes of the same kind.\n"
"Perhaps you should have escaped the inner quote character:\n"
"\n"
"    {new_line}\n"
"    {mark}\n"
msgstr ""

#: syntax_errors\message_analyzer.py:950
msgid ""
"You wrote a `try` block which did not include an `except` nor a `finally` "
"block.\n"
msgstr ""

#: syntax_errors\message_analyzer.py:965 syntax_errors\message_analyzer.py:982
#, fuzzy
#| msgid ""
#| "Perhaps you meant to write\n"
#| "\n"
#| "`{new_statement}`\n"
msgid ""
"Perhaps you meant to write\n"
"\n"
"    {new_statement}"
msgstr ""
"Quizás quisiste escribir\n"
"\n"
"`{new_statement}`\n"

#: syntax_errors\message_analyzer.py:968 syntax_errors\message_analyzer.py:985
#, fuzzy
#| msgid "Did you mean `{name}`?\n"
msgid "Did you mean `{new_statement}`?"
msgstr "¿Quieres decir `{name}`?\n"

#: syntax_errors\message_analyzer.py:975
#, fuzzy
#| msgid ""
#| "Perhaps you meant to write\n"
#| "\n"
#| "`{new_statement}`\n"
msgid ""
"Perhaps you meant to write either\n"
"\n"
"    {new_statement}\n"
"\n"
"or\n"
"\n"
"    {new_statement2}"
msgstr ""
"Quizás quisiste escribir\n"
"\n"
"`{new_statement}`\n"

#: syntax_errors\message_analyzer.py:1020
msgid ""
"You likely called a function using the Python keyword `{keyword}` as an "
"argument:\n"
"\n"
"    a_function({keyword}=something) \n"
"\n"
"which Python interpreted as trying to assign a value to a Python keyword.\n"
"\n"
msgstr ""
"Es probable que hayas llamado a una función utilizando la palabra clave de "
"Python `{keyword}` como argumento:\n"
"\n"
"    una_function({keyword}=algo) \n"
"\n"
"que Python interpretó como un intento de asignar un valor a una palabra "
"clave de Python.\n"
"\n"

#: syntax_errors\message_analyzer.py:1031
msgid ""
"You likely called a function with a named argument:\n"
"\n"
"    a_function(invalid=something) \n"
"\n"
"where `invalid` is not a valid variable name in Python\n"
"either because it starts with a number, or is a string,\n"
"or contains a period, etc.\n"
msgstr ""
"Es probable que hayas llamado a una función con un argumento con nombre:\n"
"\n"
"    unaa_función(inválido=algo) \n"
"\n"
"donde `inválido` no es un nombre de variable válido en Python\n"
"ya sea porque comienza con un número, o es una cadena\n"
"o contiene un punto, etc.\n"

#: syntax_errors\message_analyzer.py:1045
#: syntax_errors\statement_analyzer.py:1716
msgid ""
"It looks like the error occurred as you were writing a Python dict.\n"
"Perhaps you forgot to write a value after a colon.\n"
msgstr ""
"Parece que el error se produjo mientras escribías un dict de Python.\n"
"Tal vez se olvidó de escribir un valor después de dos puntos.\n"

#: syntax_errors\message_analyzer.py:1058
msgid ""
"You have written an f-string whose content `{...}`\n"
"includes a backslash; this is not allowed.\n"
"Perhaps you can replace the part that contains a backslash by\n"
"some variable. For example, suppose that you have an f-string like:\n"
"\n"
"    f\"{... 'hello\\n' ...}\"\n"
"\n"
"you could write this as\n"
"\n"
"    hello = 'hello\\n'\n"
"    f\"{... hello ...}\"\n"
msgstr ""
"Ha escrito una f-string cuyo contenido `{...}`\n"
"incluye una barra invertida; esto no está permitido.\n"
"Tal vez pueda sustituir la parte que contiene una barra invertida por\n"
"alguna variable. Por ejemplo, suponga que tiene una f-string como:\n"
"\n"
"    f\"{... 'hola\\n' ...}\"\n"
"\n"
"podría escribirla como\n"
"\n"
"    hola = 'hola\\n'\n"
"    f\"{... hola ...}\"\n"

#: syntax_errors\message_analyzer.py:1075
msgid ""
"You have written an f-string which has an unmatched `}`.\n"
"If you want to print a single `}`, you need to write `}}` in the f-string;\n"
"otherwise, you need to add an opening `{`.\n"
msgstr ""
"Has escrito una f-string que tiene un `}` sin emparejar.\n"
"Si quieres imprimir un solo `}`, tienes que escribir `}}` en la f-string;\n"
"de lo contrario, es necesario añadir una apertura `{`.\n"

#: syntax_errors\message_analyzer.py:1087
msgid ""
"You have written an f-string which has an unmatched `{`.\n"
"If you want to print a single `{`, you need to write `{{` in the f-string;\n"
"otherwise, you need to add a closing `}`.\n"
msgstr ""
"Has escrito una f-string que tiene un `{` sin emparejar.\n"
"Si quieres imprimir un solo `{`, tienes que escribir `{{` en la f-string;\n"
"de lo contrario, es necesario añadir un cierre `}`.\n"

#: syntax_errors\message_analyzer.py:1103
#: syntax_errors\statement_analyzer.py:1284
msgid ""
"I am guessing that you were writing a comprehension or a generator "
"expression\n"
"and forgot to include parentheses around tuples.\n"
"As an example, instead of writing\n"
"\n"
"    [i, i**2 for i in range(10)]\n"
"\n"
"you would need to write\n"
"\n"
"    [(i, i**2) for i in range(10)]\n"
"\n"
msgstr ""
"Supongo que estabas escribiendo una expresión de comprensión o un generador\n"
"y olvidaste incluir paréntesis alrededor de las tuplas.\n"
"Como ejemplo, en lugar de escribir\n"
"\n"
"    [i, i**2 for i in range(10)]\n"
"\n"
"tendrías que escribir\n"
"\n"
"    [(i, i**2) for i in range(10)]\n"
"\n"

#: syntax_errors\message_analyzer.py:1120
msgid ""
"A `from __future__ import` statement changes the way Python\n"
"interprets the code in a file.\n"
"It must appear at the beginning of the file."
msgstr ""
"Una sentencia `from __future__ import` cambia la forma en que Python\n"
"interpreta el código de un archivo.\n"
"Debe aparecer al principio del archivo."

#: syntax_errors\message_analyzer.py:1136
msgid "The available features are `{names}`.\n"
msgstr "Las características disponibles son `{names}`.\n"

#: syntax_errors\message_analyzer.py:1141
msgid ""
"When using a `from __future__ import` statement,\n"
"you must import specific named features.\n"
msgstr ""
"Cuando se utiliza una sentencia `from __future__ import`,\n"
"debe importar características específicas por su nombre.\n"

#: syntax_errors\message_analyzer.py:1152
msgid "Instead of `{feature}`, perhaps you meant to import `{name}`.\n"
msgstr "En lugar de `{feature}`, tal vez querías importar `{name}`.\n"

#: syntax_errors\message_analyzer.py:1157
msgid "`{feature}` is not a valid feature of module `__future__`.\n"
msgstr "`{feature}` no es una característica válida del módulo `__future__`.\n"

#: syntax_errors\message_analyzer.py:1182
msgid ""
"You are using a generator expression, something of the form\n"
"\n"
"    x for x in thing\n"
"\n"
"You must add parentheses enclosing that expression.\n"
msgstr ""
"Estás usando una expresión generadora, algo de la forma\n"
"\n"
"    x for x in cosa\n"
"\n"
"Debes añadir paréntesis encerrando esa expresión.\n"

#: syntax_errors\message_analyzer.py:1195
msgid ""
"I suspect you wrote `from __future__ import braces` following\n"
"someone else's suggestion. This will never work.\n"
"\n"
"Unlike other programming languages, Python's code block are defined by\n"
"their indentation level, and not by using some curly braces, like `{...}`.\n"
msgstr ""
"Sospecho que has escrito `de __future__ import braces` siguiendo\n"
"la sugerencia de otra persona. Esto nunca funcionará.\n"
"\n"
"A diferencia de otros lenguajes de programación, los bloques de código de "
"Python se definen por\n"
"su nivel de indentación, y no por el uso de algunas llaves, como `{...}`.\n"

#: syntax_errors\message_analyzer.py:1210
#: syntax_errors\statement_analyzer.py:190
msgid "Did you use copy-paste?\n"
msgstr "¿Usaste copiar y pegar?\n"

#: syntax_errors\message_analyzer.py:1211
msgid ""
"Python indicates that you used the unicode character `{bad_character}`\n"
"which is not allowed.\n"
msgstr ""
"Python indica que has utilizado el carácter unicode `{bad_character}`\n"
"que no está permitido.\n"

#: syntax_errors\message_analyzer.py:1237
msgid "Python tells us that you have written an invalid number."
msgstr "Python nos dice que has escrito un número no válido."

#: syntax_errors\message_analyzer.py:1238
msgid "However, I think that the problem might be the following."
msgstr "Sin embargo, creo que el problema puede ser el siguiente."

#: syntax_errors\message_analyzer.py:1272
msgid "I have no suggestion to offer to fix this problem.\n"
msgstr "No tengo una sugerencia para arreglar este problema.\n"

#: syntax_errors\message_analyzer.py:1281
#: syntax_errors\statement_analyzer.py:740
msgid ""
"The double star operator `**` is likely interpreted to mean that\n"
"dict unpacking is to be used which is not allowed or does not make sense "
"here.\n"
msgstr ""
"El operador de doble estrella `**` probablemente se interpreta como que\n"
"que se va a utilizar el desempaquetado del dictado, lo cual no está "
"permitido o no tiene sentido en este caso.\n"

#: syntax_errors\message_analyzer.py:1339
msgid ""
"You cannot use the `*` operator to unpack the iteration variable\n"
"in a comprehension.\n"
msgstr ""
"No se puede utilizar el operador `*` para descomponer la variable de "
"iteración\n"
"en una comprensión.\n"

#: syntax_errors\message_analyzer.py:1351
#: syntax_errors\message_analyzer.py:1741
#: syntax_errors\statement_analyzer.py:524
msgid ""
"The following statement has no syntax error:\n"
"\n"
"    {statement}\n"
msgstr ""
"La siguiente declaración no tiene ningún error de sintaxis:\n"
"\n"
"    {statement}\n"

#: syntax_errors\message_analyzer.py:1372
msgid ""
"You have called a function repeating the same keyword argument (`{arg}`).\n"
"Each keyword argument should appear only once in a function call.\n"
msgstr ""
"Ha llamado a una función repitiendo el mismo argumento de palabra clave "
"(`{arg}`).\n"
"Cada argumento de palabra clave debe aparecer sólo una vez en una llamada a "
"una función.\n"

#: syntax_errors\message_analyzer.py:1435
msgid ""
"Python tells us that the closing `{closing}` on the last line shown\n"
"does not match the opening `{opening}` on line {lineno}.\n"
"\n"
msgstr ""
"Python nos dice que el cierre `{closing}` de la última línea mostrada\n"
"no coincide con la apertura `{opening}` de la línea {lineno}.\n"
"\n"

#: syntax_errors\message_analyzer.py:1440
msgid ""
"Python tells us that the closing `{closing}` on the last line shown\n"
"does not match the opening `{opening}`.\n"
"\n"
msgstr ""
"Python nos dice que el cierre `{closing}` de la última línea mostrada\n"
"no coincide con la apertura `{opening}`.\n"
"\n"

#: syntax_errors\message_analyzer.py:1454
msgid "Did you forget something after `*`?\n"
msgstr "¿Olvidaste algo después de `*`?\n"

#: syntax_errors\message_analyzer.py:1455
msgid ""
"Assuming you were defining a function, you need\n"
"to replace `*` by either `*arguments` or\n"
"by `*, named_argument=value`.\n"
msgstr ""
"Asumiendo que estabas definiendo una función, necesitas\n"
"sustituir `*` por `*argumentos` o\n"
"por `*, argumento_nombrado=valor`.\n"

#: syntax_errors\message_analyzer.py:1470
msgid ""
"You assigned a value to the variable `{name}`\n"
"before declaring it as a global variable.\n"
msgstr ""
"Usted asignó un valor a la variable `{name}`.\n"
"antes de declararla como variable global.\n"

#: syntax_errors\message_analyzer.py:1494
msgid "Did you forget to add `nonlocal`?\n"
msgstr "¿Olvidó añadir `nonlocal`?\n"

#: syntax_errors\message_analyzer.py:1495
msgid ""
"You assigned a value to the variable `{name}`\n"
"before declaring it as a nonlocal variable.\n"
msgstr ""
"Ha asignado un valor a la variable `{name}`\n"
"antes de declararla como variable no local.\n"

#: syntax_errors\message_analyzer.py:1526
msgid ""
"You are including the statement\n"
"\n"
"    {newline}\n"
"\n"
"indicating that `{name}` is a variable defined outside a function.\n"
"You are also using the same `{name}` as an argument for that\n"
"function, thus indicating that it should be variable known only\n"
"inside that function, which is the contrary of what `global` implied.\n"
msgstr ""
"Usted está incluyendo la declaración\n"
"\n"
"    {newline}\n"
"\n"
"indicando que `{name}` es una variable definida fuera de una función.\n"
"También está utilizando el mismo `{name}` como argumento para esa\n"
"función, indicando así que debe ser una variable conocida sólo\n"
"dentro de esa función, que es lo contrario de lo que implica `global`.\n"

#: syntax_errors\message_analyzer.py:1543
msgid ""
"You used `{name}` as a parameter for a function\n"
"before declaring it also as a nonlocal variable:\n"
"`{name}` cannot be both at the same time.\n"
msgstr ""
"Ha utilizado `{name}` como parámetro de una función\n"
"antes de declararla también como variable no local:\n"
"{name}` no puede ser ambas cosas a la vez.\n"

#: syntax_errors\message_analyzer.py:1558
msgid ""
"You used the variable `{name}`\n"
"before declaring it as a global variable.\n"
msgstr ""
"Ha utilizado la variable `{name}`\n"
"antes de declararla como variable global.\n"

#: syntax_errors\message_analyzer.py:1581
msgid "Did you forget to write `nonlocal` first?\n"
msgstr "¿Olvidó escribir primero `nonlocal`?\n"

#: syntax_errors\message_analyzer.py:1583
msgid ""
"You used the variable `{name}`\n"
"before declaring it as a nonlocal variable.\n"
msgstr ""
"Ha utilizado la variable `{name}`\n"
"antes de declararla como variable no local.\n"

#: syntax_errors\message_analyzer.py:1607
msgid ""
"You declared the variable `{name}` as being a\n"
"nonlocal variable but it cannot be found.\n"
msgstr ""
"Ha declarado la variable `{name}` como una variable\n"
"variable no local, pero no se puede encontrar.\n"

#: syntax_errors\message_analyzer.py:1618
msgid ""
"You used the nonlocal keyword at a module level.\n"
"The nonlocal keyword refers to a variable inside a function\n"
"given a value outside that function."
msgstr ""
"Ha utilizado la palabra clave nonlocal a nivel de módulo.\n"
"La palabra clave nonlocal se refiere a una variable dentro de una función\n"
"con un valor fuera de esa función."

#: syntax_errors\message_analyzer.py:1630
msgid ""
"In Python, you can define functions with only positional arguments\n"
"\n"
"    def test(a, b, c): ...\n"
"\n"
"or only keyword arguments\n"
"\n"
"    def test(a=1, b=2, c=3): ...\n"
"\n"
"or a combination of the two\n"
"\n"
"    def test(a, b, c=3): ...\n"
"\n"
"but with the keyword arguments appearing after all the positional ones.\n"
"According to Python, you used positional arguments after keyword ones.\n"
msgstr ""
"En Python, puedes definir funciones con sólo argumentos posicionales\n"
"\n"
"    def prueba(a, b, c): ...\n"
"\n"
"o sólo con argumentos de palabra clave\n"
"\n"
"    def prueba(a=1, b=2, c=3): ...\n"
"\n"
"o una combinación de ambos\n"
"\n"
"    def prueba(a, b, c=3): ...\n"
"\n"
"pero con los argumentos de palabra clave apareciendo después de todos los "
"posicionales.\n"
"Según Python, has utilizado argumentos posicionales después de los de "
"palabra clave.\n"

#: syntax_errors\message_analyzer.py:1650
#: syntax_errors\statement_analyzer.py:1332
msgid ""
"I am guessing that you wanted to use an `except` statement\n"
"with multiple exception types. If that is the case, you must\n"
"surround them with parentheses.\n"
msgstr ""
"Supongo que querías usar una sentencia `except`\n"
"con múltiples tipos de excepción. Si ese es el caso, debes\n"
"rodearlas con paréntesis.\n"

#: syntax_errors\message_analyzer.py:1662
msgid ""
"In Python, you can call functions with only positional arguments\n"
"\n"
"    test(1, 2, 3)\n"
"\n"
"or only keyword arguments\n"
"\n"
"    test(a=1, b=2, c=3)\n"
"\n"
"or a combination of the two\n"
"\n"
"    test(1, 2, c=3)\n"
"\n"
"but with the keyword arguments appearing after all the positional ones.\n"
"According to Python, you used positional arguments after keyword ones.\n"
msgstr ""
"En Python, pueden llamar a las funciones solo con argumentos posicionales\n"
"\n"
"    prueba(1, 2, 3)\n"
"\n"
"o sólo con argumentos de palabra clave\n"
"\n"
"    prueba(a=1, b=2, c=3)\n"
"\n"
"o una combinación de ambos\n"
"\n"
"    prueba(1, 2, c=3)\n"
"\n"
"pero con los argumentos de palabra clave que aparecen después de los "
"posicionales.\n"
"Según Python, has utilizado argumentos posicionales después de los de "
"palabra clave.\n"

#: syntax_errors\message_analyzer.py:1689
#: syntax_errors\statement_analyzer.py:658
msgid ""
"Perhaps you need to type\n"
"\n"
"     print({message})\n"
"\n"
"In older version of Python, `print` was a keyword.\n"
"Now, `print` is a function; you need to use parentheses to call it.\n"
msgstr ""
"Tal vez tenga que escribir\n"
"\n"
"     print({message})\n"
"\n"
"En la versión anterior de Python, `print` era una palabra clave.\n"
"Ahora, `print` es una función por lo que es necesario usar paréntesis para "
"llamarla.\n"

#: syntax_errors\message_analyzer.py:1696
#: syntax_errors\statement_analyzer.py:665
msgid "Note that arguments of `print` must be separated by commas.\n"
msgstr ""
"Tenga en cuenta que los argumentos de `print` deben estar separados por "
"comas.\n"

#: syntax_errors\message_analyzer.py:1697
#: syntax_errors\statement_analyzer.py:666
msgid "Did you mean `print({message})`?\n"
msgstr "¿Quieres decir `print({message})`?\n"

#: syntax_errors\message_analyzer.py:1706
msgid "You can only use a `return` statement inside a function or method.\n"
msgstr ""
"Sólo se puede utilizar una sentencia `return` dentro de una función o "
"método.\n"

#: syntax_errors\message_analyzer.py:1715
msgid ""
"A star assignment must be of the form:\n"
"\n"
"    ... *name = list_or_tuple\n"
"\n"
msgstr ""
"Una asignación estrella debe ser de la forma:\n"
"\n"
"    ... *nombre = lista_o_tupla\n"
"\n"

#: syntax_errors\message_analyzer.py:1725
msgid ""
"It looks like you tried to use a starred expression as a dict value;\n"
"this is not allowed.\n"
msgstr ""
"Parece que has intentado utilizar una expresión con asteriscos como valor de "
"dict;\n"
"esto no está permitido.\n"

#: syntax_errors\message_analyzer.py:1752
msgid ""
"Your code is too complex for Python:\n"
"you need to reduce the number of indented code blocks\n"
"contained inside other code blocks.\n"
msgstr ""
"Tu código es demasiado complejo para Python:\n"
"necesitas reducir el número de bloques de código con sangría\n"
"contenidos dentro de otros bloques de código.\n"

#: syntax_errors\message_analyzer.py:1765
msgid ""
"Your code is too complex for Python:\n"
"you need to reduce the number of parentheses\n"
"contained inside other parentheses.\n"
msgstr ""
"Tu código es demasiado complejo para Python:\n"
"necesitas reducir el número de paréntesis\n"
"contenidos dentro de otros paréntesis.\n"

#: syntax_errors\message_analyzer.py:1780
msgid ""
"Python indicates that you need to surround an expression\n"
"ending with a comma by parentheses.\n"
msgstr ""
"Python indica que hay que rodear una expresión\n"
"que termina con una coma por medio de paréntesis.\n"

#: syntax_errors\message_analyzer.py:1784
msgid ""
"I have no additional suggestion to offer.\n"
"Please feel free to report this case.\n"
msgstr ""
"No tengo ninguna sugerencia adicional que ofrecer.\n"
"Por favor, siéntase libre de reportar este caso.\n"

#: syntax_errors\message_analyzer.py:1794
msgid ""
"Perhaps you meant to write\n"
"\n"
"`{new_statement}`\n"
msgstr ""
"Quizás quisiste escribir\n"
"\n"
"`{new_statement}`\n"

#: syntax_errors\message_analyzer.py:1802
msgid "However, I suspect that you wrote the keyword `{boolean}` by mistake.\n"
msgstr ""
"Sin embargo, sospecho que has escrito la palabra clave `{boolean}` por "
"error.\n"

#: syntax_errors\message_analyzer.py:1806
msgid ""
"The Python keyword `{boolean}` can only be used for boolean expressions.\n"
msgstr ""
"La palabra clave de Python `{boolean}` sólo puede utilizarse para "
"expresiones booleanas.\n"

#: syntax_errors\message_analyzer.py:1818
#: syntax_errors\message_analyzer.py:1831
msgid "However, if you remove the last comma, there will be no syntax error.\n"
msgstr ""
"Sin embargo, si eliminas la última coma, no habrá ningún error de sintaxis.\n"

#: syntax_errors\message_analyzer.py:1846
msgid ""
"You are using the continuation character `\\` outside of a string,\n"
"and it is followed by some other character(s).\n"
msgstr ""
"Está utilizando el carácter de continuación `\\` fuera de una cadena\n"
"y es seguido por algún otro carácter(es).\n"

#: syntax_errors\message_analyzer.py:1869
msgid ""
"I am guessing that you wanted to divide by the number {number} \n"
"and wrote \\ instead of /."
msgstr ""
"Supongo que querías dividir por el número {number} \n"
"y escribió \\ en lugar de /."

#: syntax_errors\message_analyzer.py:1873
msgid "Did you mean to divide by {number}?\n"
msgstr "¿Querías dividir por {number}?\n"

#: syntax_errors\message_analyzer.py:1876
msgid "I am guessing that you forgot to enclose some content in a string.\n"
msgstr "Supongo que has olvidado encerrar algún contenido en una cadena.\n"

#: syntax_errors\message_analyzer.py:1885
msgid ""
"Python tells us that it reached the end of the file\n"
"and expected more content.\n"
"\n"
msgstr ""
"Python nos dice que llegó al final del archivo\n"
"y que esperaba más contenido.\n"
"\n"

#: syntax_errors\message_analyzer.py:1892
msgid ""
"I will attempt to be give a bit more information.\n"
"\n"
msgstr ""
"Intentaré dar un poco más de información.\n"
"\n"

#: syntax_errors\message_analyzer.py:1903
msgid ""
"I suspect that you wrote a string that contains\n"
"one backslash character, `\\` followed by an uppercase `U`\n"
"and some more characters.\n"
"Python likely interpreted this as indicating the beginning of\n"
"what is known as an escape sequence for special unicode characters.\n"
"To solve the problem, either write a so-called 'raw string'\n"
"by adding the letter `r` as a prefix in\n"
"front of the string, or replace `\\U`, by `\\\\U`.\n"
msgstr ""
"Sospecho que has escrito una cadena que contiene\n"
"un carácter de barra invertida, `\\` seguida de una `U` mayúscula\n"
"y algunos caracteres más.\n"
"Python probablemente interpretó esto como el comienzo de\n"
"lo que se conoce como una secuencia de escape para caracteres especiales "
"unicode.\n"
"Para resolver el problema, escriba la llamada 'cadena cruda'\n"
"añadiendo la letra `r` como prefijo en\n"
"delante de la cadena, o reemplazar `\\U`, por `\\\\U`.\n"

#: syntax_errors\message_analyzer.py:1927
#: syntax_errors\statement_analyzer.py:127
msgid "The closing {bracket} on line {linenumber} does not match anything.\n"
msgstr ""
"El {bracket} de cierre de la línea {linenumber} no coincide con nada.\n"

#: syntax_errors\message_analyzer.py:1938
msgid "Perhaps you forgot a closing quote.\n"
msgstr "Tal vez olvidó una comilla de cierre.\n"

#: syntax_errors\message_analyzer.py:1955
msgid ""
"Inside the f-string `{fstring}`, \n"
"you have another string, which starts with either a\n"
"single quote (') or double quote (\"), without a matching closing one.\n"
msgstr ""
"Dentro de la f-string `{fstring}`, \n"
"tiene otra cadena, que comienza con una\n"
"comillas simples (') o comillas dobles (\"), sin una comilla de cierre que "
"coincida.\n"

#: syntax_errors\message_analyzer.py:1968
msgid "You can only use a `yield` statement inside a function.\n"
msgstr "Sólo se puede utilizar una sentencia `yield` dentro de una función.\n"

#: syntax_errors\message_analyzer.py:1977
msgid ""
"This is a message that was added in Python 3.9\n"
"to prevent redefining `__peg_parser__`.\n"
"It should not be present in other versions.\n"
msgstr ""
"Este es un mensaje que se añadió en Python 3.9\n"
"para evitar la redefinición de `__peg_parser__`.\n"
"No debería estar presente en otras versiones.\n"

#: syntax_errors\message_analyzer.py:2039
msgid ""
"Friendly-traceback cannot identify the non-printable character.\n"
"This should not happen. Please report this case"
msgstr ""

#: syntax_errors\message_analyzer.py:2053
#: syntax_errors\statement_analyzer.py:107
msgid "Your code contains the invalid non-printable character {char}.\n"
msgstr ""

#: syntax_errors\statement_analyzer.py:162
msgid ""
"The closing {bracket} on line {close_lineno} does not match the opening "
"{open_bracket} on line {open_lineno}.\n"
msgstr ""
"El {bracket} de cierre de la línea {close_lineno} no coincide con el "
"{open_bracket} de apertura de la línea {open_lineno}.\n"

#: syntax_errors\statement_analyzer.py:184
msgid "Did you mean to write `...`?\n"
msgstr "¿Querías escribir `...`?\n"

#: syntax_errors\statement_analyzer.py:185
msgid ""
"It looks like you meant to write `...` but added an extra `.` by mistake.\n"
msgstr ""

#: syntax_errors\statement_analyzer.py:199
msgid ""
"It looks like you copy-pasted code from an interactive interpreter.\n"
"The Python prompt, `>>>`, should not be included in your code.\n"
msgstr ""
"Parece que has copiado y pegado código de un intérprete interactivo.\n"
"El prompt de Python, `>>>`, no debería estar incluido en tu código.\n"

#: syntax_errors\statement_analyzer.py:209
msgid ""
"It looks like you copy-pasted code from an interactive interpreter.\n"
"The Python prompt, `...`, should not be included in your code.\n"
msgstr ""
"Parece que has copiado y pegado código de un intérprete interactivo.\n"
"El prompt de Python, `...`, no debería estar incluido en tu código.\n"

#: syntax_errors\statement_analyzer.py:223
msgid "You should not use the backquote character.\n"
msgstr "No debe utilizar el carácter de retrocomilla.\n"

#: syntax_errors\statement_analyzer.py:224
msgid ""
"You are using the backquote character.\n"
"Either you meant to write a single quote, ', or copied Python 2 code;\n"
"in this latter case, use the function `repr(x)`."
msgstr ""
"Estás utilizando el carácter de comillas.\n"
"O bien has querido escribir una comilla simple, ', o has copiado el código "
"de Python 2;\n"
"en este último caso, utiliza la función `repr(x)`."

#: syntax_errors\statement_analyzer.py:245
msgid "You forgot to add a condition.\n"
msgstr "Has olvidado añadir una condición.\n"

#: syntax_errors\statement_analyzer.py:247
msgid ""
"An `if` statement requires a condition:\n"
"\n"
"    if condition:\n"
"        ...\n"
"\n"
msgstr ""
"Una declaración `if` requiere una condición:\n"
"\n"
"    if condición:\n"
"        ...\n"
"\n"

#: syntax_errors\statement_analyzer.py:253
msgid ""
"A `while` loop requires a condition:\n"
"\n"
"    while condition:\n"
"        ...\n"
"\n"
msgstr ""
"Un bucle `while` requiere una condición:\n"
"\n"
"    while condición:\n"
"        ...\n"
"\n"

#: syntax_errors\statement_analyzer.py:259
msgid "A `for` loop requires at least 3 more terms.\n"
msgstr "Un bucle `for` requiere al menos 3 términos más.\n"

#: syntax_errors\statement_analyzer.py:260
msgid ""
"A `for` loop is an iteration over a sequence:\n"
"\n"
"    for element in sequence:\n"
"        ...\n"
"\n"
msgstr ""
"Un bucle `for` es una iteración sobre una secuencia:\n"
"\n"
"    for elemento in secuencia:\n"
"        ...\n"
"\n"

#: syntax_errors\statement_analyzer.py:266
msgid "A class needs a name.\n"
msgstr "Una clase necesita un nombre.\n"

#: syntax_errors\statement_analyzer.py:267
msgid ""
"A `class` statement requires a name:\n"
"\n"
"    class SomeName:\n"
"        ...\n"
"\n"
msgstr ""
"Una declaración `class` requiere un nombre:\n"
"\n"
"    class AlgunNombre:\n"
"        ...\n"
"\n"

#: syntax_errors\statement_analyzer.py:284
msgid ""
"You cannot use the Python keyword `{word}` as an attribute.\n"
"\n"
msgstr ""
"No se puede utilizar la palabra clave de Python `{word}` como atributo.\n"
"\n"

#: syntax_errors\statement_analyzer.py:290
msgid "`{word}` cannot be used as an attribute.\n"
msgstr "`{word}` no puede utilizarse como atributo.\n"

#: syntax_errors\statement_analyzer.py:312
msgid "Perhaps you meant to write `elif`.\n"
msgstr "Tal vez querías escribir `elif`.\n"

#: syntax_errors\statement_analyzer.py:313
msgid ""
"You likely meant to use Python's `elif` keyword\n"
"but wrote `{name}` instead.\n"
"\n"
msgstr ""
"Probablemente querías usar la palabra clave `elif` de Python\n"
"pero en su lugar escribiste `{name}`.\n"
"\n"

#: syntax_errors\statement_analyzer.py:332
msgid "Did you mean `from {module} import {function}`?\n"
msgstr "¿Quieres decir `from {module} import {function}`?\n"

#: syntax_errors\statement_analyzer.py:335
msgid ""
"You wrote something like\n"
"\n"
"    import {function} from {module}\n"
"\n"
"instead of\n"
"\n"
"    from {module} import {function}\n"
"\n"
msgstr ""
"Has escrito algo como\n"
"\n"
"    import {function} from {module}\n"
"\n"
"en lugar de\n"
"\n"
"    from {module} import {function}\n"
"\n"

#: syntax_errors\statement_analyzer.py:406
msgid ""
"The augmented assignment operator is not allowed in Python version "
"{version}.\n"
msgstr ""
"El operador de asignación aumentada no está permitido en la versión "
"{version} de Python.\n"

#: syntax_errors\statement_analyzer.py:409
msgid ""
"You appear to be using the operator `:=`, sometimes called\n"
"the walrus operator. This operator requires the use of\n"
"Python 3.8 or newer. You are using version {version}.\n"
msgstr ""
"Parece que estás utilizando el operador `:=`, a veces llamado\n"
"el operador morsa. Este operador requiere el uso de\n"
"Python 3.8 o más reciente. Estás utilizando la versión {version}.\n"

#: syntax_errors\statement_analyzer.py:453
msgid "Did you write operators in an incorrect order?\n"
msgstr "¿Has escrito los operadores en un orden incorrecto?\n"

#: syntax_errors\statement_analyzer.py:454
msgid ""
"It looks like you wrote two operators (`{first}` and `{second}`)\n"
"in the wrong order: `{wrong}` instead of `{correct}`.\n"
msgstr ""
"Parece que has escrito dos operadores (`{first}` y `{second}`)\n"
"en el orden equivocado: `{wrong}` en lugar de `{correct}`.\n"

#: syntax_errors\statement_analyzer.py:490
msgid ""
"You wrote three equal signs in a row which is allowed in some\n"
"programming languages, but not in Python. To check if two objects\n"
"are equal, use two equal signs, `==`; to see if two names represent\n"
"the exact same object, use the operator `is`.\n"
msgstr ""
"Has escrito tres signos de igualdad seguidos, lo que está permitido en "
"algunos\n"
"lenguajes de programación, pero no en Python. Para comprobar si dos objetos\n"
"son iguales, usa dos signos de igualdad, `==`; para ver si dos nombres "
"representan\n"
"exactamente el mismo objeto, utiliza el operador `is`.\n"

#: syntax_errors\statement_analyzer.py:496
msgid "Did you mean to use `is` instead of `===`?\n"
msgstr "¿Querías usar `is` en lugar de `===`?\n"

#: syntax_errors\statement_analyzer.py:500
msgid ""
"You cannot have write the same operator, `{op}`, twice in a row.\n"
"Perhaps you wrote one of them by mistake\n"
"or forgot to write something between them.\n"
msgstr ""
"No se puede escribir el mismo operador, `{op}`, dos veces seguidas.\n"
"Tal vez usted escribió uno de ellos por error\n"
"o se olvidó de escribir algo entre ellos.\n"

#: syntax_errors\statement_analyzer.py:511
msgid ""
"You cannot have these two operators, `{first}` and `{second}`,\n"
"following each other.\n"
"It looks like you tried to use a starred expression as a dict value;\n"
"this is not allowed.\n"
msgstr ""
"No puedes tener estos dos operadores, `{first}` y `{second}`,\n"
"siguiéndose el uno al otro.\n"
"Parece que usted trató de usar una expresión estelar como un valor de dict;\n"
"esto no está permitido.\n"

#: syntax_errors\statement_analyzer.py:528
msgid ""
"You cannot have these two operators, `{first}` and `{second}`,\n"
"following each other. Perhaps you wrote one of them by mistake\n"
"or forgot to write something between them.\n"
msgstr ""
"No puedes tener estos dos operadores, `{first}` y `{second}`,\n"
"siguiéndose el uno al otro. Tal vez usted escribió uno de ellos por error\n"
"o se olvidó de escribir algo entre ellos.\n"

#: syntax_errors\statement_analyzer.py:535
msgid ""
"Or perhaps you included a space by mistake between the two operators\n"
"and meant to write `{oper}` as a single operator.\n"
msgstr ""
"O quizás incluyó un espacio por error entre los dos operadores\n"
"y quiso escribir `{oper}` como un solo operador.\n"

#: syntax_errors\statement_analyzer.py:570
msgid "Did you mean to use `=`?\n"
msgstr "¿Querías usar `=`?\n"

#: syntax_errors\statement_analyzer.py:571
msgid ""
"You use the augmented assignment operator `:=` where\n"
"the normal assignment operator `=` was required.\n"
msgstr ""
"Se utiliza el operador de asignación aumentado `:=` donde\n"
"el operador de asignación normal `=` era necesario.\n"

#: syntax_errors\statement_analyzer.py:617
msgid ""
"The following statement would not contain a syntax error:\n"
"\n"
"    {new_statement}"
msgstr ""
"La siguiente sentencia no contendría un error de sintaxis:\n"
"\n"
"    {new_statement}"

#: syntax_errors\statement_analyzer.py:623
msgid "Perhaps you needed `==` or `:=` instead of `=`.\n"
msgstr "Tal vez necesitabas `==` o `:=` en lugar de `=`.\n"

#: syntax_errors\statement_analyzer.py:624
msgid ""
"You used an assignment operator `=`; perhaps you meant to use \n"
"an equality operator, `==`, or the walrus operator `:=`.\n"
msgstr ""
"Has utilizado un operador de asignación `=`; quizás querías utilizar \n"
"un operador de igualdad, `==`, o el operador de asignación aumentado `:=`.\n"

#: syntax_errors\statement_analyzer.py:682
msgid ""
"It looks as if you are attempting to use pip to install a module.\n"
"`pip` is a command that needs to run in a terminal,\n"
"not from a Python interpreter.\n"
msgstr ""
"Parece que está intentando utilizar pip para instalar un módulo.\n"
"`pip` es un comando que debe ejecutarse en una terminal,\n"
"no desde un intérprete de Python.\n"

#: syntax_errors\statement_analyzer.py:690
msgid "Pip cannot be used in a Python interpreter.\n"
msgstr "Pip no puede ser utilizado en un intérprete de Python.\n"

#: syntax_errors\statement_analyzer.py:693
msgid ""
"I am guessing that you are attempting to use Python to run a program.\n"
"You must do so from a terminal and not from a Python interpreter.\n"
msgstr ""
"Supongo que estás intentando utilizar Python para ejecutar un programa.\n"
"Debe hacerlo desde un terminal y no desde un intérprete de Python.\n"

#: syntax_errors\statement_analyzer.py:703
msgid "You cannot have a dot `.` followed by `{bracket}`.\n"
msgstr "No puede haber un punto `.` seguido de `{bracket}`.\n"

#: syntax_errors\statement_analyzer.py:719
msgid "Perhaps you need to replace the dot by a comma.\n"
msgstr "Tal vez haya que sustituir el punto por una coma.\n"

#: syntax_errors\statement_analyzer.py:730
msgid ""
"It looks like you are trying to raise an exception using Python 2 syntax.\n"
msgstr ""
"Parece que estás intentando lanzar una excepción utilizando la sintaxis de "
"Python 2.\n"

#: syntax_errors\statement_analyzer.py:791
msgid "Did you forget a colon `:`?\n"
msgstr "¿Olvidaste los dos puntos `:`?\n"

#: syntax_errors\statement_analyzer.py:795
msgid ""
"You wrote a `{for_while}` loop but\n"
"forgot to add a colon `:` at the end\n"
"\n"
msgstr ""
"Has escrito un bucle `{for_while}` pero\n"
"olvidó añadir dos puntos `:` al final\n"
"\n"

#: syntax_errors\statement_analyzer.py:802
msgid ""
"You wrote a statement beginning with\n"
"`{name}` but forgot to add a colon `:` at the end.\n"
"\n"
msgstr ""
"Ha escrito una sentencia que empieza por\n"
"{name}` pero se olvidó de añadir los dos puntos `:` al final.\n"
"\n"

#: syntax_errors\statement_analyzer.py:826
msgid "You wrote a semicolon, `;`, where a comma was expected.\n"
msgstr "Has escrito un punto y coma, `;`, donde se esperaba una coma.\n"

#: syntax_errors\statement_analyzer.py:846
msgid "You wrote semicolons, `;`, where commas were expected.\n"
msgstr "Has escrito punto y coma, `;`, donde se esperaban comas.\n"

#: syntax_errors\statement_analyzer.py:847
msgid "Did you mean to write commas?\n"
msgstr "¿Querías escribir comas?\n"

#: syntax_errors\statement_analyzer.py:867
msgid "You wrote a semicolon, `;`, where a colon was expected.\n"
msgstr "Has escrito un punto y coma, `;`, donde se esperaba dos puntos.\n"

#: syntax_errors\statement_analyzer.py:868
msgid "Did you mean to write a colon?\n"
msgstr "¿Querías escribir dos puntos?\n"

#: syntax_errors\statement_analyzer.py:886
msgid "Did you made a mistake in writing an hexadecimal integer?\n"
msgstr "¿Te has equivocado al escribir un entero hexadecimal?\n"

#: syntax_errors\statement_analyzer.py:887
msgid ""
"It looks like you used an invalid character (`{character}`) in an "
"hexadecimal number.\n"
"\n"
"Hexadecimal numbers are base 16 integers that use the symbols `0` to `9`\n"
"to represent values 0 to 9, and the letters `a` to `f` (or `A` to `F`)\n"
"to represent values 10 to 15.\n"
"In Python, hexadecimal numbers start with either `0x` or `0X`,\n"
"followed by the characters used to represent the value of that integer.\n"
msgstr ""
"Parece que has utilizado un carácter no válido (`{character}`) en un número "
"hexadecimal.\n"
"\n"
"Los números hexadecimales son enteros de base 16 que utilizan los símbolos "
"`0` a `9`\n"
"para representar los valores 0 a 9, y las letras `a` a `f` (o `A` a `F`)\n"
"para representar los valores del 10 al 15.\n"
"En Python, los números hexadecimales comienzan con `0x` o `0X`,\n"
"seguido de los caracteres utilizados para representar el valor de ese número "
"entero.\n"

#: syntax_errors\statement_analyzer.py:906
msgid "Did you made a mistake in writing an octal integer?\n"
msgstr "¿Te has equivocado al escribir un entero octal?\n"

#: syntax_errors\statement_analyzer.py:907
msgid ""
"It looks like you used an invalid character (`{character}`) in an octal "
"number.\n"
"\n"
"Octal numbers are base 8 integers that only use the symbols `0` to `7`\n"
"to represent values.\n"
"In Python, octal numbers start with either `0o` or `0O`,\n"
"(the digit zero followed by the letter `o`)\n"
"followed by the characters used to represent the value of that integer.\n"
msgstr ""
"Parece que has utilizado un carácter no válido (`{character}`) en un número "
"octal.\n"
"\n"
"Los números octales son enteros de base 8 que sólo utilizan los símbolos `0` "
"a `7`\n"
"para representar valores.\n"
"En Python, los números octales comienzan con `0o` o `0O`,\n"
"(el dígito cero seguido de la letra `o`)\n"
"seguido de los caracteres utilizados para representar el valor de ese número "
"entero.\n"

#: syntax_errors\statement_analyzer.py:934
msgid "Valid names cannot begin with a number.\n"
msgstr "Los nombres válidos no pueden empezar por un número.\n"

#: syntax_errors\statement_analyzer.py:941
msgid "Did you mean `{number}j`?\n"
msgstr "¿Quieres decir `{number}j`?\n"

#: syntax_errors\statement_analyzer.py:942
msgid ""
"Perhaps you thought that `i` could be used to represent\n"
"the square root of `-1`. In Python, the symbol used for this is `j`\n"
"and the complex part is written as `some_number` immediately\n"
"followed by `j`, with no spaces in between.\n"
"Perhaps you meant to write `{number}j`.\n"
msgstr ""
"Tal vez pensó que `i` podría ser utilizado para representar\n"
"la raíz cuadrada de `-1`. En Python, el símbolo utilizado para esto es `j`\n"
"y la parte compleja se escribe como `algún_número` inmediatamente\n"
"seguido de `j`, sin espacios intermedios.\n"
"Tal vez haya querido escribir `{number}j`.\n"

#: syntax_errors\statement_analyzer.py:952
#, fuzzy
#| msgid "Did you mean `{number}j`?\n"
msgid "Did you mean `{number}{second}0`?\n"
msgstr "¿Quieres decir `{number}j`?\n"

#: syntax_errors\statement_analyzer.py:955
msgid ""
"Perhaps you meant to write `{number}{second}0` in scientific notation\n"
"and forgot the numerical value for the exponent.\n"
msgstr ""

#: syntax_errors\statement_analyzer.py:962
msgid ""
"[Note: `{first} * {second}` would also be valid\n"
"since `{first}` is a complex number.]\n"
msgstr ""
"[Nota: `{first}` * {second}` también sería válido\n"
"ya que `{first}` es un número complejo].\n"

#: syntax_errors\statement_analyzer.py:973
msgid "Perhaps you forgot a multiplication operator, `{first} * {second}`.\n"
msgstr "Tal vez olvidó un operador de multiplicación, `{first} * {second}`.\n"

#: syntax_errors\statement_analyzer.py:988
msgid "Your Python version does not support this f-string feature.\n"
msgstr "Su versión de Python no soporta esta función f-string.\n"

#: syntax_errors\statement_analyzer.py:989
msgid ""
"You are likely using a 'debug' syntax of f-strings introduced\n"
"in Python version 3.8. You are using version {version}.\n"
msgstr ""
"Es probable que estés usando una sintaxis de depuración de f-strings "
"introducida\n"
"en la versión 3.8 de Python. Estás usando la versión {version}.\n"

#: syntax_errors\statement_analyzer.py:995
msgid ""
"You are likely trying to assign a value within an f-string.\n"
"This is not allowed.\n"
msgstr ""
"Es probable que esté intentando asignar un valor dentro de un f-string.\n"
"Esto no está permitido.\n"

#: syntax_errors\statement_analyzer.py:1010
msgid ""
"The content of your f-string is invalid. Please consult the documentation:\n"
"https://docs.python.org/3/reference/lexical_analysis.html#f-strings\n"
msgstr ""
"El contenido de su f-string no es válido. Consulte la documentación:\n"
"https://docs.python.org/3/reference/lexical_analysis.html#f-strings\n"

#: syntax_errors\statement_analyzer.py:1020
msgid "Python keywords cannot be used as identifiers (variable names).\n"
msgstr ""
"Las palabras clave de Python no pueden utilizarse como identificadores "
"(nombres de variables).\n"

#: syntax_errors\statement_analyzer.py:1044
msgid ""
"`lambda` does not allow parentheses around its arguments.\n"
"This was allowed in Python 2 but it not allowed in Python 3.\n"
msgstr ""
"`lambda` no permite paréntesis alrededor de sus argumentos.\n"
"Esto estaba permitido en Python 2 pero no en Python 3.\n"

#: syntax_errors\statement_analyzer.py:1061
msgid ""
"You cannot have explicit tuples as arguments.\n"
"Assign any tuple to a parameter and unpack it\n"
"within the body of the function.\n"
msgstr ""
"No se pueden tener tuplas explícitas como argumentos.\n"
"Asigne cualquier tupla a un parámetro y desempaque\n"
"dentro del cuerpo de la función.\n"

#: syntax_errors\statement_analyzer.py:1099
msgid "If you remove `{type_decl}`, you will have a valid Python statement.\n"
msgstr "Si eliminas `{type_decl}`, tendrás una declaración válida de Python.\n"

#: syntax_errors\statement_analyzer.py:1103
msgid ""
"However, even if you remove `{type_decl}`, there would still be some\n"
"some syntax errors.\n"
msgstr ""
"Sin embargo, incluso si se elimina `{type_decl}`, todavía habría algunos\n"
"algunos errores de sintaxis.\n"

#: syntax_errors\statement_analyzer.py:1108
msgid "You do not need to declare variables in Python.\n"
msgstr "No es necesario declarar variables en Python.\n"

#: syntax_errors\statement_analyzer.py:1109
msgid ""
"It looks like you were trying to declare that `{var}` was\n"
"a variable using the word `{type_decl}`.\n"
msgstr ""
"Parece que estabas intentando declarar que `{var}` era\n"
"una variable utilizando la palabra `{type_decl}`.\n"

#: syntax_errors\statement_analyzer.py:1146
msgid ""
"I am guessing that you forgot a comma between two strings\n"
"when defining a dict.\n"
"\n"
msgstr ""
"Supongo que has olvidado una coma entre dos cadenas\n"
"al definir un dict.\n"
"\n"

#: syntax_errors\statement_analyzer.py:1198
msgid "Did you forget to write `in`?\n"
msgstr "¿Olvidaste escribir `in`?\n"

#: syntax_errors\statement_analyzer.py:1199
msgid ""
"It looks as though you forgot to use the keyword `in`\n"
"as part of a `for` statement. Perhaps you meant:\n"
"\n"
"    {new_statement}\n"
"\n"
msgstr ""
"Parece que ha olvidado utilizar la palabra clave `in`\n"
"como parte de una sentencia `for`. Tal vez quiso decir:\n"
"\n"
"    {new_statement}\n"
"\n"

#: syntax_errors\statement_analyzer.py:1227
msgid "Did you forget to write parenthesis?\n"
msgstr "¿Te has olvidado de escribir paréntesis?\n"

#: syntax_errors\statement_analyzer.py:1228
msgid ""
"It looks as though you forgot to use to use parenthesis with `range`.\n"
"Perhaps you meant:\n"
"\n"
"    {new_statement}\n"
"\n"
msgstr ""
"Parece que te has olvidado de usar paréntesis con `range`.\n"
"Tal vez quisiste decir:\n"
"\n"
"    {new_statement}\n"
"\n"

#: syntax_errors\statement_analyzer.py:1260
msgid ""
"Perhaps you meant to write `{keyword}` and made a typo.\n"
"The correct line might be `{line}`\n"
msgstr ""
"Tal vez quiso escribir `{keyword}` y cometió un error.\n"
"La línea correcta podría ser `{line}`\n"

#: syntax_errors\statement_analyzer.py:1273
msgid ""
"I am guessing that you were writing a comprehension or a generator "
"expression\n"
"and use the wrong order for a condition.\n"
"The correct order depends if there is an `else` clause or not.\n"
"For example, the correct order for a list comprehensions with\n"
"condition can be either\n"
"\n"
"    [f(x) if condition else other for x in sequence]  # 'if' before 'for'\n"
"\n"
"or, if there is no `else`\n"
"\n"
"    [f(x) for x in sequence if condition]  # 'if' after 'for'\n"
"\n"
msgstr ""
"Supongo que estabas escribiendo una comprensión o una expresión generadora\n"
"y utilizas el orden incorrecto para una condición.\n"
"El orden correcto depende de si hay una cláusula `else` o no.\n"
"Por ejemplo, el orden correcto para una comprensión de lista con\n"
"condición puede ser\n"
"\n"
"    [f(x) if condición else otro for x in secuencia]  # 'if' antes de 'for'\n"
"\n"
"o, si no hay ningún `else`\n"
"\n"
"    [f(x) for x in secuencia if condición]  # 'if' despues de 'for'\n"
"\n"

#: syntax_errors\statement_analyzer.py:1385
msgid ""
"You cannot have spaces in identifiers (variable names).\n"
"Perhaps you meant `{name}`?\n"
msgstr ""
"No puede haber espacios en los identificadores (nombres de variables).\n"
"¿Quizás se refería a `{name}`?\n"

#: syntax_errors\statement_analyzer.py:1407
msgid "`bf` is an illegal string prefix.\n"
msgstr "`bf` es un prefijo de cadena no valido.\n"

#: syntax_errors\statement_analyzer.py:1408
msgid ""
"I am guessing that you wanted a binary f-string;\n"
"this is not allowed.\n"
msgstr ""
"Supongo que querías un f-string binario;\n"
"esto no está permitido.\n"

#: syntax_errors\statement_analyzer.py:1432
msgid ""
"It is possible that you forgot a comma between items in a tuple, \n"
"or between function arguments, \n"
"at the position indicated by ^.\n"
msgstr ""
"Es posible que haya olvidado una coma entre los elementos de una tupla, \n"
"o entre los argumentos de una función, \n"
"en la posición indicada por ^.\n"

#: syntax_errors\statement_analyzer.py:1440
msgid ""
"It is possible that you forgot a comma between items in a list\n"
"at the position indicated by ^.\n"
msgstr ""
"Es posible que haya olvidado una coma entre los elementos de una lista\n"
"en la posición indicada por ^.\n"

#: syntax_errors\statement_analyzer.py:1446
msgid ""
"It is possible that you forgot a comma between items in a set or dict\n"
"at the position indicated by ^.\n"
msgstr ""
"Es posible que haya olvidado una coma entre los elementos de un set o dict\n"
"en la posición indicada por ^.\n"

#: syntax_errors\statement_analyzer.py:1476
msgid ""
"Python indicates that the error is caused by `{second}` written immediately "
"after `{first}`.\n"
msgstr ""
"Python indica que el error es causado por `{second}` escrito inmediatamente "
"después de `{first}`.\n"

#: syntax_errors\statement_analyzer.py:1533
msgid "Perhaps you meant{line}"
msgstr "Tal vez quiso decir{line}."

#: syntax_errors\statement_analyzer.py:1540
msgid "Did you forget something between `{first}` and `{second}`?\n"
msgstr "¿Olvidaste algo entre `{first}` y `{second}`?\n"

#: syntax_errors\statement_analyzer.py:1555
msgid ""
"Perhaps you meant to insert an operator like `{operators}`\n"
"between `{first}` and `{second}`.\n"
"The following lines of code would not cause any `SyntaxError`:\n"
"\n"
msgstr ""
"Tal vez usted quería insertar un operador como `{operators}`\n"
"entre `{first}` y `{second}`.\n"
"Las siguientes líneas de código no causarían ningún `SyntaxError`:\n"
"\n"

#: syntax_errors\statement_analyzer.py:1564
msgid ""
"Note: these are just some of the possible choices and that\n"
"some of them might raise other types of exceptions.\n"
msgstr ""
"Nota: estas son sólo algunas de las opciones posibles y que\n"
"algunas de ellas pueden generar otros tipos de excepciones.\n"

#: syntax_errors\statement_analyzer.py:1571
msgid "There is an additional possibility.\n"
msgstr "Hay una posibilidad adicional.\n"

#: syntax_errors\statement_analyzer.py:1586
msgid ""
"It is possible that you used an equal sign `=` instead of a colon `:`\n"
"to assign values to keys in a dict\n"
"before or at the position indicated by ^.\n"
msgstr ""
"Es posible que haya utilizado un signo igual `=` en lugar de dos puntos `:`\n"
"para asignar valores a las claves de un dict\n"
"antes o en la posición indicada por ^.\n"

#: syntax_errors\statement_analyzer.py:1609
msgid ""
"The Python keyword `{boolean}` can only be used for boolean expressions.\n"
"Perhaps you meant to write\n"
"\n"
"`{new_statement}`\n"
msgstr ""
"La palabra clave de Python `{boolean}` sólo puede utilizarse para "
"expresiones booleanas.\n"
"Quizás haya querido escribir\n"
"\n"
"`{new_statement}`\n"

#: syntax_errors\statement_analyzer.py:1639
msgid ""
"I am guessing that you are trying to import at least one object\n"
"from module `{module}` and rename it using the Python keyword `as`;\n"
"this keyword can only be used to rename one object at a time\n"
"using a well defined syntax.\n"
"I suggest that you split up any such import statement with each object\n"
"renamed on a separate line as follows:\n"
"\n"
"    from {module} import object_1 as name_1\n"
"    from {module} import object_2 as name_2  # if needed\n"
msgstr ""
"Supongo que estás intentando importar al menos un objeto\n"
"del módulo `{module}` y renombrarlo usando la palabra clave de Python `as`;\n"
"esta palabra clave sólo puede ser utilizada para renombrar un objeto a la "
"vez\n"
"utilizando una sintaxis bien definida.\n"
"Le sugiero que divida cualquier declaración de importación con cada objeto\n"
"renombrado en una línea separada como sigue:\n"
"\n"
"    from {module} import objeto_1 as nombre_1\n"
"    from {module} import objeto_2 as nombre_2  # si es necesario\n"

#: syntax_errors\statement_analyzer.py:1669
msgid ""
"I am guessing that you wrote {bad_token} twice in a row by mistake.\n"
"If that is the case, you need to remove the second one.\n"
msgstr ""
"Supongo que has escrito {bad_token} dos veces seguidas por error.\n"
"Si ese es el caso, tienes que eliminar la segunda.\n"

#: syntax_errors\statement_analyzer.py:1673
msgid "Did you write {bad_token} twice by mistake?\n"
msgstr "¿Has escrito {bad_token} dos veces por error?\n"

#: syntax_errors\statement_analyzer.py:1700
msgid ""
"I am guessing that you wrote {bad_token} by mistake.\n"
"Removing it and writing `{line}` seems to fix the error.\n"
msgstr ""
"Supongo que has escrito {bad_token} por error.\n"
"Quitándolo y escribiendo `{line}` parece que se solucionara el error.\n"

#: syntax_errors\statement_analyzer.py:1704
msgid "Did you write {bad_token} by mistake?\n"
msgstr "¿Has escrito {bad_token} por error?\n"

#: syntax_errors\statement_analyzer.py:1721
msgid ""
"It looks like the error occurred as you were writing a Python dict.\n"
"Perhaps wrote a dict key without writing the corresponding value.\n"
msgstr ""
"Parece que el error se ha producido al escribir un `dict` de Python.\n"
"Tal vez escribió una clave de `dict` sin escribir el valor correspondiente.\n"

#: syntax_errors\statement_analyzer.py:1737
msgid ""
"The `else` keyword does not begin a code block that matches\n"
"a valid code block, possibly because `else` is not indented correctly.\n"
msgstr ""
"La palabra clave `else` no comienza un bloque de código que coincide con\n"
"un bloque de código válido, posiblemente porque `else` no está indentado "
"correctamente.\n"

#: syntax_errors\statement_analyzer.py:1749
msgid ""
"The `elif` keyword does not begin a code block that matches\n"
"an `if` block, possibly because `elif` is not indented correctly.\n"
msgstr ""
"La palabra clave `elif` no comienza un bloque de código que coincide con\n"
"un bloque `if`, posiblemente porque `elif` no tiene el indentado correcto.\n"

#: syntax_errors\statement_analyzer.py:1762
#, fuzzy
#| msgid ""
#| "The `elif` keyword does not begin a code block that matches\n"
#| "an `if` block, possibly because `elif` is not indented correctly.\n"
msgid ""
"The `except` keyword does not begin a code block that matches\n"
"a `try` block, possibly because `except` is not indented correctly.\n"
msgstr ""
"La palabra clave `elif` no comienza un bloque de código que coincide con\n"
"un bloque `if`, posiblemente porque `elif` no tiene el indentado correcto.\n"

#: syntax_errors\statement_analyzer.py:1775
#, fuzzy
#| msgid ""
#| "The `elif` keyword does not begin a code block that matches\n"
#| "an `if` block, possibly because `elif` is not indented correctly.\n"
msgid ""
"The `finally` keyword does not begin a code block that matches\n"
"a `try` block, possibly because `finally` is not indented correctly.\n"
msgstr ""
"La palabra clave `elif` no comienza un bloque de código que coincide con\n"
"un bloque `if`, posiblemente porque `elif` no tiene el indentado correcto.\n"

#: syntax_errors\statement_analyzer.py:1814
msgid "You used square brackets, `[...]` instead of parentheses.\n"
msgstr "Has utilizado corchetes, `[...]` en lugar de paréntesis.\n"

#: syntax_errors\statement_analyzer.py:1818
msgid ""
"Write the following instead:\n"
"\n"
"{new_statement}"
msgstr ""
"Escriba lo siguiente en su lugar:\n"
"\n"
"{new_statement}"

#: syntax_errors\statement_analyzer.py:1862
msgid "The opening {bracket} on line {linenumber} is not closed.\n"
msgstr "El {bracket} de apertura en la línea {linenumber} no está cerrado.\n"

#: syntax_errors\statement_analyzer.py:1876
msgid "If this is incorrect, please report this case.\n"
msgstr "Si esto es incorrecto, por favor reporte este caso.\n"

#: syntax_errors\statement_analyzer.py:1888
msgid ""
"Perhaps you wrote a statement beginning a code block\n"
"intended to be part of a generator expression.\n"
"You cannot have separate code blocks inside generator expressions.\n"
msgstr ""
"Tal vez usted escribió una declaración que comienza un bloque de código\n"
"destinado a formar parte de una expresión del generador.\n"
"No puedes tener bloques de código separados dentro de las expresiones del "
"generador.\n"

#: syntax_errors\statement_analyzer.py:1894
msgid ""
"Perhaps you wrote a statement beginning a code block\n"
"intended to be part of a list comprehension.\n"
"You cannot have separate code blocks inside list comprehensions.\n"
msgstr ""
"Tal vez usted escribió una declaración que comienza un bloque de código\n"
"destinado a formar parte de una comprensión de lista.\n"
"No se pueden tener bloques de código separados dentro de las comprensiones "
"de listas.\n"

#: syntax_errors\statement_analyzer.py:1900
msgid ""
"Perhaps you wrote a statement beginning a code block\n"
"intended to be part of a dict or set comprehension.\n"
"You cannot have separate code blocks inside dict or set comprehensions.\n"
msgstr ""
"Tal vez usted escribió una declaración que comienza un bloque de código\n"
"destinado a formar parte de una comprensión dict o set.\n"
"No puedes tener bloques de código separados dentro de las comprensiones dict "
"o set.\n"

#: syntax_errors\statement_analyzer.py:1906
msgid "If this explanation is incorrect, please report this case.\n"
msgstr "Si esta explicación es incorrecta, por favor informe de este caso.\n"

#: syntax_errors\syntax_utils.py:22
msgid "parenthesis `(`"
msgstr "paréntesis `(`"

#: syntax_errors\syntax_utils.py:23
msgid "parenthesis `)`"
msgstr "paréntesis `)`"

#: syntax_errors\syntax_utils.py:24
msgid "square bracket `[`"
msgstr "corchete `[`"

#: syntax_errors\syntax_utils.py:25
msgid "square bracket `]`"
msgstr "corchete `]`"

#: syntax_errors\syntax_utils.py:26
msgid "curly bracket `{`"
msgstr "llave `{`"

#: syntax_errors\syntax_utils.py:27
msgid "curly bracket `}`"
msgstr "llave `}`"

#: syntax_errors\syntax_utils.py:60
msgid "Did you mean to use a normal quote character, `'` or `\"`?\n"
msgstr "¿Quería utilizar un carácter de comillas normal, `'` o `\"`?\n"

#: syntax_errors\syntax_utils.py:61
msgid ""
"I suspect that you used a fancy unicode quotation mark\n"
"whose name is {name}\n"
"instead of a normal single or double quote for a string.\n"
msgstr ""
"Sospecho que has utilizado una comilla unicode de fantasía\n"
"cuyo nombre es {name}\n"
"en lugar de una comilla simple o doble normal para una cadena.\n"

#: syntax_errors\syntax_utils.py:76
msgid "Or perhaps, you meant to write a less than sign, `<`.\n"
msgstr "O tal vez, quisiste escribir un signo menos que, `<`.\n"

#: syntax_errors\syntax_utils.py:78
msgid "Or perhaps, you meant to write a greater than sign, `>`.\n"
msgstr "O tal vez, quisiste escribir un signo mayor que, `>`.\n"

#: syntax_errors\syntax_utils.py:80
msgid "Or perhaps, you meant to write a comma.\n"
msgstr "O tal vez, quisiste escribir una coma.\n"

#: syntax_errors\syntax_utils.py:97
msgid ""
"I suspect that you used a fancy unicode quotation mark\n"
"whose name is {name}.\n"
"\n"
msgstr ""
"Sospecho que has utilizado una comilla elegante unicode\n"
"cuyo nombre es {name}.\n"
"\n"

#: syntax_errors\syntax_utils.py:112
msgid "Perhaps, you meant to write a less than sign, `<`.\n"
msgstr "Tal vez, quisiste escribir un signo menos que, `<`.\n"

#: syntax_errors\syntax_utils.py:113
msgid "Did you mean to write a less than sign, `<`?\n"
msgstr "¿Querías escribir un signo menos que, `<`?\n"

#: syntax_errors\syntax_utils.py:115
msgid "Perhaps, you meant to write a greater than sign, `>`.\n"
msgstr "Tal vez, quisiste escribir un signo mayor que, `>`.\n"

#: syntax_errors\syntax_utils.py:116
msgid "Did you mean to write a greater than sign, `>`?\n"
msgstr "¿Querías escribir un signo mayor que, `>`?\n"

#: syntax_errors\syntax_utils.py:118
msgid "Perhaps, you meant to write a comma.\n"
msgstr "Tal vez, quisiste escribir una coma.\n"

#: syntax_errors\syntax_utils.py:136
msgid ""
"I suspect that you used the unicode character known as\n"
"'FRACTION SLASH', which looks similar to\n"
"but is different from the division operator `/`.\n"
msgstr ""
"Sospecho que has utilizado el carácter unicode conocido como\n"
"'FRACTION SLASH', que es similar a\n"
"pero es diferente del operador de división `/`.\n"

#: syntax_errors\syntax_utils.py:143
msgid "Did you use a unicode fraction?\n"
msgstr "¿Usaste una fracción unicode?\n"

#: syntax_errors\syntax_utils.py:144
msgid ""
"I suspect that you used the unicode character `{char}`meant to represent a "
"fraction.\n"
"The name of this unicode character is {name}.\n"
msgstr ""
"Sospecho que has utilizado el carácter unicode `{char}` para representar una "
"fracción.\n"
"El nombre de este carácter unicode es {name}.\n"

#: syntax_errors\syntax_utils.py:181
msgid "Did you mean `{num}/{denom}`?\n"
msgstr "¿Quieres decir `{num}/{denom}`?\n"

#: syntax_errors\syntax_utils.py:182
msgid ""
"You used the unicode character {char} which is known as\n"
"{name}\n"
"I suspect that you meant to write the fraction `{num}/{denom}` instead.\n"
msgstr ""
"Has utilizado el carácter unicode {char} que se conoce como\n"
"{name}\n"
"Sospecho que querías escribir la fracción `{num}/{denom}` en su lugar.\n"

#: warning_parsers\syntax_warning.py:47
msgid ""
"You have {container_type} followed by square brackets, `[...]`.\n"
"What is included between the square brackets, `[...]`,\n"
"must be either an integer or a slice\n"
"(`start:stop` or `start:stop:step`) \n"
"and you have used {obj_type} instead.\n"
msgstr ""

#~ msgid "Changes the prompt style to be used in the Friendly console."
#~ msgstr "Cambia el estilo del indicador de consola que será utilizado."

#~ msgid "Nothing to go back to: no exception recorded."
#~ msgstr "Nada a donde volver: no se registró excepción alguna."

#~ msgid "Removes the last recorded traceback item."
#~ msgstr "Elimina el último elemento del trackback registrado."

#~ msgid "No information is available about this warning.\n"
#~ msgstr "No hay información disponible sobre esta advertencia.\n"

#, fuzzy
#~| msgid ""
#~| "Perhaps you meant\n"
#~| "\n"
#~| "    {line}\n"
#~ msgid ""
#~ "Perhaps you meant\n"
#~ "\n"
#~ "{line}\n"
#~ msgstr ""
#~ "Tal vez se refería a\n"
#~ "\n"
#~ "    {line}\n"

#~ msgid ""
#~ "In older version of Python, `print` was a keyword.\n"
#~ "Now, `print` is a function; you need to use parentheses to call it.\n"
#~ msgstr ""
#~ "En la versión anterior de Python, `print` era una palabra clave.\n"
#~ "Ahora, `print` es una función; necesitas usar paréntesis para llamarla.\n"

#~ msgid ""
#~ "Perhaps you meant\n"
#~ "\n"
#~ "    {line}\n"
#~ msgstr ""
#~ "Tal vez se refería a\n"
#~ "\n"
#~ "    {line}\n"

#~ msgid "Perhaps you misplaced a quote.\n"
#~ msgstr "Tal vez ubicaste en el lugar incorrecto una comilla.\n"

#~ msgid ""
#~ "There appears to be a Python identifier (variable name)\n"
#~ "immediately following a string.\n"
#~ "I suspect that you were trying to use a quote inside a string\n"
#~ "that was enclosed in quotes of the same kind.\n"
#~ msgstr ""
#~ "Parece que hay un identificador Python (nombre de variable)\n"
#~ "inmediatamente después de una cadena.\n"
#~ "Sospecho que estabas tratando de usar una comilla dentro de una cadena\n"
#~ "que estaba encerrada entre comillas del mismo tipo.\n"

#~ msgid "some value"
#~ msgstr "algún valor"

#~ msgid ""
#~ "You wrote an expression like\n"
#~ "\n"
#~ "    {fn_call} = {value}\n"
#~ "\n"
#~ "where `{fn_call}`, on the left-hand side of the equal sign, is\n"
#~ "a function call and not the name of a variable.\n"
#~ msgstr ""
#~ "Has escrito una expresión como\n"
#~ "\n"
#~ "    {fn_call} = {value}\n"
#~ "\n"
#~ "en donde `{fn_call}`, a la izquierda del signo de igualdad, es\n"
#~ "una llamada a una función y no el nombre de una variable.\n"

#~ msgid ""
#~ "`{filename}` is not a regular Python file whose contents\n"
#~ "can be analyzed.\n"
#~ msgstr ""
#~ "`{filename}` no es un archivo regular de Python cuyo contenido\n"
#~ "puede ser analizado.\n"
